-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "干瞪眼", order = 1, SpeakText = "快点儿，都等的我花儿都谢了~", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "干瞪眼", order = 2, SpeakText = "怎么又断线了，网络怎么这么差呀", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "干瞪眼", order = 3, SpeakText = "不要走，决战到天亮", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "干瞪眼", order = 4, SpeakText = "你的牌打的太好了", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "干瞪眼", order = 5, SpeakText = "你是妹妹还是哥哥啊？", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "干瞪眼", order = 6, SpeakText = "和你合作真是太愉快了", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "干瞪眼", order = 7, SpeakText = "大家好，很高兴见到各位", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "干瞪眼", order = 8, SpeakText = "哎，各位真是不好意思，我得离开一会", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 109, GameName = "干瞪眼", order = 9, SpeakText = "不要吵了不要吵了，吵啥嘛吵，专心玩游戏", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 110, GameName = "干瞪眼", order = 10, SpeakText = "交个朋友吧，能告诉我你的联系方式吗？", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "干瞪眼", order = 11, SpeakText = "下次我们再玩吧，我要走了！", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 112, GameName = "干瞪眼", order = 12, SpeakText = "再见咯，我会想念大家的！", M_SpeakFileName = "M_Speak112.mp3", W_SpeakFileName = "W_Speak112.mp3", listIndex = 1 	}
	}
}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

-- index
tab.GameSpeakConfigByindex = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByindex[rec.index] = rec
end

tab.Enum = {
}

return tab