local InvateConfig = 
{
    -- 温州（茶）
    [XH.LOBBY_ID.WENZHOU] = 
    {
        KW_INVATE_REWARD_TIP = "输入邀请码，立即获得10张房卡",
        KW_WECHAT_ACCOUNT_TEXT_CREATEBOXROOM = "",
        KW_WECHAT_ACCOUNT_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_KWFU_NAME_TEXT_HISTORYBILL = "温州（茶）",
        KW_WECHAT_ACCOUNT_KEFU_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_CHECK = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_TUIGUANGYUAN = "",
    },
    -- 瑞安
    [XH.LOBBY_ID.RUIAN] = 
    {
        KW_INVATE_REWARD_TIP = "输入邀请码，立即获得10张房卡",
        KW_WECHAT_ACCOUNT_TEXT_CREATEBOXROOM = "",        
        KW_WECHAT_ACCOUNT_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_KWFU_NAME_TEXT_HISTORYBILL = "瑞安",
        KW_WECHAT_ACCOUNT_KEFU_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_CHECK = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_TUIGUANGYUAN = "",
    },
    -- 台州
    [XH.LOBBY_ID.TAIZHOU] = 
    {
        KW_INVATE_REWARD_TIP = "输入邀请码，立即获得12张房卡",
        KW_WECHAT_ACCOUNT_TEXT_CREATEBOXROOM = "",        
        KW_WECHAT_ACCOUNT_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_KWFU_NAME_TEXT_HISTORYBILL = "台州",
        KW_WECHAT_ACCOUNT_KEFU_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_CHECK = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_TUIGUANGYUAN = "",
    },
    -- 乐清
    [XH.LOBBY_ID.YUEQING] = 
    {
        KW_INVATE_REWARD_TIP = "输入邀请码，立即获得10张房卡",
        KW_WECHAT_ACCOUNT_TEXT_CREATEBOXROOM = "",        
        KW_WECHAT_ACCOUNT_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_KWFU_NAME_TEXT_HISTORYBILL = "乐清",
        KW_WECHAT_ACCOUNT_KEFU_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_CHECK = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_TUIGUANGYUAN = "",
    },
    ["default"] = 
    {
        KW_INVATE_REWARD_TIP = "输入邀请码，立即获得10张房卡",
        KW_WECHAT_ACCOUNT_TEXT_CREATEBOXROOM = "",
        KW_WECHAT_ACCOUNT_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_KWFU_NAME_TEXT_HISTORYBILL = "温州（茶）",
        KW_WECHAT_ACCOUNT_KEFU_TEXT_HISTORYBILL = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_CHECK = "",
        KW_WECHAT_ACCOUNT_TEXT_INVITE_TUIGUANGYUAN = "",
	},    
}


return InvateConfigW
