return {
	--样例 ["XXX"] = "XXX"
    ["APP_NAME"]                = "浙江游戏大厅",
    ["MSG_SEND_SUCCESS"]        = "连接服务器成功!" ,
    ["MSG_SEND_FAIL"]           = "连接服务器失败，请检查网络连接!" ,
    ["MSG_SEND_TIME_OUT"]       = "连接服务器超时，请检查网络连接!",

	["SHOW_MESSAGE"]            = "您的登录信息错误(1)!",
    ["PTUSER_NEED_REGISTER"]    = "帐号错误，请您注册平台帐号(2).",
    ["UNKNOW_USERID"]           = "您登录的帐号不存在，请重新登录(3).",
    ["INVALID_PASSWORD"]        = "您的密码输入错误，请重新输入(4).",
    ["UNKNOW_USERTYPE"]         = "您的账号存在类型异常，请联系客服(5).",
    ["LOCALAUTH_USERTYPE_ERR"]  = "您的帐号已经被停封(13).",
    ["PLAYERCENTER_SEND_ERR"]   = "发送协议失败，请您重新尝试(玩家中心).",
    ["PTSVR_SEND_ERR"]          = "发送协议失败，请您重新尝试(PTSVR).",
    ["NO_PTINFO"]               = "没有找到您的账号信息，请重新登录(users_pt).",
    ["NO_AUTHFLAG"]             = "没有找到您的认证标志，请重新登录(游戏认证).",
    --["DBERR"]                   = "您的数据存在异常，请稍后重试(数据库).",
    ["DBCONNERR"]               = "您的数据存在异常，请稍后重试(表连接未找到).",
    ["FORBID_USERID"]           = "您的帐号已经被停封.",
    ["LOCK_BY_USER_SELF"]       = "您的帐号被自己锁定，请联系客服.",
    ["INVALID_HARDWARE"]        = "您登录手机的硬件码存在错误，请稍后重试.",
    ["PT_TIME_OUT"]             = "返回信息超时，请检查网络(ptsvr).",
    ["PC_SEND_ERR"]             = "发送协议失败，请检查网络(playercenter).",
    ["PC_TIME_OUT"]             = "接收信息超时，请检查网络(playercenter).",
    ["AD_SEND_ERR"]             = "发送信息失败，请检查网络(AccountDataSvr).",
    ["AD_TIME_OUT"]             = "接收信息超时，请检查网络(AccountDataSvr).",
    --["POST_SENDERR"]            = "发送协议失败，请检查网络(post).",
    --["POST_TIMEOUT"]            = "接收信息超时，请检查网络(post).",
    ["RISK_REFUSE"]             = "登录失败，请联系客服.",
    ["LOBBYVER_OLDR"]           = "您有新的游戏版本更新，请尽快更新保证体验.",
    ["LOBBYVER_TOOOLD"]         = "您的游戏版本太过老旧，请立即进行更新.",
    ["LOBBYVER_TOONEW"]         = "您的游戏版本异常，请立即进行更新.",
    ["SMS_SEND_ERR"]            = "发送短信失败，请重新发送.",
    ["INVALID_SMSCODE"]         = "短信验证码填写错误，请重新填写.",
    ["NO_SMSCODE"]              = "短信验证码超时，请重新发送.",
    ["UNKNOW_AREAID"]           = "您的地理位置错误(areaid).",
    ["POST_SEND_ERR"]           = "发送协议失败，请检查网络(post).",
    ["OTP_TIME_OUT"]            = "接收信息超时，请检查网络(otpsvr).",
    ["INVALID_SCREEN"]          = "您的屏幕分辨率存在问题.",
    ["NO_GAMEPOST"]             = "您的游戏地址错误.",
    ["INVALID_SESSIONID"]       = "您的令牌错误，请重新尝试",
    ["NO_SESSIONID"]            = "您的令牌信息存在异常",
    ["INVALID_SESSIONID_PC"]    = "您的令牌及设备码错误",
    ["INVALID_SESSIONID_IP"]    = "您的令牌、设备码及IP信息错误",
    --["PLAYERCENTER_BANTO_LOGIN"]    = "您的账号存在异常，请联系客服",
    ["ACCOUNT_ERR"]                 = "您的登录方式选择错误，请重新选择",
    ["ACCOUNT_NOT_EXIST"]           = "您的账号不存在，请重新登录",
    ["ACCOUNT_PWD_ERR"]             = "手机登录失败，请重新验证并登录",
    ["BIND_COMPUTER"]               = "您的帐号已绑定，请先进行解绑",
    ["BAN_LOGIN"]                   = "您的帐号被禁止登录，请联系客服核实",
    ["PLAYERCENTER_BANTO_LOGIN"]    = "您的账号存在异常，请联系客服",
    ["CNENTER_BANTO_IP"]            = "您的IP地址存在异常，请联系客服",
    ["PLAEYER_CNENTER_DB_ERR"]      = "您的账号存在数据异常，请联系客服",
    ["ARED_ID_ERR"]                 = "您的区号错误，请重新登录",
    ["NUMBER_ACCOUNT_ERR"]          = "您的数字帐号错误，请重新登录",
    ["SYSTEM_BANTO_LOGIN"]          = "您的登录异常，请检查网络",
    ["SERVER_NO_ERR"]               = "选择的游戏或服务器异常，请重新登录",
    ["HARDWARE_CODE_ERR"]           = "选择服务器异常，请重新登录",
    ["ERROR"]                       = "网络异常，请检查网络环境",
    ["SESSIONID_ERROR"]             = "网络异常，请检查网络环境(SESSIONID错误)",
    ["SYSTEM_MAINTAIN"]             = "系统正在维护当中，请稍候再登录",
    ["FREQUENT_LOGIN"]              = "频繁登录，请稍后再试",
    ["ACCOUNTORPWD_ERROR_1"]        = "您输入的帐号密码有误，请重新输入！",
    ["ACCOUNTORPWD_ERROR_2"]        = "您输入的帐号密码有误，请重新输入！",
    ["SYSTEM_REFUSE_LOGIN"]         = "您的账号存在异常，请联系客服",
    ["NOT_BING_PWD_PRO"]            = "您还没绑定密宝",
    ["PWD_PRO_ERROR"]               = "您的输入的密宝有误，请重新输入",
    ["NEED_TWO_PWD"]                = "请输入二级密码进行登录",
    ["ACCOUNT_ALREADY_EXIST"]           = "您的游戏ID异常，请联系客服",
    ["ACCOUNT_LOGIN_OTHER"]         = "您的帐号已在其它地方登录，请妥善保管账号信息",
    ["ID_EXIST"]                    = "游戏ID已经存在，请重新尝试",
    ["PT_LOGIN_FAIL"]               = "登录失败，请重新尝试(PT)",
    ["ACCOUNT_SIMPLE_BIND"]         = "您的帐号已绑定，请使用绑定的设备进行登录",
    ["UNKNOWN_THIRDID"]             = "手机暂未绑定手机号",
    ["ACCOUNT_NEED_PWD_BIND"]       = "您的帐号必须使用密宝进行登录",
    ["ACCOUNT_NEED_SAGE_CARD_LOGIN"]      = "您的帐号必须使用安全卡进行登录",
    ["ACCOUNT_NEED_SAGE_CARD_LOGIN_1"]    = "您的帐号必须使用安全卡进行登录",
    

    --包厢创建加入相关的错误码
    ["ERROR_PARAM"]             = "房间上传的参数有误，请稍后重试",
    ["ERROR_GET_GAME_APPID"]    = "游戏服务异常，请稍后重试(appid)",
    ["ERROR_CREATE_ROOM_ID"]    = "创建房间号码异常，请重新创建房间",
    ["ERROR_SAVE_ROOM_INFO"]    = "当前房间信息异常，请刷新进行重试",
    ["ERROR_ROOM_ID"]           = "您输入的房间号有误，请重新输入",
    ["NO_MATCH_GAME_APPID"]     = "游戏服务异常，请稍后重试(Game)",
    ["NO_FOUND_ROOM_CONFIG"]    = "您加入的房间配置异常，请稍后重试",
    ["NOT_ENOUGH_PROP"]         = "您的房间道具不足，请进行充值",
    ["ALREADY_IN_TABLE"]        = "您已经加入房间了，祝您游戏愉快",
    ["ROOM_DISMISSED"]          = "您要加入的房间已经被解散",
    ["NOT_FOUND_GAME_ID"]       = "游戏ID信息异常，请稍后重试(gameid)",
    ["NOT_TEA_HOUSE_RIGHT"]     = "您还没有此亲友圈的加入权限，请联系圈主",
    ["NOT_EMPTY_TABLE"]         =  "已经没有空的桌子了，请联系圈主",
    ["TEA_HOUSE_CLOSED"]        = "您加入的亲友圈已经关闭，请联系圈主",
    ["ERROR_GET_ROOM_MODE"]     = "获取房间信息失败，请稍后重试(roommode)",
    ["REDIS_NOT_FOUND_ROOM_ID"] = "获取房间号异常，请稍后重试(redis)",
    ["ALREADY_PLAYER_CREATE_ID"] = "已经有玩家续桌",
    ["ERROR_IP_LIMITED"]        = "由于同ip无法进入该桌子",
    ["ERROR_NOT_OPEN_GPS"]      = "没开启定位,无法加入桌子",
    ["ERROE_DISTANCE_LIMIT"]    = "由于距离过近无法进入该桌子",
    
    --金币场相关错误码
    ["ERROR_CAN_NOT_FIND_ROOM"] = "找不到能匹配的房间，请稍后重试",
    ["ERROR_MAINTENANCE"]       = "您选择的游戏正在维护中",
    ["ERROR_INAPPID"]           = "您已经在游戏房间中了",
    ["ERROR_NOT_ENOUGH_SR"]     = "您的金币不足，请进行充值",
    ["ERROR_TOO_MUCH_SR"]       = "您的金币太多了，请前往更高级的场次进行游戏",

    --工具服务错误码
    ["POST_SENDERR"]            = "游戏维护中，请稍后重试",
    ["POST_TIMEOUT"]            = "您的道具存在异常，请检查网络环境",
    ["DBERR"]                   = "您的数据存在异常，请稍后重试",
    ["GAMETABLENOTFIND"]        = "您的数据存储异常，请稍后重试",
    ["DBCONNNOTFIND"]           = "连接数据库异常，请稍后重试",
    ["SVRSCORETYPEERR"]         = "您选择金币类型错误，请稍后重试",
    ["NETBUSY"]                 = "购买失败，请重新购买",

    --手机绑定 身份认证
    ["ERROR_NOT_INPUT_PHONE"]   = "请输入您的手机",
    ["ERROR_NOT_INPUT_NAME"]    = "请输入您的姓名",
    ["ERROR_NOT_INPUT_IDENTITY"]    = "请输入您的身份证号",
    ["ERROR_NAME"]              = "您输入的姓名有误，请输入正确的姓名",
    ["ERROR_IDENTITY_NAME"]     = "您输入的姓名有误，请核对身份信息正确输入",
    ["ERROR_IDENTITY"]          = "您输入的身份证号码有误，请正确输入",
    ["IDENTITY_SUCCESS"]        = "认证成功",
    ["IDENTITY_SUCCESS_ING"]        = "等待认证中。。。",
    ["IDENTITY_ERROR"]          = "实名认证失败，请稍后重试",
    ["ERROR_PHONE"]             = "您输入的手机号码有误，请正确输入",
    ["ERROR_PHONE_CODE"]        = "您输入的验证码有误，请检查后重新输入",
    ["PHONE_BIND_SUCCESS"]      = "手机绑定成功",

    --大厅
    ["LOBBY_HEAD_NICK_NAME"]         = "%s 序号:%s",
    ["LOBBY_HEAD_ROOM_CARD"]         = "房卡:%s",
    ["LOBBY_HEAD_SR"]                = "金币:%d",

    --战绩
    ["RESULT_DETAIL_ROUND"]         = "第%d局",
    ["RESULT_DETAIL_TOTAL_ROUND"]         = "共：%s局",
    ["RESULT_ROUND_ROOMID"]         = "房间号：%s",
    ["RESULT_DETAIL_SHARE_CODE"]         = "回放码:%d",
    ["RESULT_ROUND_COUNT"]          = "局数：%s/%s",
    ["RESULT_ROUND_NO_RESULT"]          = "暂无账单成绩，创建包厢邀请好友快速开局！",
    ["RESULT_ROUND_NO_RESULT_SECOND_LINE"]          = "###########",
    ["RESULT_REPLAY_NOT_EXISTED"]          = "请求的回放不存在",
    ["RESULT_REPLAY_INVALID_SHARE_CODE"]          = "回放码错误",
    --商城
    ["ERROR_SHOP_GOLD_NOT_ENOUGH"]        = "您的金币不足，请购买金币后重试",
    ["ERROR_SHOP_DIAMOND_NOT_ENOUGH"]        = "您的钻石不足，请购买钻石后重试",
    ["ERROR_SHOP_COUPON_NOT_ENOUGH"] = "您的礼券不足，兑换失败",
    ["RESULT_SHOP_BY_MARKER_SUCCEED"] = "购买成功，快去进行游戏吧",
    ["PLEASE_REAL_NAME"] = "请先进行实名认证,再进行购买",
    ["PLEASE_REAL_NAME_2"] = "此功能需要先进行实名认证",
    ["ERROR_SHOP_ROOM_CARD_NOT_ENOUGH"]        = "您的房卡不足，请购买房卡后重试",
    ["RESULT_SHOP_BY_FREEQUAN_SUCCEED"] = "恭喜你获得会员福利，会员时效内可以免费创建包厢房间",
    ["RESULT_SHOP_BY_WECHAT_PACKTE"] = "兑换成功！\n点击【确定】查看兑换码",
    ["TIP_SHOP_ENOUGH_MID_PROP"] = "是否消耗%s，立即获得%s",
    ["PROP_NAME_SHOP_DIAMOND"] = "钻石",

    --活动
    ["ACTIVITY_ROOM_CARD"]          = "房卡X%d",
    ["ACTIVITY_DIAMOND"]            = "钻石X%d",
    ["ACTIVITY_GOAL_COUNT"]         = "金币X%d",
    ["ACTIVITY_PAN_AWARD"]          = "完成%d场对局，获得",
    ["ACTIVITY_PLAY_ROOM_CARD"]          = "%d房卡",
    ["ACTIVITY_PLAY_GOAL_COUNT"]         = "%d金币",
    ["ACTIVITY_FINISH"]             = "  (已完成)",

    --个人中心
    ["COPY_SUCCESS"]             = "复制成功",

    ["VIP_RESET_PWD_UNBIND_ERROR"]             = "手机号未绑定！\n请先绑定手机号再进行重置密码哦~";

    --你提我改
    ["YOUSUGGEST_WECHANGE"]          = "你提我改提交失败，请稍后重试",
    ["YOUSUGGEST_HAD_SUBMIT"]          = "您的建议已经成功提交",
    ["YOUSUGGEST_TOO_LITTLE"]              = "寥寥片语，无法诉说您的心声，\n请多留一些话吧。\n(请超过20个字哦)",
    ["YOUSUGGEST_TOO_MANY"]              = "或许千言万语，才足以表达您的情感，\n但还恳请您精简语言。\n(请少于100个字哦)",
    ["YOUSUGGEST_NO_CONTACT"]              = "留下联系方式，让我们能更好的帮助您，\n并确保奖励的正确发放。",
    ["YOUSUGGEST_TIPS"]              = "您的满意是我们最大的动力。\n请留下您的宝贵意见、吐槽...\n我们会用心对待，您的每次发声。",
    ["YOUSUGGEST_HAVE_NOT_SUBMIT"]              = "您有未提交的建议，提交后再离开吧。",

    --手机绑定
    ["PHONE_BIND_ERROR"]          = "请求手机绑定失败，请稍后重试",
    ["PHONE_REBIND_ERROR"]        = "请求手机换绑失败，请稍后重试",
    ["PHONE_PWD_ERROR"]           = "请求手机登录失败，请稍后重试",
    ["PHONE_BIND_STATE_ERROR"]    = "请求手机绑定状态失败，请稍后重试",
    ["PHONE_CODE_ERROR"]          = "请求手机验证码失败，请稍后重试",

    ["GET_EXCHANGE_HISTORY_ERROR"]          = "请求兑换记录失败，请稍后重试",
    ["GET_EXCHANGE_KAMI_ERROR"]          = "请求卡密失败，请稍后重试",

    ["ERROR_UNBINDWECHAT"]        = "约局游戏需要微信绑定方可进行游戏",

    --绑定功能相关
    ["BIND_AGENT_YQM_NONE"]          = "此邀请码不存在！",
    ["BIND_AGENT_REQ_FAIL"]          = "请求用户信息失败，请稍后重试！",
    ["BIND_AGENT_GET_MSG_FAIL"]      = "获取用户信息失败",
    ["BIND_AGENT_INPUT_GET_FAIL"]    = "用户序号输入有误\n请核对后重试！",
    ["BIND_AGENT_INPUT_GET_ERROR"]   = "您绑定的用户目前无法进行售卡",
    ["BIND_AGENT_INPUT_AGENT_T1"]    = "用户邀请码：",
    ["BIND_AGENT_INPUT_AGENT_T2"]    = "用户昵称：",
    ["BIND_AGENT_INPUT_AGENT_T3"]    = "是否确认绑定",
    ["BIND_AGENT_BIND_SUCCESS"]      = "绑定成功",
    ["BIND_AGENT_BIND_FAIL"]         = "绑定失败",
    ["BIND_AGENT_UNBIND_SUCCESS"]    = "解绑成功！",
    ["BIND_AGENT_UNBIND_FAIL"]       = "解绑失败,请稍后重试！",
    ["RELEASE_BIND_AGENT"]           = "是否确认解除绑定关系",
    ["GIFT_BAG_LAYER_PASS"] = "礼包已过期",
    ["GIFT_BAG_LAYER_CANNOTFIND"] = "后台配置错误,找不到可购买的商品",
    ["SUMMER_ACT_INFO_NO_COUNT"] = "无剩余开启机会,请前往获取或明日再来！",
    ["SUMMER_ACT_INFO_NO_PRIZE"] = "谢谢参与！",
    ["NATIONAL_DAY_ACT_INFO_NO_COUNT"] = "无剩余开启机会,请前往对局或明日再来！",
    ["NATIONAL_DAY_ACT_INFO_NO_PRIZE"] = "谢谢参与！",
    ["NATIONAL_DAY_ACT_OUT_DTAE"] = "不在活动期内！",
    -- 创建房间扣卡提示
    ["CREATE_TABLE_CONSUME_AFTER_FIRST_GAME"] = "注：房卡在完成第一局游戏后扣除，提前解散不扣房卡",
    ["CREATE_TABLE_CONSUME_BEFORE_FIRST_GAME"] = "注：房卡在开局后扣除",
    -- 快捷兑换相关
    ["QUICK_RECHARGE_NUM"] = "%d钻石",
    ["QUICK_RECHARGE_TIP"] = "售价:%d%s",
    ["QUICK_RECHARGE_SUCCESS"] = "购买成功",
    ["QUICK_RECHARGE_NOT_ENOUGH"] = "您的道具不足，请进行充值",
    ["QUICK_RECHARGE_GOODS_LOST"] = "充值成功，自动兑换失败",
    -- 裂变活动
    ["FISSION_ACT_TIPS"] = "再邀请一人可获\n得%s奖励",
    ["FISSION_COUNT_DOWN"] = "倒计时：剩余%s",
    ["FISSION_STAGE_END_TIP"] = "倒计时结束，开启新任务啦~",
    -- 获取Token
    ["REQ_TOKEN_ERR"] = "获取token失败",
    --注销相关
    ["WRITE_OFF_ING"] = "此账号正在申请注销，15天冻结期满将注销账号，是否撤回注销申请？",
    -- SXVIP
    ["SXVIP_REMAINER_ERROR"] = "请求会员接口失败~",
    ["USE_EQUIP_CARD_ERROR"] = "普通道具转化为时效道具接口失败~",
}   �@  