return {
    ["LobbyView"] = {
        ["_KWA_HEAD_PANEL"] = "头像",
        ["_KWA_BTN_COPY"] = "复制",
        ["_KWA_AREA_PANEL"] = "切换地区",
        ["_KWA_BTND_ADD_ROOM_CARD"] = "房卡",
        ["_KWA_BTND_ADD_GOLD"] = "金币",
        ["_KWA_BTND_ADD_DIAMOND"] = "钻石",
        ["_KWA_BTN_VIP"] = "会员",
        ["_KW_UI_OPEN_PIC"] = "牌友",
        ["_KWA_BTND_CREATE_BACK_BOX_ROOM"] = "创建房间",
        ["_KWA_GOLD_BTND_JOIN_ROOM"] = "加入房间",
        ["_KWA_BTND_PEAK_RACE_MATCH"] = "比赛场",
        ["_KWA_BTND_PEAK_RACE"] = "巅峰赛",
        ["_KW_GAME_ICON_ITEM"] = function(item)
            if item.roomConf and item.roomConf.GameTitle then
                return item.roomConf.GameTitle
            end
            return "更多游戏"
        end,
        ["_KW_UI_BACK"] = "返回大厅",
        ["_KWA_BTND_CREATE_JINBICHANG_ITEM"] = "人人捕鱼",
        -- 匹配前段字符串
        ["KWA_BTND_CREATE_"] = function(item)
            local confID = XH.StringTool.getNumberSuffixByString(item:getName())
            local roomConf = XH.goldConfigManager:getGoldRoomInfoByIndex(confID)
            if roomConf.roomInfo and roomConf.roomInfo.GameTitle then
                return roomConf.roomInfo.GameTitle
            end
        end,
    },
    ["TeaHouseMainView"] = {
        ["_KW_BTN_BACK"] = "返回",
        ["_KW_BTN_RECHARGE_1"] = "充值",
        ["_KW_BTN_RECHARGE_2"] = "充值",
        ["_KW_BTN_RECHARGE_3"] = "充值",
        ["_KW_BTN_COPY"] = "复制",
        ["_KWA_BTN_VIP"] = "会员",
        ["_KW_BTN_MEMBER_1"] = "成员详细",
        ["_KW_BTN_MEMBER_2"] = "成员详细",
        ["_KW_BTN_BILL_MANAGE_1"] = "比赛战绩",
        ["_KW_BTN_BILL_MANAGE_2"] = "比赛战绩",
        ["_KW_BTN_RANK_1"] = "排行榜",
        ["_KW_BTN_RANK_2"] = "排行榜",
        ["_KW_BTN_SETTING"] = "设置",
        ["_KW_BTN_MORE_1"] = "更多",
        ["_KW_BTN_MORE_2"] = "更多",
        ["_KW_LOG_NODE"] = "操作日志",
        ["_KW_SHARE_NODE"] = "分享",
        ["_KW_PANEL_RRBY"] = "人人捕鱼",
        ["_KW_BTN_QUIT_CLOSE"] = "闭赛",
        ["_KW_FUNC_IMG_BTN"] = "功能",
        ["teahouse_main_extend_up.png"] = "升级桌子",
        ["teahouse_main_extend_filter.png"] = "玩法刷选",
        ["tea_house_main_cusservice_btn.png"] = "客服",
        ["tea_house_main_FAQ_btn.png"] = "常见问题",
        ["_KW_BTN_LEVEL_UP"] = "升级",
        ["_KW_BTN_MAX_PLAYER"] = "人数超限",
        ["_KW_PANEL_PROMOTE"] = "推广活动",
        ["_KW_BTN_NEW_PLAY_TYPE_DRAW_1"] = "抽奖活动",
        ["_KW_BTN_FULI_1"] = "福利任务",
        ["_KW_BTN_NEW_PLAY_TYPE_DRAW_2"] = "抽奖活动",
        ["_KW_BTN_FULI_2"] = "福利任务",
        ["_KW_BTN_AGENT"] = "我要做圈主",
        ["_KW_BTN_COMPLAIN"] = "吐槽",
        ["_KW_BTN_APPLY"] = "申请加入比赛场",
    },

    ["TeaHouseOnlineListView"] = {
        ["_KW_OPEN_TOUCH_AREA"] = "成员"
    },


    ["ActivityIcon"] = {
        ["1001"] = "商城",
        ["1002"] = "活动",
        ["1003"] = "规则",
        ["1004"] = "公告",
        ["1005"] = "战绩",
        ["1006"] = "设置",
        ["1007"] = "更多",
        ["1008"] = "邀请",
        ["1010"] = "健康须知",
        ["1011"] = "防du",
        ["1012"] = "绑定手机",
        ["1015"] = "兑奖",
        ["1017"] = "分享",
        ["1018"] = "邮件",
        ["1019"] = "客服",
        ["1021"] = "背包",
        ["1022"] = "新闻",
        ["1023"] = "好友系统",
        ["1024"] = "特惠商城",
        ["1025"] = "公众号",
        ["1026"] = "更新提示",

        ["2005"] = "更新福利",
        ["2006"] = "回归礼包",
        ["2007"] = "砍价活动",
        ["2008"] = "每日抽奖",
        ["2010"] = "限时优惠",
        ["2011"] = "折扣礼包",
        ["2012"] = "国庆活动",
        ["2013"] = "分享活动",
        ["2014"] = "幸运转盘活动",
        ["2016"] = "topon话费",
        ["2019"] = "温茶引导创圈活动",
        ["2020"] = "新玩法活动C端",


        ["3000"] = "联运大厅",
        ["3001"] = "决战",
        ["3002"] = "千炮捕鱼",
        ["3003"] = "传奇",
        ["3004"] = "vip",
        ["3009"] = "祈福活动",
        ["3010"] = "51礼包",
        ["3011"] = "比赛场B端活动",
        ["3012"] = "捕鱼大奖赛",
        ["3013"] = "比赛场4转2",
        ["3014"] = "大天使之剑",
        ["3015"] = "羚萌直播",
        ["3017"] = "热血封神",
        ["3018"] = "斗罗大陆",
        ["3019"] = "街机三国",
        ["3020"] = "未知",
        ["3021"] = "人人捕鱼",
        ["30211"] = "人人捕鱼",
        ["30212"] = "人人捕鱼",
        ["3022"] = "谁是首富",
        ["3023"] = "推广活动",
        ["3024"] = "幸运任务",
        ["3025"] = "签到有礼",
        ["3026"] = "连炸斗地主",
        ["3027"] = "连炸斗地主中心ICON",
        ["3028"] = "金龙降临",
        ["3029"] = "维京传奇",
        ["3030"] = "卓越传说",
        ["3031"] = "远征将士",
        ["3032"] = "荣耀之怒",
        ["3033"] = "百战沙城",
        ["3034"] = "破产礼包",
        ["3035"] = "免赔礼包",
        ["3036"] = "未知",
        ["3037"] = "奥运活动",
        ["3038"] = "深渊契约",
        ["3039"] = "伏魔战歌",
        ["3040"] = "计分助手",
    }
}�