-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameExpression = {
		{ ConfID = 1, ExpressionName = "joker", ExpressionDirName = "joker", ExpressionJsonName = "joker", ExpressionIconPlistName = "expression_joker", ExpressionSelectIcon = { "baoqian", "dese", "diantou", "haixiu", "jingyan", "koubi", "leibeng", "leidao", "manzu", "qiza", "shangxin", "shihua", "shuqian", "sikao", "wunai", "xingfu", "xinlei", "yiwen", "yun", "zan" }, ExpressionAniName = { "joker_1", "joker_2", "joker_3", "joker_4", "joker_5", "joker_6", "joker_7", "joker_8", "joker_9", "joker_10", "joker_11", "joker_12", "joker_13", "joker_14", "joker_15", "joker_16", "joker_17", "joker_18", "joker_19", "joker_20" } 	},
		{ ConfID = 2, ExpressionName = "小短腿", ExpressionDirName = "xiaoduantuier", ExpressionJsonName = "xiaoduantuier", ExpressionIconPlistName = "expression_xiaoduantuier", ExpressionSelectIcon = { "tubiao_congbai", "tubiao_dengchi", "tubiao_deyi", "tubiao_duibuqi", "tubiao_fangpi", "tubiao_gandong", "tubiao_ganga", "tubiao_guisu", "tubiao_jingdai", "tubiao_qifei", "tubiao_sanren", "tubiao_shengqi", "tubiao_sualai", "tubiao_tiaoxin", "tubiao_wa", "tubiao_wodao", "tubiao_wokan", "tubiao_yihuo", "tubiao_yuema", "tubiao_yun" }, ExpressionAniName = { "xiaoduantuier_1", "xiaoduantuier_2", "xiaoduantuier_3", "xiaoduantuier_4", "xiaoduantuier_5", "xiaoduantuier_6", "xiaoduantuier_7", "xiaoduantuier_8", "xiaoduantuier_9", "xiaoduantuier_10", "xiaoduantuier_11", "xiaoduantuier_12", "xiaoduantuier_13", "xiaoduantuier_14", "xiaoduantuier_15", "xiaoduantuier_16", "xiaoduantuier_17", "xiaoduantuier_18", "xiaoduantuier_19", "xiaoduantuier_20" } 	}
	}

}


-- ConfID
tab.GameExpressionByConfID = {}
for _, rec in pairs(tab.GameExpression) do
	tab.GameExpressionByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tabC