NG.UI_TYPE = XH.UI_TYPE
NG.SCENE_TAG = XH.SCENE_TAG
NG.TIP_LAYER_TYPE = XH.TIP_LAYER_TYPE
NG.ZORDER = XH.ZORDER
NG.SRS_LINK_STATE = XH.SRS_LINK_STATE
NG.UIButton = XH.UIButton

NG.SCENE_TAG.NEWGOLD_LOBBY = 1001
NG.SCENE_TAG.NEWGOLD_GAME = 1002
