--[[
    --配置道具动画
    --1.本地会有一个_ske.json文件(骨骼控制数据)
	--2.https://www.json.cn/内可清晰查看到动画骨骼的数据
	--3.animation会记录每段动画片段的名称，根据animation内的name来配置
	--4.起始动画,飞行动画最终动画
    author:{xiezhihan}
    time:2021-12-21 20:45:33
]]
local strjson = [[
{
	"Tool": "github.com/davyxu/tabtoy",
	"Version": "3.0.1",
	"PropAniConf":[
		{ "ConfID": 1, "Index": 1, "SortIndex":6, "IsSelf": 2, "Visible": true, "Free": 0, "AniPicName": "throwprop_bingtong.png", "FileName": "hd_bingtong01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "ArriveMusicName": "hd_bingtong01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150283  },
		{ "ConfID": 2, "Index": 2, "SortIndex":7, "IsSelf": 2, "Visible": true, "Free": 0, "AniPicName": "throwprop_boom.png", "FileName": "dj_boom", "AppearAniName": "dj_boom_appear", "FlyAniName": "dj_boom_fly", "ArriveAniName": "dj_boom_arrive", "ArmatureName": "Armature", "FlyMusicName": "daoju_zhayao.mp3", "ArriveMusicName": "", "StartTime": "0.51", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150284 },
		{ "ConfID": 3, "Index": 3, "SortIndex":8, "IsSelf": 2, "Visible": true, "Free": 0, "GuideAniFile": "ios_jiqiang_xiao", "GuideAni": "newAnimation", "AniPicName": "throwprop_jiguanqiang.png", "FileName": "hd_jiguanqiang01", "EndFileName": "hd_jiguanqiang01_end_1", "AppearAniName": "animation", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "AppearMusicName": "hd_jiguanqiang01.mp3", "ArriveMusicName": "", "StartTime": "0.6", "FlyTime": "0.5", "StartCount": "1", "FlyCount": "30", "SpaceTime": "0.1", "EndCount": "1", "Rotation": "0", "RandPos": true, "WaitTime": "0", "FlyName": "throwprop_zidan.png" , "Propid": 150285 },
		{ "ConfID": 4, "Index": 4, "SortIndex":9, "IsSelf": 2, "Visible": true, "Flag": "10l", "Free": 0, "AniPicName": "throwprop_shoes.png", "FileName": "dj_shoes", "AppearAniName": "shoes_appear", "FlyAniName": "shoes_fly", "ArriveAniName": "shoes_arrive", "ArmatureName": "Armature", "FlyMusicName": "shoes_in.mp3", "ArriveMusicName": "shoes_stop.mp3", "StartTime": "0", "FlyTime": "0.25", "StartCount": "1", "FlyCount": "25", "SpaceTime": "0.1", "EndCount": "1", "RandPos": true, "WaitTime": "0", "FlyName": "throwprop_shoes.png", "FlyRotation": "270" , "Propid": 150286 },
		{ "ConfID": 5, "Index": 5, "SortIndex":10, "IsSelf": 2, "Visible": true, "Flag": "10l", "Free": 0, "AniPicName": "throwprop_jidan.png", "FileName": "hd_jidan01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "FlyEndMusicName": "hd_jidan01.mp3", "ArriveMusicName": "", "StartTime": "0", "StartCount": "1", "FlyCount": "15", "SpaceTime": "0.1", "EndCount": "15", "RandPos": true, "WaitTime": "0", "Propid": 150287  },
		{ "ConfID": 6, "Index": 6, "SortIndex":1, "IsSelf": 2, "Visible": true, "Free": 0, "AniPicName": "throwprop_dianzan.png", "FileName": "dianzan", "AppearAniName": "dianzan_appear", "FlyAniName": "dianzan_fly", "ArriveAniName": "dianzan_arrive", "ArmatureName": "Armature", "ArriveMusicName": "", "StartTime": "0.45", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150278 },
		{ "ConfID": 7, "Index": 7, "SortIndex":2, "IsSelf": 2, "Visible": true, "Free": 0, "AniPicName": "throwprop_ganbei.png", "FileName": "hd_ganbei01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "ArriveMusicName": "hd_ganbei01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150279  },
		{ "ConfID": 8, "Index": 8, "SortIndex":3, "IsSelf": 2, "Visible": true, "Free": 0, "GuideAniFile": "iso_woshou_xiao", "GuideAni": "newAnimation", "AniPicName": "throwprop_woshou.png", "FileName": "hd_woshou01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "ArriveMusicName": "hd_woshou01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150280 },
		{ "ConfID": 9, "Index": 9, "SortIndex":4, "IsSelf": 2, "Visible": true, "Free": 0, "GuideAniFile": "ios_daocha_xiao", "GuideAni": "newAnimation", "AniPicName": "throwprop_daocha.png", "FileName": "hd_daocha01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "ArriveMusicName": "hd_daocha01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150281 },
		{ "ConfID": 10, "Index": 10, "SortIndex":5, "IsSelf": 2, "Visible": true, "Free": 1, "GuideAniFile": "yd_meigui", "GuideAni": "newAnimation", "AniPicName": "throwprop_meigui.png", "AnimationName": "newAnimation", "FileName": "hd_meigui01", "FlyAniName": "fly", "ArriveAniName": "animation", "ArmatureName": "armatureName", "ArriveMusicName": "hd_meigui01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150282 },
		{ "ConfID": 11, "Index": 91, "SortIndex":11, "Scale": "2.5", "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "caishen.png", "FileName": "qf_caishen01", "ArriveAniName": "caishen", "ArmatureName": "armatureName", "ArriveMusicName": "qf_caishen01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150288  },
		{ "ConfID": 12, "Index": 92, "SortIndex":12, "Scale": "2.5", "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "xishou.png", "FileName": "dj_xishou", "ArriveAniName": "dj_xishou", "ArmatureName": "Armature", "ArriveMusicName": "water.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150289 },
		{ "ConfID": 13, "Index": 93, "SortIndex":13, "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "throwprop_zhaocaimao.png", "FileName": "Ios_zhaocaicat", "ArriveAniName": "newAnimation", "ArmatureName": "Armature", "ArriveMusicName": "", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150290  },
		{ "ConfID": 14, "Index": 94, "SortIndex":14, "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "throwprop_zhaocaishu.png", "FileName": "Ios_yqs", "ArriveAniName": "newAnimation", "ArmatureName": "Armature", "ArriveMusicName": "", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150291 },
		{ "ConfID": 15, "Index": 95, "SortIndex":15, "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "throwprop_sfzy.png", "FileName": "Ios_lucky", "ArriveAniName": "newAnimation", "ArmatureName": "Armature", "ArriveMusicName": "", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150292 },
		{ "ConfID": 16, "Index": 96, "SortIndex":16, "Scale": "2.5", "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "chuizhuozi.png", "FileName": "daoju_chuizhuozi", "ArriveAniName": "chuizhuozi1", "ArmatureName": "armatureName", "ArriveMusicName": "daoju_chuizhuozi.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3" , "Propid": 150294 },
		{ "ConfID": 17, "Index": 97, "SortIndex":17, "Scale": "2.5", "IsSelf": 0, "Visible": true, "Free": 0, "AniPicName": "dajidali.png", "FileName": "qf_dajidali01", "ArriveAniName": "dajidali", "ArmatureName": "armatureName", "ArriveMusicName": "qf_dajidali01.mp3", "StartTime": "0", "StartCount": "1", "FlyCount": "1", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150293  },
		{ "ConfID": 18, "Index": 11, "SortIndex":18, "IsSelf": 2, "Visible": true, "Free": 1, "GuideAniFile": "ios_gxfc_xiao", "GuideAni": "newAnimation","AniPicName": "ios_gxfc_caishen_tex.png", "FileName": "ios_gxfc_caishen", "AppearAniName": "" ,"FlyAniName": "stop", "ArriveAniName": "star", "ArmatureName": "Armature","ArriveMusicName": "gongxifacai.mp3","StartTime": "0","StartCount": "0", "FlyCount": "1", "FlyTime": "0.7", "SpaceTime": "0.1", "EndCount": "1", "EndTime": "1.0", "WaitTime": "0.3","Propid": 150692 },
		{ "ConfID": 19, "Index": 12, "SortIndex":19, "IsSelf": 2, "Visible": true, "Free": 1, "GuideAniFile": "ios_bianpao_xiao", "GuideAni": "newAnimation","AniPicName": "zjb_bianpao_tex.png", "FileName": "zjb_bianpao" ,"AppearAniName": "","FlyAniName": "stop", "ArriveAniName": "star", "ArmatureName": "Armature", "ArriveMusicName": "bianpao.mp3","StartTime": "0", "StartCount": "0", "FlyCount": "1", "FlyTime": "0.75", "SpaceTime": "0.1", "EndCount": "1", "RandPos": false, "WaitTime": "0.3", "Propid": 150693  },
		{ "ConfID": 20, "SortIndex":20, "Visible": false },
		{ "ConfID": 21, "SortIndex":21, "Visible": false },
		{ "ConfID": 22, "SortIndex":22, "Visible": false }
	]}
]]

return strjson �$  