-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "丽水关牌", order = 1, SpeakText = "别摸虱", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "丽水关牌", order = 2, SpeakText = "炸弹放起来当宝", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "丽水关牌", order = 3, SpeakText = "别慌", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "丽水关牌", order = 4, SpeakText = "全手炸弹", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "丽水关牌", order = 5, SpeakText = "看不到司令", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "丽水关牌", order = 6, SpeakText = "满手白愣", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "丽水关牌", order = 7, SpeakText = "花腔", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "丽水关牌", order = 8, SpeakText = "看我的", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 110, GameName = "丽水关牌", order = 9, SpeakText = "贼牌", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 111, GameName = "丽水关牌", order = 10, SpeakText = "财过霉", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 112, GameName = "丽水关牌", order = 11, SpeakText = "闭着眼睛乱炸", M_SpeakFileName = "M_Speak112.mp3", W_SpeakFileName = "W_Speak112.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 113, GameName = "丽水关牌", order = 12, SpeakText = "真爽", M_SpeakFileName = "M_Speak113.mp3", W_SpeakFileName = "W_Speak113.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 114, GameName = "丽水关牌", order = 13, SpeakText = "忒猪波", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 115, GameName = "丽水关牌", order = 14, SpeakText = "没事多打几盘", M_SpeakFileName = "M_Speak115.mp3", W_SpeakFileName = "W_Speak115.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 116, GameName = "丽水关牌", order = 15, SpeakText = "真有胚", M_SpeakFileName = "M_Speak116.mp3", W_SpeakFileName = "W_Speak116.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 117, GameName = "丽水关牌", order = 16, SpeakText = "给力", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 118, GameName = "丽水关牌", order = 17, SpeakText = "小心被偷鸡", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 119, GameName = "丽水关牌", order = 18, SpeakText = "公饼配面席", M_SpeakFileName = "M_Speak119.mp3", W_SpeakFileName = "W_Speak119.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 120, GameName = "丽水关牌", order = 19, SpeakText = "我就喜欢和你配", M_SpeakFileName = "M_Speak120.mp3", W_SpeakFileName = "W_Speak120.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab