-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7
local tab = {
    GameNewTypeConf = {
    }
}

-- GameID
tab.GameNewTypeConfByGameID = {}
for _, rec in pairs(tab.GameNewTypeConf) do
    tab.GameNewTypeConfByGameID[rec.GameID] = rec
end

tab.Enum = {}

return tab
