-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
    GameSpeakConfig = {
        {ConfID = 1001, index = 101, order = 1, SpeakText = "我等的假花儿都谢了！", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1},
        {ConfID = 1002, index = 102, order = 2, SpeakText = "我炸你个桃花朵朵开！", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1},
        {ConfID = 1003, index = 103, order = 3, SpeakText = "姑娘你真是条汉子！", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1},
        {ConfID = 1004, index = 104, order = 4, SpeakText = "搏一搏，单车变摩托", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1},
        {ConfID = 1005, index = 105, order = 5, SpeakText = "炸的好！", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1},
        {ConfID = 1006, index = 106, order = 6, SpeakText = "就这就这？", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1}
    }
}

-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
    tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {}

return tab
F