local GameDefine = CF.gameClass("GameDefine", "game.DoubleKou.BaseDoubleKou.Define.GameDefine")
GameDefine.GAME_STEP = {
    GAME_STEP_NONE = 0,
    GAME_STEP_GAME_START = 1,
    GAME_STEP_INTERVENE_OPEN_CARD = 2,
    GAME_STEP_INTERVENE_FRIEND = 3,
    GAME_STEP_INTERVENE_HAND_CARD = 4,
    GAME_STEP_OPEN_CARD = 5,
    GAME_STEP_TAKE_CARD = 6,
    GAME_STEP_SWAP_SEAT = 7,
    GAME_STEP_SEND_FRIEND_CARD = 8,
    GAME_STEP_PLAY_CARD = 9,
    GAME_STEP_WIN_LOST = 10,
    GAME_STEP_ESCAPE_WIN_LOST = 11,
    GAME_STEP_MAKE_CARD = 12,
    GAME_STEP_INC_DOUBLING = 13,
}
GameDefine.GAME_STEP.GAME_STEP_ADD_MULTIPLE = GameDefine.GAME_STEP.GAME_STEP_INC_DOUBLING --千变叫GAME_STEP_INC_DOUBLING，加倍框架用的是GAME_STEP_ADD_MULTIPLE
return GameDefine