local CardFrameworkDefine = {}

--游戏步骤

CardFrameworkDefine.ENUM_GAME_STEP = {
    KW_GAME_STEP_NONE = 0,
    KW_GAME_STEP_GAME_START = 1,
    KW_GAME_STEP_INTERVENE_OPEN_CARD = 2,
    KW_GAME_STEP_INTERVENE_FRIEND = 3,
    KW_GAME_STEP_INTERVENE_HAND_CARD = 4,
    KW_GAME_STEP_OPEN_CARD = 5,
    KW_GAME_STEP_TAKE_CARD = 6,
    KW_GAME_STEP_SWAP_SEAT = 7,
    KW_GAME_STEP_SEND_FRIEND_CARD = 8,
    KW_GAME_STEP_PLAY_CARD = 9,
    KW_GAME_STEP_WIN_LOST = 10,
    KW_GAME_STEP_ESCAPE_WIN_LOST = 11,
    KW_GAME_STEP_MAKE_CARD = 12,
}


return CardFrameworkDefineP