local GameSceneDefine = class("GameSceneDefine")

GameSceneDefine.KW_GAMECOMMON_PATH = "GameCommon"
GameSceneDefine.KW_GAME_PATH = "DoubleBuckle"

-- UI控件关键字定义
GameSceneDefine.KW_ROOT_LAYER = "KW_ROOT_LAYER"
GameSceneDefine.KW_UI_WIFI_STATE = "KW_UI_WIFI_STATE"
GameSceneDefine.KW_UI_POWER_STATE = "KW_UI_POWER_STATE"
GameSceneDefine.KW_UI_GAME_BG = "KW_UI_GAME_BG"
GameSceneDefine.KW_UI_MENU = "KW_UI_MENU"
GameSceneDefine.KW_UI_MENU_OUT_POS = "KW_UI_MENU_OUT_POS"
GameSceneDefine.KW_UI_MENU_IN_POS = "KW_UI_MENU_IN_POS"
GameSceneDefine.KW_UI_ROOM_INFO = "KW_UI_ROOM_INFO"
GameSceneDefine.KW_UI_BOX_ROOM_INFO_BG = "KW_UI_BOX_ROOM_INFO_BG"
GameSceneDefine.KW_UI_BOX_ROOM_MENU = "KW_UI_BOX_ROOM_MENU"
GameSceneDefine.KW_UI_BOX_ROOM_INFO = "KW_UI_BOX_ROOM_INFO"
GameSceneDefine.KW_UI_HEAD_HOST = "KW_UI_HEAD_HOST"
GameSceneDefine.KW_UI_PLAYER_HEAD_BG = "KW_UI_PLAYER_HEAD_BG"
GameSceneDefine.KW_UI_INFO_PIC = "KW_UI_INFO_PIC"
GameSceneDefine.KW_UI_INFO_PIC_AREA = "KW_UI_INFO_PIC_AREA"
GameSceneDefine.KW_UI_HEAD_PIC = "KW_UI_PLAYER_HEAD"
GameSceneDefine.KW_UI_HEAD_PIC_AREA = "KW_UI_PLAYER_HEAD_AREA"
GameSceneDefine.KW_UI_INFO_IP = "KW_UI_INFO_IP"
GameSceneDefine.KW_UI_INFO_PANEL = "KW_UI_PLAYER_INFO_BG"
GameSceneDefine.KW_UI_PLAYER_TIME = "KW_UI_PLAYER_TIME"
GameSceneDefine.KW_UI_READY = "KW_UI_READY" 
GameSceneDefine.KW_UI_INFO_LEVEL = "KW_UI_INFO_LEVEL"
GameSceneDefine.KW_UI_PLAYER_CARD_LEFT = "KW_UI_PLAYER_CARD_LEFT"
GameSceneDefine.KW_UI_ROOM_RULE = "KW_UI_ROOM_RULE"
GameSceneDefine.KW_UI_GAME_END_RANK = "KW_UI_GAME_END_RANK"
GameSceneDefine.KW_UI_SPEAK_BG = "KW_UI_SPEAK_BG"
GameSceneDefine.KW_UI_PASS = "KW_UI_PASS"
GameSceneDefine.KW_UI_NOCARDBIG = "KW_UI_NOCARDBIG"
GameSceneDefine.KW_POS_PLAYER_HEAD_EFFECT = "KW_POS_PLAYER_HEAD_EFFECT"
GameSceneDefine.KW_PARTICLE_PLAYER_HEAD_EFFECT_PATH = "DoubleBuckle/DoubleBuckle/Json/newtears_headlight/headlight_particle_1.plist"
GameSceneDefine.KW_PARTICLE_SELF_HEAD_EFFECT_PATH = GameSceneDefine.KW_GAMECOMMON_PATH.."/GameCommon/Json/touxiangkuang/zadan_1.plist"
GameSceneDefine.KW_UI_WIRE_BREAK_ANIMATION = "KW_UI_WIRE_BREAK_ANIMATION"
GameSceneDefine.KW_POS_WIRE_BREAK = "KW_POS_WIRE_BREAK"
GameSceneDefine.KW_UI_GAME_SOUND_PROGRESS = "KW_UI_GAME_SOUND_PROGRESS"
GameSceneDefine.KW_TEXT_GAME_SOUND_PROGRESS = "KW_TEXT_GAME_SOUND_PROGRESS"
GameSceneDefine.KW_UI_GAME_SOUNDS_DOWNLOAD = "KW_UI_GAME_SOUNDS_DOWNLOAD"
GameSceneDefine.KW_UI_CARD_LAYER = "KW_UI_CARD_LAYER"
GameSceneDefine.KW_UI_GAMEAREA_HAND_CARD = "KW_UI_GAMEAREA_HAND_CARD"
GameSceneDefine.KW_ADAPT_CARDS_ = "KW_ADAPT_CARDS_"

GameSceneDefine.KW_HEAD_EFFECT_PATH = "Lobby32/Json/PopLayer/joker_activity/ldj_touxiang/"
GameSceneDefine.KW_HEAD_EFFECT_JSON = "ldj_touxiang"
GameSceneDefine.KW_HEAD_EFFECT_ANI = "Animation1"

--match
GameSceneDefine.KW_UI_MATCH_ROOM_INFO = "KW_UI_MATCH_ROOM_INFO"
GameSceneDefine.KW_TEXT_MATCH_ROOM_HINT = "KW_TEXT_MATCH_ROOM_HINT"
GameSceneDefine.KW_TEXT_RANK = "KW_TEXT_RANK"
GameSceneDefine.KW_UI_MATCH_INFO_RANK ="KW_UI_MATCH_INFO_RANK"
GameSceneDefine.KW_UI_MATCH_INFO_PANEL ="KW_UI_MATCH_INFO_PANEL"
GameSceneDefine.KW_TEXT_MATCH_ROOM_HINT_BG ="KW_TEXT_MATCH_ROOM_HINT_BG"

-- 按钮关键字定义
GameSceneDefine.KW_BTN_MENU = "KW_BTN_MENU"
GameSceneDefine.KW_BTN_BACK = "KW_BTN_BACK"
GameSceneDefine.KW_BTN_DISSOLVE = "KW_BTN_DISSOLVE"
GameSceneDefine.KW_BTN_SETTING = "KW_BTN_SETTING"
GameSceneDefine.KW_BTN_BOT = "KW_BTN_BOT"
GameSceneDefine.KW_BTN_CHANGE_TABLE = "KW_BTN_CHANGE_TABLE"
GameSceneDefine.KW_BTN_EXIT = "KW_BTN_EXIT"
GameSceneDefine.KW_BTN_TALK = "KW_BTN_TALK"
GameSceneDefine.KW_BTN_START = "KW_BTN_START"
GameSceneDefine.KW_BTN_INVITE = "KW_BTN_INVITE"
GameSceneDefine.KW_BTN_ROBOT = "KW_BTN_ROBOT"
GameSceneDefine.KW_BTN_MIKE = "KW_BTN_MIKE"
GameSceneDefine.KW_BTN_REPLAY = "KW_BTN_REPLAY"
GameSceneDefine.KW_BTN_PASS = "KW_BTN_PASS"
GameSceneDefine.KW_BTN_TELL_ME = "KW_BTN_TELL_ME"
GameSceneDefine.KW_BTN_OUT_CARD = "KW_BTN_OUT_CARD"
GameSceneDefine.KW_BTN_CHAO_DI = "KW_BTN_CHAO_DI"
GameSceneDefine.KW_BTN_SORT = "KW_BTN_SORT"
GameSceneDefine.KW_BTN_PLAY_BACK = "KW_BTN_PLAY_BACK"
GameSceneDefine.KW_BTN_PAUSE_BACK = "KW_BTN_PAUSE_BACK"
GameSceneDefine.KW_BTN_ADD_SPEED = "KW_BTN_ADD_SPEED"
GameSceneDefine.KW_BTN_MINUS_SPEED = "KW_BTN_MINUS_SPEED"
GameSceneDefine.KW_BTN_PROP = "KW_BTN_PROP"
GameSceneDefine.KW_BTN_SWAP = "KW_BTN_SWAP"
GameSceneDefine.KW_BTN_COPY_ROOMNO = "KW_BTN_COPY_ROOMNO"

GameSceneDefine.KW_ROOM_RULE_BTN_SHOW = "KW_ROOM_RULE_BTN_SHOW"
GameSceneDefine.KW_ROOM_RULE_BTN_RETRACT = "KW_ROOM_RULE_BTN_RETRACT"


GameSceneDefine.KW_PANEL_HEAD_ = "KW_PANEL_HEAD_"
GameSceneDefine.KW_PANEL_HEAD_TIPS_ = "KW_PANEL_HEAD_TIPS_"
GameSceneDefine.KW_PANEL_READY = "KW_PANEL_READY_"
GameSceneDefine.KW_PANEL_ROBOT = "KW_PANEL_ROBOT"
GameSceneDefine.KW_PANEL_ROOM_RULE = "KW_PANEL_ROOM_RULE"
GameSceneDefine.KW_PANEL_BTNS_READY = "KW_PANEL_BTNS_READY"
GameSceneDefine.KW_PANEL_BTNS_GAME = "KW_PANEL_BTNS_GAME"
GameSceneDefine.KW_PANEL_PLAYBACK_TIP = "KW_PANEL_PLAYBACK_TIP"
GameSceneDefine.KW_PANEL_PLAYBACK_SET = "KW_PANEL_PLAYBACK_SET"
GameSceneDefine.KW_PANEL_FEATURES = "KW_PANEL_FEATURES"
GameSceneDefine.KW_PANEL_CARD_LEFT = "KW_PANEL_CARD_LEFT"

GameSceneDefine.KW_PANEL_BTNS_GAME_NORMAL = "KW_PANEL_BTNS_GAME_NORMAL"

GameSceneDefine.KW_TEXT_HEAD_NICKNAME = "KW_TEXT_PLAYER_NAME"
GameSceneDefine.KW_TEXT_SCORE = "KW_TEXT_PLAYER_SCORE"
GameSceneDefine.KW_TEXT_NUMBER_ID = "KW_TEXT_NUMBER_ID_NUM"
GameSceneDefine.KW_TEXT_MONEY_NUM = "KW_TEXT_MONEY_NUM"
GameSceneDefine.KW_TEXT_GAME_NUM = "KW_TEXT_GAME_COUNT_NUM"
GameSceneDefine.KW_TEXT_WIN_RATE = "KW_TEXT_WIN_RATE_NUM"
GameSceneDefine.KW_TEXT_ESCAPE_RATE = "KW_TEXT_ESCAPE_RATE_NUM"
GameSceneDefine.KW_TEXT_IP = "KW_TEXT_IP"
GameSceneDefine.KW_TEXT_SYS_TIME = "KW_TEXT_SYS_TIME"
GameSceneDefine.KW_TEXT_SYS_TIME_POINT = "KW_TEXT_SYS_TIME_POINT"
GameSceneDefine.KW_TEXT_ROOM_ID = "KW_TEXT_ROOM_ID"
GameSceneDefine.KW_TEXT_INNING = "KW_TEXT_INNING"
GameSceneDefine.KW_UI_PLAYER_TIME = "KW_UI_PLAYER_TIME"
GameSceneDefine.KW_TEXT_PLAYER_CONTRIBUTION = "KW_TEXT_PLAYER_CONTRIBUTION" 
GameSceneDefine.KW_TEXT_CONTRIBUTION = "KW_TEXT_CONTRIBUTION"
GameSceneDefine.KW_TEXT_LEVEL = "KW_TEXT_LEVEL"
GameSceneDefine.KW_TEXT_PLAYER_TIME = "KW_TEXT_PLAYER_TIME"
GameSceneDefine.KW_TEXT_PLAYER_CARD_LEFT_NUM = "KW_TEXT_PLAYER_CARD_LEFT_NUM"
GameSceneDefine.KW_TEXT_WIN_MUT = "KW_TEXT_WIN_MUT"
GameSceneDefine.KW_TEXT_LOST_MUT = "KW_TEXT_LOST_MUT"
GameSceneDefine.KW_TEXT_BASE_SCORE= "KW_TEXT_BASE_SCORE"
GameSceneDefine.KW_TEXT_ROOM_RULE = "KW_TEXT_ROOM_RULE"
GameSceneDefine.KW_TEXT_WIN_MUT_TMP = "KW_TEXT_WIN_MUT_TMP"
GameSceneDefine.KW_TEXT_SPEAK = "KW_TEXT_SPEAK"
GameSceneDefine.KW_TEXT_SPEED = "KW_TEXT_SPEED"
GameSceneDefine.KW_TEXT_AMAP_POS_FIRST = "KW_TEXT_AMAP_POS_FIRST"--高德 地图
GameSceneDefine.KW_TEXT_AMAP_POS_SECOND = "KW_TEXT_AMAP_POS_SECOND"
GameSceneDefine.KW_AMAP_ADDRESS = "KW_AMAP_ADDRESS"
-- 图片资源关键字定义
GameSceneDefine.KW_UI_PLAYER_HEAD_PNG = "game_sex_img_%d.png"
GameSceneDefine.KW_UI_INFO_SEX_BIG_IMG_ = "game_sex_big_img_%d.png"
GameSceneDefine.KW_UI_WIND_PNG = "game_logo_%d.png"


GameSceneDefine.KW_TIP_NO_TRUST = "KW_TIP_NO_TRUST"
GameSceneDefine.KW_TIP_NO_CHANGE_TABLE = "KW_TIP_NO_CHANGE_TABLE"


GameSceneDefine.KW_POS_ROBOT_ANI = "KW_POS_ROBOT_ANI"
GameSceneDefine.KW_POS_MIKE_ANI = "KW_POS_MIKE_ANI"
GameSceneDefine.KW_POS_TIME_PARTICLE_ANI = "KW_POS_TIME_PARTICLE_ANI"
GameSceneDefine.KW_PLAY_RECORD_POS = "KW_POS_PLAY_RECORD"

GameSceneDefine.ROBOT_ARMATURE = "ROBOT_ARMATURE"


GameSceneDefine.KW_PATH_RESOUCE =   "DoubleBuckle"
GameSceneDefine.KW_PATH_RESOUCE_JASON =   GameSceneDefine.KW_PATH_RESOUCE .. "/Json"
GameSceneDefine.KW_PATH_RESOUCE_IMAGE =   GameSceneDefine.KW_PATH_RESOUCE .. "/Image"
GameSceneDefine.KW_PATH_RESOUCE_CSB =   GameSceneDefine.KW_PATH_RESOUCE .. "/CSB"
GameSceneDefine.KW_PATH_RESOUCE_FONT =   GameSceneDefine.KW_PATH_RESOUCE .. "/Fonts"

GameSceneDefine.KW_ANI_CARD_PILE = "KW_ANI_CARD_PILE"


GameSceneDefine.CardAniType =
    {
        None = 0,
        FirstDealHandCard = 1,
    }


return GameSceneDefine 