---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaojiabao.
--- DateTime: 2022/4/26 11:21 上午
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaojiabao.
--- DateTime: 2021/4/13 4:37 下午
---
------------------------
-- cocos2dx-lua
------------------------


local m = {}

--- Java回调参数  全局函数方法
--- @param msg java回调过来的数据  json支付串，含有code和msg
RepluginSDKCallBack = function(msg)
    m.rePluginSdkCallBack(msg)
    -- local luaJson = require("luaJson")
    -- local code = tonumber(luaJson.json2lua(msg).code)
    -- local msg = luaJson.json2lua(msg).msg
    -- if code == 6 then
    --     print(msg)
    -- end
end

if device.platform == "android" then
--- 获取Java类名
m.JavaClassName = "com.ymnsdk.replugin.RepluginSdkJavaBridging"
m.luaj = require("cocos.cocos2d.luaj")
m.rePluginSdkCallBack = nil
end

m.addRepluginSDKListener = function(callBack)
    m.rePluginSdkCallBack = callBack
end


--- 获取插件列表
--- @function getPluginsInfo
--- @param app_id  应用id String 必填
--- @param hostAppInfo 宿主应用信息 json字符串:含有package_id/channel_id/user_id/user_type字段  非必填
m.getPluginsInfo = function(app_id, hostAppInfo)
    local JavaMethodName = "getPluginsInfo"
    local args = {app_id, hostAppInfo}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 查询某个插件状态
--- @function queryPluginStatus
--- @param plugin_id 插件id
m.queryPluginStatus = function(plugin_id)
    local JavaMethodName = "queryPluginStatus"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 预加载某个插件
--- @function preloadPlugin
--- @param plugin_id 插件id
m.preloadPlugin = function(plugin_id)
    local JavaMethodName = "preloadPlugin"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 判断某个插件是否安装
--- @function isInstallPlugin
--- @param plugin_id 插件id
m.isInstallPlugin = function(plugin_id)
    local JavaMethodName = "isInstallPlugin"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 安装某个插件（方式一）
--- @function installPlugin
--- @param plugin_id 插件id
m.installPlugin = function(plugin_id)
    local JavaMethodName = "installPlugin"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 安装某个插件（方式二）
--- @function installPlugin
--- @param plugin_id 插件id
--- @param noNetTimeout 断网超时时间，单位s，不传默认为5s
--- @param weakNetTimeout 弱网超时时间，单位s，不传默认为15s
m.installPlugin = function(plugin_id, noNetTimeout, weakNetTimeout)
    local JavaMethodName = "installPlugin"
    local args = {plugin_id, noNetTimeout, weakNetTimeout}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 启动某个插件
--- @function startApk
--- @param plugin_id 插件id
--- @param loginJsonStr  登录信息  json字符串
m.startApk = function(plugin_id, loginJsonStr)
    local JavaMethodName = "startApk"
    local args = {plugin_id, loginJsonStr}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 卸载某个插件
--- @function unInstallPlugin
--- @param plugin_id 插件id
m.unInstallPlugin = function(plugin_id)
    local JavaMethodName = "unInstallPlugin"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)

end

--- 清除插件下载缓存
--- @function clearDownloadCache
--- @param plugin_id 插件id
m.clearDownloadCache = function(plugin_id)
    local JavaMethodName = "clearDownloadCache"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)

end

--- 打开插件
--- @function openPlugin
--- @param plugin_id 插件id
--- @param loginJsonStr  登录信息，一定要含有 hostPackageName:宿主包名 / hostActivity:宿主主Activity 全路径    类型：json字符串
m.openPlugin = function(plugin_id, loginJsonStr)
    local JavaMethodName = "openPlugin"
    local args = {plugin_id, loginJsonStr}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

--- 允许启动插件
--- @function allowStartPlugin
--- @param plugin_id 插件id
--- @param loginJsonStr  登录信息，一定要含有 hostPackageName:宿主包名 / hostActivity:宿主主Activity 全路径    类型：json字符串
--- @param isAllow  是否允许打开，String,传“1”为允许，否则为不允许
m.allowStartPlugin = function(plugin_id, loginJsonStr, isAllow)
    local JavaMethodName = "allowStartPlugin"
    local isAllowStr = isAllow and "1" or "0"
    local args = {plugin_id, loginJsonStr, isAllowStr}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
end

m.postToSepperllita = function(jsonStr)
    local JavaMethodName = "postToSepperllita"
    local args = {jsonStr}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName,args,sigs)
    print("postToSepperllita:"..jsonStr)
end

--- 用户同意隐私政策
--- @function allowUserPrivacy
m.allowUserPrivacy = function()
    local JavaMethodName = "allowUserPrivacy"
    m.luaj.callStaticMethod(m.JavaClassName,JavaMethodName)

end

m.deleteDownloadCacheAndIgnoreSilentDownload = function(plugin_id)
    if device.platform ~= "android" then
        return
    end
    if cc.Application:getInstance():getVersion() < "1.5.9" then
        return
    end
    local JavaMethodName = "deleteDownloadCacheAndIgnoreSilentDownload"
    local args = {plugin_id}
    local sigs = "(Ljava/lang/String;)V"
    m.luaj.callStaticMethod("com/ymnsdk/replugin/RePluginSdk",JavaMethodName,args,sigs)
end

-- 插件包调用宿主包方法
m.invokeFuncNameandParameters = function(method, param)
    if device.platform ~= "android" then
        return
    end
    if type(param) == "table" then
        param = json.encode(param)
    end
    local JavaMethodName = "invokeFuncNameandParameters"
    local args = {method, param}
    local sigs = "(Ljava/lang/String;Ljava/lang/String;)V"
    print("yuhang " .. method .. "_" .. param)
    m.luaj.callStaticMethod("com/bianfeng/pluginlibrary/RePluginSdk",JavaMethodName,args,sigs)
end

return m

--------------
--- 方法调用示例
---------------

-- local s = require("RePluginSdk")
-- - 设置监听
-- s.addRepluginSDKListener(function(msg)
--    print(msg)
-- end)
--- 获取插件列表
-- s.getPluginsInfo("123","")



