local GameDefine = CF.gameClass("GameDefine", "game.GameBase.Define.GameDefine")

GameDefine.GAME_STEP = {
    GAME_STEP_NONE = 0,
    GAME_STEP_GAME_START = 1,
    GAME_STEP_ADD_MULTIPLE = 2,
    GAME_STEP_ADD_MULTIPLE_END = 3,
    GAME_STEP_INTERVENE_OPEN_CARD = 4,
    GAME_STEP_INTERVENE_FRIEND = 5,
    GAME_STEP_INTERVENE_HAND_CARD = 6,
    GAME_STEP_OPEN_CARD = 7,
    GAME_STEP_TAKE_CARD = 8,
    GAME_STEP_SWAP_SEAT = 9,
    GAME_STEP_SEND_FRIEND_CARD = 10,
    GAME_STEP_PLAY_CARD = 11,
    GAME_STEP_WIN_LOST = 12,
    GAME_STEP_ESCAPE_WIN_LOST = 13,
    GAME_STEP_MAKE_CARD = 14,
}

GameDefine.GAME_WIN_ORDER = {
    FIRSET = 1,
    SECOND = 2,
    THREE = 3
}

GameDefine.ENUM_WINLOST_ENDTYPE = {
    KW_ENDTYPE_TAOPAO = 1,
    KW_ENDTYPE_CHAODI = 2,
    KW_ENDTYPE_PINGKOU = 3,
    KW_ENDTYPE_DANKOU = 4,
    KW_ENDTYPE_SHUANGKOU = 5,
}

GameDefine.GAME_BTNS_TAG_FLAG = {
    BTN_OUTCARD = 1,
    BTN_NOT_OUTCARD = 2,
    BTN_TELL_ME = 3,
}

return GameDefine