local HTTP_ID_START = 10000
HttpDefine = {
    HTTP_ID_RED_PACKET = HTTP_ID_START + 1,
    HTTP_ID_REQUEST_CARNIVAL_GETWROD = HTTP_ID_START + 2,
    HTTP_ID_REQUEST_REDBOX = HTTP_ID_START + 3,
    HTTP_ID_REQUEST_TREASURE = HTTP_ID_START + 4,
    }
return HttpDefine