-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "玉环打通", order = 1, SpeakText = "快点吧，等的花都谢了", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "玉环打通", order = 2, SpeakText = "急什么，让我想想怎么打", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "玉环打通", order = 3, SpeakText = "和你合作真是太愉快了", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "玉环打通", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "玉环打通", order = 5, SpeakText = "好牌！好牌！", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "玉环打通", order = 6, SpeakText = "别慌，看我的", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "玉环打通", order = 7, SpeakText = "炸弹带回家啊？", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "玉环打通", order = 8, SpeakText = "不要急，一手手来", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "玉环打通", order = 9, SpeakText = "对家不给力啊", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "玉环打通", order = 10, SpeakText = "又断网了，网络怎么这么差", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "玉环打通", order = 11, SpeakText = "各位对不住了，有事先走一步", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab