-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "上虞花麻将", order = 1, SpeakText = "早就可以胡了，就等财神了", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "上虞花麻将", order = 2, SpeakText = "不好意思啊，有点事，稍等一下", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "上虞花麻将", order = 3, SpeakText = "对家风头真好啊", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "上虞花麻将", order = 4, SpeakText = "杠开摸了个财神那，那是要飞鸟拉", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "上虞花麻将", order = 5, SpeakText = "听牌了听牌了", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "上虞花麻将", order = 6, SpeakText = "今天风头怎么那么好啊", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "上虞花麻将", order = 7, SpeakText = "快点快点，那么慢的", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "上虞花麻将", order = 8, SpeakText = "呦，你马上三摊了宁", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "上虞花麻将", order = 9, SpeakText = "好吃不吃吃三摊 心烦啊", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "上虞花麻将", order = 10, SpeakText = "风头那么差的啊，一只好牌都没有", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "上虞花麻将", order = 11, SpeakText = "这盘总要让我飞出来了呀", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "上虞花麻将", order = 12, SpeakText = "小心拦杠胡啊，太大了呀", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 13, GameName = "上虞花麻将", order = 13, SpeakText = "牌打得那么好，联系方式留一个", M_SpeakFileName = "M_Speak13.mp3", W_SpeakFileName = "W_Speak13.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 14, GameName = "上虞花麻将", order = 14, SpeakText = "有点事情去，我先走一步", M_SpeakFileName = "M_Speak14.mp3", W_SpeakFileName = "W_Speak14.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 15, GameName = "上虞花麻将", order = 15, SpeakText = "不要催不要催，慢慢打呀", M_SpeakFileName = "M_Speak15.mp3", W_SpeakFileName = "W_Speak15.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 16, GameName = "上虞花麻将", order = 16, SpeakText = "那么烦得嘞，打什么摸什么啊，烦心", M_SpeakFileName = "M_Speak16.mp3", W_SpeakFileName = "W_Speak16.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 17, GameName = "上虞花麻将", order = 17, SpeakText = "那么好的牌，胡不掉啊", M_SpeakFileName = "M_Speak17.mp3", W_SpeakFileName = "W_Speak17.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 18, GameName = "上虞花麻将", order = 18, SpeakText = "这副牌好了啊 包胡啊", M_SpeakFileName = "M_Speak18.mp3", W_SpeakFileName = "W_Speak18.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 19, GameName = "上虞花麻将", order = 19, SpeakText = "你这个人牌打得那么好嘞，套路深啊", M_SpeakFileName = "M_Speak19.mp3", W_SpeakFileName = "W_Speak19.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab