-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	TeaHousePower = {
		{ PowerLevel = "Owner", CreateTeahouse = "AllowAll", DismissTeaHouse = "AllowAll", PauseTeaHouse = "AllowAll", ModifyTeahouse = "AllowAll", ModifyPlayMode = "AllowAll", ModifyAdmin = "AllowAll", ModifyMember = "AllowAll", ModifyBlack = "Forbid", KickMember = "AllowAll", RechargeTeaHouse = "AllowAll", AddCardTeaHouse = "AllowAll", ModifyMemberCost = "AllowAll", ModifyBill = "AllowAll", FinishBill = "AllowAll", CreateTable = "AllowAll", JoinTable = "AllowAll", DismissTable = "AllowAll", DismissGameTable = "Forbid", QuitTeaHouse = "Forbid", QueryRank = "AllowAll", AgentApplication = "Forbid", ModifyVisible = "AllowAll", AutoJoinTable = "AllowAll", ModifyRemark = "Forbid", ModifyMutex = "AllowAll", ModifyRankSetting = "AllowAll", ModifyInventory = "AllowAll" 	},
		{ PowerLevel = "Admin", CreateTeahouse = "Forbid", DismissTeaHouse = "Forbid", PauseTeaHouse = "Forbid", ModifyTeahouse = "Forbid", ModifyPlayMode = "Forbid", ModifyAdmin = "Forbid", ModifyMember = "AllowAll", ModifyBlack = "Forbid", KickMember = "AllowLow", RechargeTeaHouse = "AllowAll", AddCardTeaHouse = "AllowAll", ModifyMemberCost = "AllowAll", ModifyBill = "AllowAll", FinishBill = "AllowAll", CreateTable = "AllowAll", JoinTable = "AllowAll", DismissTable = "AllowAll", DismissGameTable = "Forbid", QuitTeaHouse = "AllowAll", QueryRank = "AllowAll", AgentApplication = "Forbid", ModifyVisible = "Forbid", AutoJoinTable = "AllowAll", ModifyRemark = "Forbid", ModifyMutex = "Forbid", ModifyRankSetting = "AllowAll", ModifyInventory = "Forbid" 	},
		{ PowerLevel = "Member", CreateTeahouse = "Forbid", DismissTeaHouse = "Forbid", PauseTeaHouse = "Forbid", ModifyTeahouse = "Forbid", ModifyPlayMode = "Forbid", ModifyAdmin = "Forbid", ModifyMember = "Forbid", ModifyBlack = "Forbid", KickMember = "Forbid", RechargeTeaHouse = "Forbid", AddCardTeaHouse = "Forbid", ModifyMemberCost = "Forbid", ModifyBill = "Forbid", FinishBill = "Forbid", CreateTable = "AllowAll", JoinTable = "AllowAll", DismissTable = "Forbid", DismissGameTable = "Forbid", QuitTeaHouse = "AllowAll", QueryRank = "AllowAll", AgentApplication = "AllowAll", ModifyVisible = "Forbid", AutoJoinTable = "AllowAll", ModifyRemark = "Forbid", ModifyMutex = "Forbid",ModifyRankSetting = "Forbid", ModifyInventory = "Forbid" 	},
		{ PowerLevel = "Black", CreateTeahouse = "Forbid", DismissTeaHouse = "Forbid", PauseTeaHouse = "Forbid", ModifyTeahouse = "Forbid", ModifyPlayMode = "Forbid", ModifyAdmin = "Forbid", ModifyMember = "Forbid", ModifyBlack = "Forbid", KickMember = "Forbid", RechargeTeaHouse = "Forbid", AddCardTeaHouse = "Forbid", ModifyMemberCost = "Forbid", ModifyBill = "Forbid", FinishBill = "Forbid", CreateTable = "Forbid", JoinTable = "Forbid", DismissTable = "Forbid", DismissGameTable = "Forbid", QuitTeaHouse = "AllowAll", QueryRank = "Forbid", AgentApplication = "Forbid", ModifyVisible = "Forbid", AutoJoinTable = "Forbid", ModifyRemark = "Forbid", ModifyMutex = "Forbid" ,ModifyRankSetting = "Forbid", ModifyInventory = "Forbid" 	}
	}

}


-- PowerLevel
tab.TeaHousePowerByPowerLevel = {}
for _, rec in pairs(tab.TeaHousePower) do
	tab.TeaHousePowerByPowerLevel[rec.PowerLevel] = rec
end

tab.Enum = {
	PowerLevel = {
		Owner = 0,
		Admin = 1,
		Member = 2,
		Black = 3,
	},
	PowerValue = {
		AllowAll = 0,
		AllowSame = 1,
		AllowLow = 2,
		Forbid = 3,
	},
}

return tab�