local JuBaoPenConfig = CF.gameClass("JuBaoPenConfig")

JuBaoPenConfig.ActDes = "1. 宝物获取及有效期：抽取成功后获得相应的宝物，每个宝物有效期为3小时，自获得时开始计算。如果在有效期内再次抽到相同的宝物，那么宝物升1级，运势叠加，并且重置有效期至3小时。满级为10级，达到满级时抽中相同宝物，不再升级，有效期将会重置为3小时。\n\n2. 宝物：一共16个宝物，分为4个品质（普通、精品、极品、绝品），品质越高，获得的运势值越高\n\n3.运势加成：每个宝物都带有纯表现性质的运势加成，虽无实际游戏数值影响，但可为您的游戏历程增添别样乐趣与心理助力。\n\n4.抽取概率说明：所有宝物概率均摊，约为6.25%"

local Quality = {
    Normal = 1,
    Good = 2,
    Super = 3,
    Special = 4,
}
JuBaoPenConfig.Quality = Quality

JuBaoPenConfig.QualityName = {
    [Quality.Normal] = "普通",
    [Quality.Good] = "精品",
    [Quality.Super] = "极品",
    [Quality.Special] = "绝品",
}

JuBaoPenConfig.Tag = {
    New = 1,
    Upgrade = 2,
    Max = 3
}

JuBaoPenConfig.ITEM_CONFIG = {
    {
        id = 10001,
        index = 1,
        name = "手串",
        quality = Quality.Normal,
        ys = 60,
        animationName = "lv",
        title = "凝珠成串，清雅致韵",
        titleColor = cc.c3b(0x7C,0xE2,0x9E),
        description = "珍珠镶嵌金纹，缀绿玉珠，配黑珠白珠吊坠，精致典雅，似能汇聚财气、带来福气满满。",
    },
    {
        id = 10002,
        index = 2,
        name = "宝瓶",
        quality = Quality.Normal,
        ys = 60,
        animationName = "lv",
        title = "金翠交织，玉质莹润",
        titleColor = cc.c3b(0x7C,0xE2,0x9E),
        description = "瓶身呈渐变翠绿，饰有金色卷草纹，瓶口、瓶底镶金，通透雅致，似能收纳财气，为周遭带来吉祥福气。",
    },
    {
        id = 10003,
        index = 3,
        name = "金元宝",
        quality = Quality.Normal,
        ys = 60,
        animationName = "lv",
        title = "元宝生辉，财运亨通",
        titleColor = cc.c3b(0x7C,0xE2,0x9E),
        description = "纯金打造元宝，通体金黄，底部刻招财进宝，象征财富积累，助事业兴旺。",
    },
    {
        id = 10004,
        index = 4,
        name = "玉佩",
        quality = Quality.Normal,
        ys = 60,
        animationName = "lv",
        title = "玉翠灵动，聚财纳福",
        titleColor = cc.c3b(0x7C,0xE2,0x9E),
        description = "翠绿玉饰，造型优美带涡旋纹，红绳流苏点缀，温润有光泽，仿若能聚财气、送福气。",
    },
    {
        id = 10005,
        index = 5,
        name = "宝石戒指",
        quality = Quality.Good,
        ys = 80,
        animationName = "lan",
        title = "红宝金戒，财福俱收",
        titleColor = cc.c3b(0x69,0xBA,0xFF),
        description = "金色戒身镶嵌大红宝石，两侧缀蓝绿宝石，花纹精致，似能汇聚财气、带来吉祥好运。",
    },
    {
        id = 10006,
        index = 6,
        name = "聚宝葫芦",
        quality = Quality.Good,
        ys = 80,
        animationName = "lan",
        title = "聚宝葫芦，财福双收",
        titleColor = cc.c3b(0x69,0xBA,0xFF),
        description = "葫芦谐音“福禄”，既聚财又招福，寓意财运亨通的同时，还有健康、平安等福气环绕，吉祥美满。",
    },
    {
        id = 10007,
        index = 7,
        name = "金算盘",
        quality = Quality.Good,
        ys = 80,
        animationName = "lan",
        title = "算珠灵动，财吉满盈",
        titleColor = cc.c3b(0x69,0xBA,0xFF),
        description = "通体纯金算盘，算珠圆润饱满，框架雕祥云纹，精致贵气，似能算八方财，聚纳富贵吉祥。",
    },
    {
        id = 10008,
        index = 8,
        name = "金猪拱财",
        quality = Quality.Good,
        ys = 80,
        animationName = "lan",
        title = "金猪献瑞，拱财纳吉",
        titleColor = cc.c3b(0x69,0xBA,0xFF),
        description = "通体金黄的小猪，体态圆润，衔着铜钱，神态活泼，似能引财上门、带来满满福气。",
    },
    {
        id = 10009,
        index = 9,
        name = "铜钱串",
        quality = Quality.Super,
        ys = 168,
        animationName = "zi",
        title = "铜钱成串，家缠万贯",
        titleColor = cc.c3b(0xFF,0x65,0xF9),
        description = "用红绳串联的古铜钱，代表“万贯家财”寓意财富积累如同串子般越变越长，运气好到挡不住。",
    },
    {
        id = 10010,
        index = 10,
        name = "阴阳宝镜",
        quality = Quality.Super,
        ys = 168,
        animationName = "zi",
        title = "阴阳调和，财气满盈",
        titleColor = cc.c3b(0xFF,0x65,0xF9),
        description = "蓝绿色象征生机与财富，中央的阴阳鱼清晰灵动，似在不断流转，寓意阴阳平衡，能调和气场汇聚财气。",
    },
    {
        id = 10011,
        index = 11,
        name = "转运珠",
        quality = Quality.Super,
        ys = 168,
        animationName = "zi",
        title = "金玉珠连，财吉双至",
        titleColor = cc.c3b(0xFF,0x65,0xF9),
        description = "蓝黄珠粒相间，色泽鲜亮，搭配红流苏，灵动雅致，似能聚拢财气，带来吉祥好运。",
    },
    {
        id = 10012,
        index = 12,
        name = "玉如意",
        quality = Quality.Super,
        ys = 168,
        animationName = "zi",
        title = "如意如意，随我心意",
        titleColor = cc.c3b(0xFF,0x65,0xF9),
        description = "翠绿玉石温润透亮，鎏金祥云纹饰环绕，贵气十足，能招引四方财气，带来顺遂吉祥。",
    },
    {
        id = 10013,
        index = 13,
        name = "招财金猫",
        quality = Quality.Special,
        ys = 666,
        animationName = "cheng",
        title = "金猫捧宝，招财纳福",
        titleColor = cc.c3b(0xFF,0x9B,0x34),
        description = "通体金黄的猫咪，捧金元宝，挂“发”字牌，神态喜庆，似能招揽财富、送来福气。",
    },
    {
        id = 10014,
        index = 14,
        name = "金钱树",
        quality = Quality.Special,
        ys = 666,
        animationName = "cheng",
        title = "金叶满树，聚宝呈祥",
        titleColor = cc.c3b(0xFF,0x9B,0x34),
        description = "满树金黄铜钱，枝干挺拔，底座翠绿带花纹，散落金币点缀，似能摇落财富、汇聚福气。",
    },
    {
        id = 10015,
        index = 15,
        name = "聚宝盆",
        quality = Quality.Special,
        ys = 666,
        animationName = "cheng",
        title = "盆聚万宝，吉祥满溢",
        titleColor = cc.c3b(0xFF,0x9B,0x34),
        description = "红鼎金纹，双耳衔链，满盛元宝铜钱，缀绿珠，富贵庄重，似能广纳财气，助财富充盈、福气降临。",
    },
    {
        id = 10016,
        index = 16,
        name = "金蟾吐宝",
        quality = Quality.Special,
        ys = 666,
        animationName = "cheng",
        title = "金蟾吐宝，财源滚滚",
        titleColor = cc.c3b(0xFF,0x9B,0x34),
        description = "金色蟾蜍，口含铜钱，身绕红绳铜钱饰，蹲坐铜钱堆上，模样富态，似能吸纳财气、带来吉祥。",
    }
}

JuBaoPenConfig.YS_TITLE_CONFIG = {
    {
        index = 1,
        ysStart = 1,
        ysEnd = 200,
        title = "初露锋芒",
    },
    {
        index = 2,
        ysStart = 201,
        ysEnd = 10000,
        title = "福运加身",
    },
    {
        index = 3,
        ysStart = 10001,
        ysEnd = 30000,
        title = "鸿运当头",
    },
    {
        index = 4,
        ysStart = 30001,
        ysEnd = 50000,
        title = "天选之子",
    },
    {
        index = 5,
        ysStart = 50001,
        ysEnd = math.huge,
        title = "气运之主",
    }
}

return JuBaoPenConfig!