-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
    GameSpeakConfig = {
        { ConfID = 1001, index = 301, GameName = "熟客双扣", order = 1, SpeakText = "快点吧，等的花都谢了", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1    },
        { ConfID = 1002, index = 302, GameName = "熟客双扣", order = 2, SpeakText = "急什么，让我想想", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1    },
        { ConfID = 1003, index = 303, GameName = "熟客双扣", order = 3, SpeakText = "和你合作真是太愉快了！", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1    },
        { ConfID = 1004, index = 304, GameName = "熟客双扣", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1    },
        { ConfID = 1005, index = 305, GameName = "熟客双扣", order = 5, SpeakText = "好牌！好牌！", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1    },
        { ConfID = 1006, index = 306, GameName = "熟客双扣", order = 6, SpeakText = "别慌，看我的", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1    },
        { ConfID = 1007, index = 307, GameName = "熟客双扣", order = 7, SpeakText = "炸弹带回家啊？", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1    },
        { ConfID = 1008, index = 308, GameName = "熟客双扣", order = 8, SpeakText = "不要急，一手手来", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1    },
        { ConfID = 1009, index = 309, GameName = "熟客双扣", order = 9, SpeakText = "对家不给力啊", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1    },
        { ConfID = 1010, index = 310, GameName = "熟客双扣", order = 10, SpeakText = "又断网了，网络怎么这么差", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1    },
        { ConfID = 1011, index = 311, GameName = "熟客双扣", order = 11, SpeakText = "各位对不住了，有事先走一步", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1    },
        { ConfID = 1025, index = 5, GameName = "熟客双扣", order = 25, SpeakText = "没吃不倒霉", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1026, index = 6, GameName = "熟客双扣", order = 26, SpeakText = "炸弹带回家", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1027, index = 7, GameName = "熟客双扣", order = 27, SpeakText = "没炸弹啊", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1028, index = 8, GameName = "熟客双扣", order = 28, SpeakText = "定点！别慌", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1029, index = 10, GameName = "熟客双扣", order = 29, SpeakText = "对家，没料?", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1030, index = 11, GameName = "熟客双扣", order = 30, SpeakText = "破牌", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1031, index = 12, GameName = "熟客双扣", order = 31, SpeakText = "双拖双", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1032, index = 13, GameName = "熟客双扣", order = 32, SpeakText = "三拖一", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1033, index = 14, GameName = "熟客双扣", order = 33, SpeakText = "全散", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1034, index = 15, GameName = "熟客双扣", order = 34, SpeakText = "全大", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1035, index = 16, GameName = "熟客双扣", order = 35, SpeakText = "什么牌型那", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1036, index = 17, GameName = "熟客双扣", order = 36, SpeakText = "我帮你瞄着", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1037, index = 109, GameName = "熟客双扣", order = 37, SpeakText = "让他打吧", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1038, index = 110, GameName = "熟客双扣", order = 38, SpeakText = "一手手来", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    }
    }
}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
    tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab�