-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 0, GameName = "温州双扣", order = 1, SpeakText = "人都等睡着了", M_SpeakFileName = "M_Speak121.mp3", W_SpeakFileName = "W_Speak121.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 1, GameName = "温州双扣", order = 2, SpeakText = "动作快点~~", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 2, GameName = "温州双扣", order = 3, SpeakText = "看大字报？~~", M_SpeakFileName = "M_Speak122.mp3", W_SpeakFileName = "W_Speak122.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 3, GameName = "温州双扣", order = 4, SpeakText = "快打快打！", M_SpeakFileName = "M_Speak123.mp3", W_SpeakFileName = "W_Speak123.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 104, GameName = "温州双扣", order = 5, SpeakText = "没味儿", M_SpeakFileName = "M_Speak132.mp3", W_SpeakFileName = "W_Speak132.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 116, GameName = "温州双扣", order = 6, SpeakText = "逃哪里去", M_SpeakFileName = "M_Speak125.mp3", W_SpeakFileName = "W_Speak125.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 112, GameName = "温州双扣", order = 7, SpeakText = "形势看透西", M_SpeakFileName = "M_Speak126.mp3", W_SpeakFileName = "W_Speak126.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "温州双扣", order = 8, SpeakText = "定点！别慌", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 6, GameName = "温州双扣", order = 9, SpeakText = "炸弹带回家", M_SpeakFileName = "M_Speak140.mp3", W_SpeakFileName = "W_Speak140.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "温州双扣", order = 10, SpeakText = "对家，没料?", M_SpeakFileName = "M_Speak141.mp3", W_SpeakFileName = "W_Speak141.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "温州双扣", order = 11, SpeakText = "破牌", M_SpeakFileName = "M_Speak142.mp3", W_SpeakFileName = "W_Speak142.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 14, GameName = "温州双扣", order = 12, SpeakText = "全散", M_SpeakFileName = "M_Speak143.mp3", W_SpeakFileName = "W_Speak143.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 15, GameName = "温州双扣", order = 13, SpeakText = "全大", M_SpeakFileName = "M_Speak144.mp3", W_SpeakFileName = "W_Speak144.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 17, GameName = "温州双扣", order = 14, SpeakText = "我帮你瞄着", M_SpeakFileName = "M_Speak145.mp3", W_SpeakFileName = "W_Speak145.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 113, GameName = "温州双扣", order = 15, SpeakText = "自打错了没怨", M_SpeakFileName = "M_Speak127.mp3", W_SpeakFileName = "W_Speak127.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 114, GameName = "温州双扣", order = 16, SpeakText = "你凶西", M_SpeakFileName = "M_Speak128.mp3", W_SpeakFileName = "W_Speak128.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 100, GameName = "温州双扣", order = 17, SpeakText = "一世痛苦", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 101, GameName = "温州双扣", order = 18, SpeakText = "牌像中石油", M_SpeakFileName = "M_Speak131.mp3", W_SpeakFileName = "W_Speak131.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 110, GameName = "温州双扣", order = 19, SpeakText = "手手来", M_SpeakFileName = "M_Speak146.mp3", W_SpeakFileName = "M_Speak146.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 102, GameName = "温州双扣", order = 20, SpeakText = "南斯拉夫", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	},
		{ ConfID = 1021, index = 4, GameName = "温州双扣", order = 21, SpeakText = "快来那", M_SpeakFileName = "M_Speak124.mp3", W_SpeakFileName = "W_Speak124.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 105, GameName = "温州双扣", order = 22, SpeakText = "强生针", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1023, index = 106, GameName = "温州双扣", order = 23, SpeakText = "关公面前舞大刀", M_SpeakFileName = "M_Speak133.mp3", W_SpeakFileName = "W_Speak133.mp3", listIndex = 1 	},
		{ ConfID = 1024, index = 107, GameName = "温州双扣", order = 24, SpeakText = "哈哈，偷机", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1025, index = 108, GameName = "温州双扣", order = 25, SpeakText = "糖金杏捣裂", M_SpeakFileName = "M_Speak134.mp3", W_SpeakFileName = "W_Speak134.mp3", listIndex = 1 	},
		{ ConfID = 1026, index = 111, GameName = "温州双扣", order = 26, SpeakText = "人毛嫌刀钝", M_SpeakFileName = "M_Speak135.mp3", W_SpeakFileName = "W_Speak135.mp3", listIndex = 1 	},
		{ ConfID = 1027, index = 115, GameName = "温州双扣", order = 27, SpeakText = "赖歪肉吃不壮", M_SpeakFileName = "M_Speak136.mp3", W_SpeakFileName = "W_Speak136.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab,