-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 301, GameName = "宝宝双扣", order = 1, SpeakText = "我等的花都谢了", M_SpeakFileName = "talk_1.mp3", W_SpeakFileName = "talk_1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 302, GameName = "宝宝双扣", order = 2, SpeakText = "急什么，让我想想", M_SpeakFileName = "talk_2.mp3", W_SpeakFileName = "talk_2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 303, GameName = "宝宝双扣", order = 3, SpeakText = "和你合作真是太愉快啦", M_SpeakFileName = "talk_3.mp3", W_SpeakFileName = "talk_3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 304, GameName = "宝宝双扣", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "talk_4.mp3", W_SpeakFileName = "talk_4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 305, GameName = "宝宝双扣", order = 5, SpeakText = "好牌！好牌！", M_SpeakFileName = "talk_5.mp3", W_SpeakFileName = "talk_5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 309, GameName = "宝宝双扣", order = 6, SpeakText = "炸弹带回家？", M_SpeakFileName = "talk_9.mp3", W_SpeakFileName = "talk_9.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 310, GameName = "宝宝双扣", order = 7, SpeakText = "我手牌太差，你自己先走", M_SpeakFileName = "talk_10.mp3", W_SpeakFileName = "talk_10.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 311, GameName = "宝宝双扣", order = 8, SpeakText = "我已经稳坐钓鱼台", M_SpeakFileName = "talk_11.mp3", W_SpeakFileName = "talk_11.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 317, GameName = "宝宝双扣", order = 9, SpeakText = "好好打牌，表说话", M_SpeakFileName = "talk_17.mp3", W_SpeakFileName = "talk_17.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 320, GameName = "宝宝双扣", order = 10, SpeakText = "你这么打牌，我也是醉了\",", M_SpeakFileName = "talk_20.mp3", W_SpeakFileName = "talk_20.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 321, GameName = "宝宝双扣", order = 11, SpeakText = "和你合作我也是蛮拼的", M_SpeakFileName = "talk_21.mp3", W_SpeakFileName = "talk_21.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 323, GameName = "宝宝双扣", order = 12, SpeakText = "这手牌，我是崩溃了", M_SpeakFileName = "talk_23.mp3", W_SpeakFileName = "talk_23.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 324, GameName = "宝宝双扣", order = 13, SpeakText = "快出！快出！快出！", M_SpeakFileName = "talk_24.mp3", W_SpeakFileName = "talk_24.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 315, GameName = "宝宝双扣", order = 15, SpeakText = "生活不止眼前", M_SpeakFileName = "talk_15.mp3", W_SpeakFileName = "talk_15.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 316, GameName = "宝宝双扣", order = 16, SpeakText = "安静地做美男子(宝宝)", M_SpeakFileName = "talk_16.mp3", W_SpeakFileName = "talk_16.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 319, GameName = "宝宝双扣", order = 17, SpeakText = "牌友诚可贵，且打且珍惜", M_SpeakFileName = "talk_19.mp3", W_SpeakFileName = "talk_19.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 325, GameName = "宝宝双扣", order = 18, SpeakText = "不作死就不会死", M_SpeakFileName = "talk_25.mp3", W_SpeakFileName = "talk_25.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 328, GameName = "宝宝双扣", order = 20, SpeakText = "你们城里人真会玩", M_SpeakFileName = "talk_28.mp3", W_SpeakFileName = "talk_28.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 333, GameName = "宝宝双扣", order = 22, SpeakText = "666", M_SpeakFileName = "talk_33.mp3", W_SpeakFileName = "talk_33.mp3", listIndex = 1 	},
		{ ConfID = 1023, index = 334, GameName = "宝宝双扣", order = 23, SpeakText = "还有谁！！！", M_SpeakFileName = "talk_34.mp3", W_SpeakFileName = "talk_34.mp3", listIndex = 1 	},
		{ ConfID = 1025, index = 5, GameName = "宝宝双扣", order = 25, SpeakText = "没吃不倒霉", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1026, index = 6, GameName = "宝宝双扣", order = 26, SpeakText = "炸弹带回家", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1027, index = 7, GameName = "宝宝双扣", order = 27, SpeakText = "没炸弹啊", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1028, index = 8, GameName = "宝宝双扣", order = 28, SpeakText = "定点！别慌", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1029, index = 10, GameName = "宝宝双扣", order = 29, SpeakText = "对家，没料?", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1030, index = 11, GameName = "宝宝双扣", order = 30, SpeakText = "破牌", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1031, index = 12, GameName = "宝宝双扣", order = 31, SpeakText = "双拖双", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1032, index = 13, GameName = "宝宝双扣", order = 32, SpeakText = "三拖一", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1033, index = 14, GameName = "宝宝双扣", order = 33, SpeakText = "全散", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1034, index = 15, GameName = "宝宝双扣", order = 34, SpeakText = "全大", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1035, index = 16, GameName = "宝宝双扣", order = 35, SpeakText = "什么牌型那", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1036, index = 17, GameName = "宝宝双扣", order = 36, SpeakText = "我帮你瞄着", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1037, index = 109, GameName = "宝宝双扣", order = 37, SpeakText = "让他打吧", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    },
        { ConfID = 1038, index = 110, GameName = "宝宝双扣", order = 38, SpeakText = "一手手来", M_SpeakFileName = "M_Speak999.mp3", W_SpeakFileName = "W_Speak999.mp3", listIndex = 1    }
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab