-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "丽水斗地主玩法", order = 1, SpeakText = "我等的花都谢了", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "丽水斗地主玩法", order = 2, SpeakText = "急什么，让我想想", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "丽水斗地主玩法", order = 3, SpeakText = "和你合作真是太愉快啦", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "丽水斗地主玩法", order = 4, SpeakText = "天下还有这样的烂牌！", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "丽水斗地主玩法", order = 5, SpeakText = "好牌好牌", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 109, GameName = "丽水斗地主玩法", order = 6, SpeakText = "炸弹带回家？", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 110, GameName = "丽水斗地主玩法", order = 7, SpeakText = "我手牌太差，你自己先走", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 111, GameName = "丽水斗地主玩法", order = 8, SpeakText = "我已经稳坐钓鱼台", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 117, GameName = "丽水斗地主玩法", order = 9, SpeakText = "好好打牌，表说话", M_SpeakFileName = "M_Speak17.mp3", W_SpeakFileName = "W_Speak17.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 120, GameName = "丽水斗地主玩法", order = 10, SpeakText = "你这么打牌，我也是醉了", M_SpeakFileName = "M_Speak20.mp3", W_SpeakFileName = "W_Speak20.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 121, GameName = "丽水斗地主玩法", order = 11, SpeakText = "和你合作我也是蛮拼的", M_SpeakFileName = "M_Speak21.mp3", W_SpeakFileName = "W_Speak21.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 123, GameName = "丽水斗地主玩法", order = 12, SpeakText = "这手牌，我是崩溃了", M_SpeakFileName = "M_Speak23.mp3", W_SpeakFileName = "W_Speak23.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 124, GameName = "丽水斗地主玩法", order = 13, SpeakText = "快出！快出！快出！", M_SpeakFileName = "M_Speak24.mp3", W_SpeakFileName = "W_Speak24.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 115, GameName = "丽水斗地主玩法", order = 15, SpeakText = "生活不止眼前", M_SpeakFileName = "M_Speak15.mp3", W_SpeakFileName = "W_Speak15.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 116, GameName = "丽水斗地主玩法", order = 16, SpeakText = "安静地做美男子(宝宝)", M_SpeakFileName = "M_Speak16.mp3", W_SpeakFileName = "W_Speak16.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 119, GameName = "丽水斗地主玩法", order = 17, SpeakText = "牌友诚可贵，且打且珍惜", M_SpeakFileName = "M_Speak19.mp3", W_SpeakFileName = "W_Speak19.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 125, GameName = "丽水斗地主玩法", order = 18, SpeakText = "不作死就不会死", M_SpeakFileName = "M_Speak25.mp3", W_SpeakFileName = "W_Speak25.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 128, GameName = "丽水斗地主玩法", order = 20, SpeakText = "你们城里人真会玩", M_SpeakFileName = "M_Speak28.mp3", W_SpeakFileName = "W_Speak28.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 133, GameName = "丽水斗地主玩法", order = 22, SpeakText = "666", M_SpeakFileName = "M_Speak33.mp3", W_SpeakFileName = "W_Speak33.mp3", listIndex = 1 	},
		{ ConfID = 1023, index = 134, GameName = "丽水斗地主玩法", order = 23, SpeakText = "还有谁！！！", M_SpeakFileName = "M_Speak34.mp3", W_SpeakFileName = "W_Speak34.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab