package com.kwad.sdk.core.b.a;

import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.b.a.h;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.ac;
import com.kwad.components.core.webview.jshandler.ad;
import com.kwad.components.core.webview.jshandler.ae;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.b;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.n;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.jshandler.z;
import com.kwad.sdk.i.a;
import com.kwad.sdk.i.b;

/* JADX INFO: loaded from: classes2.dex */
public final class bz {
    public static void AQ() {
        ex.AR().put(com.kwad.components.core.webview.b.b.a.class, new m());
        ex.AR().put(an.a.class, new fd());
        ex.AR().put(com.kwad.components.core.webview.b.b.f.class, new bn());
        ex.AR().put(aq.a.class, new jj());
        ex.AR().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new x());
        ex.AR().put(a.C0223a.class, new cs());
        ex.AR().put(v.a.class, new go());
        ex.AR().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new w());
        ex.AR().put(com.kwad.components.core.webview.b.b.g.class, new bq());
        ex.AR().put(com.kwad.components.core.webview.b.b.l.class, new fb());
        ex.AR().put(a.b.class, new cp());
        ex.AR().put(ah.a.class, new gf());
        ex.AR().put(z.a.class, new eb());
        ex.AR().put(com.kwad.components.core.webview.b.b.w.class, new jd());
        ex.AR().put(com.kwad.components.core.webview.b.b.y.class, new ji());
        ex.AR().put(l.a.class, new ik());
        ex.AR().put(com.kwad.components.core.webview.b.b.i.class, new dv());
        ex.AR().put(com.kwad.components.core.webview.b.b.o.class, new gd());
        ex.AR().put(com.kwad.components.core.webview.b.b.t.class, new hr());
        ex.AR().put(ai.a.class, new ap());
        ex.AR().put(c.a.class, new dq());
        ex.AR().put(ac.a.class, new cc());
        ex.AR().put(com.kwad.components.core.webview.b.b.p.class, new gl());
        ex.AR().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new v());
        ex.AR().put(b.a.class, new dp());
        ex.AR().put(com.kwad.components.core.webview.b.b.e.class, new bg());
        ex.AR().put(e.a.class, new ds());
        ex.AR().put(ae.a.class, new et());
        ex.AR().put(au.a.class, new ew());
        ex.AR().put(com.kwad.components.core.webview.b.b.s.class, new hq());
        ex.AR().put(e.b.class, new dt());
        ex.AR().put(n.a.class, new q());
        ex.AR().put(WebCardVideoPositionHandler.VideoPosition.class, new jh());
        ex.AR().put(com.kwad.components.core.webview.b.b.j.class, new ev());
        ex.AR().put(d.a.class, new dr());
        ex.AR().put(com.kwad.components.core.offline.b.class, new fx());
        ex.AR().put(com.kwad.components.core.webview.b.b.b.class, new at());
        ex.AR().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ey());
        ex.AR().put(com.kwad.components.core.webview.b.b.h.class, new cg());
        ex.AR().put(com.kwad.components.core.webview.b.b.v.class, new jb());
        ex.AR().put(y.a.class, new jc());
        ex.AR().put(a.C0166a.class, new cm());
        ex.AR().put(com.kwad.components.core.k.a.class, new p());
        ex.AR().put(w.a.class, new gp());
        ex.AR().put(com.kwad.components.core.webview.a.b.class, new fy());
        ex.AR().put(ae.b.class, new eu());
        ex.AR().put(com.kwad.components.core.webview.b.b.u.class, new ib());
        ex.AR().put(b.C0224b.class, new hk());
        ex.AR().put(com.kwad.components.core.webview.b.b.q.class, new hn());
        ex.AR().put(com.kwad.components.core.webview.b.b.x.class, new jf());
        ex.AR().put(com.kwad.components.core.webview.a.c.class, new ga());
        ex.AR().put(com.kwad.components.core.webview.b.b.m.class, new fn());
        ex.AR().put(h.a.class, new ej());
        ex.AR().put(ak.a.class, new ay());
        ex.AR().put(a.b.class, new ee());
        ex.AR().put(b.a.class, new hj());
        ex.AR().put(h.b.class, new ek());
        ex.AR().put(g.a.class, new du());
        ex.AR().put(com.kwad.components.core.webview.b.b.d.class, new ax());
        ex.AR().put(ar.a.class, new iq());
        ex.AR().put(com.kwad.components.core.webview.b.b.r.class, new hp());
        ex.AR().put(com.kwad.components.core.webview.b.b.c.class, new av());
        ex.AR().put(ad.b.class, new dx());
        ex.AR().put(aj.b.class, new as());
        ex.AR().put(com.kwad.sdk.a.a.a.a.class, new el());
        ex.AR().put(as.a.class, new dz());
        ex.AR().put(com.kwad.components.core.webview.b.b.n.class, new fz());
        ex.AR().put(aj.a.class, new ar());
        ex.AR().put(h.b.class, new gn());
    }
}
