package com.tkay.expressad.video.module.a;

public interface a {
    public static final int A = 110;
    public static final int B = 111;
    public static final int C = 112;
    public static final int D = 113;
    public static final int E = 114;
    public static final int F = 115;
    public static final int G = 116;
    public static final int H = 122;
    public static final int I = 118;
    public static final int J = 119;
    public static final int K = 117;
    public static final int L = 121;
    public static final int M = 120;
    public static final int N = 123;
    public static final int O = 124;
    public static final int P = 125;
    public static final int Q = 126;
    public static final int R = 127;
    public static final int S = 128;
    public static final int T = 129;
    public static final int b = -1;
    public static final int c = 1;
    public static final int d = 2;
    public static final int e = 8;
    public static final int f = 5;
    public static final int g = 6;
    public static final int h = 7;
    public static final int i = 10;
    public static final int j = 11;
    public static final int k = 12;
    public static final int l = 13;
    public static final int m = 14;
    public static final int n = 15;
    public static final int o = 16;
    public static final int p = 17;
    public static final int q = 100;
    public static final int r = 101;
    public static final int s = 102;
    public static final int t = 103;
    public static final int u = 104;
    public static final int v = 105;
    public static final int w = 106;
    public static final int x = 107;
    public static final int y = 108;
    public static final int z = 109;

    void a(int r1, java.lang.Object r2);
}
