package com.ss.android.socialbase.downloader.constants;

public interface DBDefinition {
    public static final java.lang.String APP_VERSION_CODE = "appVersionCode";
    public static final java.lang.String AUXILIARY_JSONOBJECT_STRING = "auxiliaryJsonobjectString";
    public static final java.lang.String BACKUP_URLS_STR = "backUpUrlsStr";
    public static final java.lang.String BACKUP_URL_RETRY_COUNT = "backUpUrlRetryCount";
    public static final java.lang.String[] CHUNK_ALL_COLUMNS = null;
    public static final java.lang.String CHUNK_CONTENT_LEN = "chunkContentLen";
    public static final java.lang.String CHUNK_COUNT = "chunkCount";
    public static final java.lang.String CHUNK_DOWNGRADE_RETRY = "chunkDowngradeRetry";
    public static final java.lang.String CHUNK_INDEX = "chunkIndex";
    public static final java.lang.String[] CHUNK_PK_COLUMNS = null;
    public static final java.lang.String CHUNK_RUNNABLE_REUSE = "chunkRunnableReuse";
    public static final java.lang.String CHUNK_TABLE_NAME = "downloadChunk";
    public static final java.lang.String CREATE_CHUNK_TABLE = "CREATE TABLE IF NOT EXISTS downloadChunk( _id INTEGER, chunkIndex INTEGER, startOffset INTEGER, curOffset INTEGER, endOffset INTEGER, chunkContentLen INTEGER, hostChunkIndex INTEGER )";
    public static final java.lang.String CREATE_DOWNLOAD_TABLE = "CREATE TABLE IF NOT EXISTS downloader( _id INTEGER PRIMARY KEY, url TEXT, savePath TEXT, tempPath TEXT, name TEXT, chunkCount INTEGER, status INTEGER, curBytes INTEGER, totalBytes INTEGER, eTag TEXT, onlyWifi INTEGER, force INTEGER, retryCount INTEGER, extra TEXT, mimeType TEXT, title TEXT, notificationEnable INTEGER, notificationVisibility INTEGER, isFirstDownload INTEGER, isFirstSuccess INTEGER, needHttpsToHttpRetry INTEGER, downloadTime INTEGER, packageName TEXT, md5 TEXT, retryDelay INTEGER, curRetryTime INTEGER, retryDelayStatus INTEGER, defaultHttpServiceBackUp INTEGER, chunkRunnableReuse INTEGER, retryDelayTimeArray TEXT, chunkDowngradeRetry INTEGER, backUpUrlsStr TEXT, backUpUrlRetryCount INTEGER, realDownloadTime INTEGER, retryScheduleMinutes INTEGER, independentProcess INTEGER, auxiliaryJsonobjectString TEXT, iconUrl TEXT, appVersionCode INTEGER, taskId TEXT)";
    public static final java.lang.String CREATE_SEGMENT_TABLE = "CREATE TABLE IF NOT EXISTS segments( _id INTEGER PRIMARY KEY,info TEXT )";
    public static final java.lang.String CUR_BYTES = "curBytes";
    public static final java.lang.String CUR_OFFSET = "curOffset";
    public static final java.lang.String CUR_RETRY_TIME = "curRetryTime";
    public static final java.lang.String DATABASE_NAME = "downloader.db";
    public static final int DATABASE_VERSION = 15;
    public static final java.lang.String DEFAULT_HTTP_SERVICE_BACKUP = "defaultHttpServiceBackUp";
    public static final java.lang.String[] DOWNLOAD_ALL_COLUMNS = null;
    public static final java.lang.String[] DOWNLOAD_PK_COLUMNS = null;
    public static final java.lang.String DOWNLOAD_TABLE_NAME = "downloader";
    public static final java.lang.String DOWNLOAD_TIME = "downloadTime";
    public static final java.lang.String END_OFFSET = "endOffset";
    public static final java.lang.String ETAG = "eTag";
    public static final java.lang.String EXTRA = "extra";
    public static final java.lang.String FIRST_DOWNLOAD = "isFirstDownload";
    public static final java.lang.String FIRST_SUCCESS = "isFirstSuccess";
    public static final java.lang.String FORCE = "force";
    public static final java.lang.String HOST_CHUNK_INDEX = "hostChunkIndex";
    public static final java.lang.String ICON_URL = "iconUrl";
    public static final java.lang.String ID = "_id";
    public static final java.lang.String INDEPENDENT_PROCESS = "independentProcess";
    public static final java.lang.String MD5 = "md5";
    public static final java.lang.String MIME_TYPE = "mimeType";
    public static final java.lang.String NAME = "name";
    public static final java.lang.String NEED_HTTPS_TO_HTTP_RETRY = "needHttpsToHttpRetry";
    public static final java.lang.String NOTIFICATION_ENABLE = "notificationEnable";
    public static final java.lang.String NOTIFICATION_VISIBILITY = "notificationVisibility";
    public static final java.lang.String ONLY_WIFI = "onlyWifi";
    public static final java.lang.String PACKAGE_NAME = "packageName";
    public static final java.lang.String REAL_DOWNLOAD_TIME = "realDownloadTime";
    public static final java.lang.String RETRY_COUNT = "retryCount";
    public static final java.lang.String RETRY_DELAY = "retryDelay";
    public static final java.lang.String RETRY_DELAY_STATUS = "retryDelayStatus";
    public static final java.lang.String RETRY_DELAY_TIME_ARRAY = "retryDelayTimeArray";
    public static final java.lang.String RETRY_SCHEDULE_MINUTES = "retryScheduleMinutes";
    public static final java.lang.String SAVE_PATH = "savePath";
    public static final java.lang.String[] SEGMENT_ALL_COLUMNS = null;
    public static final java.lang.String SEGMENT_INFO = "info";
    public static final java.lang.String[] SEGMENT_PK_COLUMNS = null;
    public static final java.lang.String SEGMENT_TABLE_NAME = "segments";
    public static final java.lang.String START_OFFSET = "startOffset";
    public static final java.lang.String STATUS = "status";
    public static final java.lang.String TASK_ID = "taskId";
    public static final java.lang.String TEMP_PATH = "tempPath";
    public static final java.lang.String TITLE = "title";
    public static final java.lang.String TOTAL_BYTES = "totalBytes";
    public static final java.lang.String URL = "url";
    public static final int VERSION_DOWNLOAD_TABLE_ADD_AUXILIARY_JSONOBJECT_STRING = 12;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_CHUNK_RUNNABLE_REUSE = 9;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_COLUMNS = 2;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_DOWNLOAD_TIME = 5;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_FIRST_START = 3;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_FIRST_SUCCESS = 4;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_HOST_CHUNK_INDEX = 8;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_ICON_AND_VERSION = 13;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_RETRY_DELAY = 7;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_RETRY_TIME_ARRAY = 10;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_SECURITY_VERIFY = 6;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_TASK_ID = 15;
    public static final int VERSION_DOWNLOAD_TABLE_ADD_TOTAL_RETRY_COUNT = 11;
    public static final int VERSION_INIT = 1;
    public static final int VERSION_SEGMENT_TABLE_ADD = 14;

    static {
            java.lang.String r0 = "_id"
            java.lang.String r1 = "url"
            java.lang.String r2 = "savePath"
            java.lang.String r3 = "tempPath"
            java.lang.String r4 = "name"
            java.lang.String r5 = "chunkCount"
            java.lang.String r6 = "status"
            java.lang.String r7 = "curBytes"
            java.lang.String r8 = "totalBytes"
            java.lang.String r9 = "eTag"
            java.lang.String r10 = "onlyWifi"
            java.lang.String r11 = "force"
            java.lang.String r12 = "retryCount"
            java.lang.String r13 = "extra"
            java.lang.String r14 = "mimeType"
            java.lang.String r15 = "title"
            java.lang.String r16 = "notificationEnable"
            java.lang.String r17 = "notificationVisibility"
            java.lang.String r18 = "isFirstDownload"
            java.lang.String r19 = "isFirstSuccess"
            java.lang.String r20 = "needHttpsToHttpRetry"
            java.lang.String r21 = "downloadTime"
            java.lang.String r22 = "packageName"
            java.lang.String r23 = "md5"
            java.lang.String r24 = "retryDelay"
            java.lang.String r25 = "curRetryTime"
            java.lang.String r26 = "retryDelayStatus"
            java.lang.String r27 = "defaultHttpServiceBackUp"
            java.lang.String r28 = "chunkRunnableReuse"
            java.lang.String r29 = "retryDelayTimeArray"
            java.lang.String r30 = "chunkDowngradeRetry"
            java.lang.String r31 = "backUpUrlsStr"
            java.lang.String r32 = "backUpUrlRetryCount"
            java.lang.String r33 = "realDownloadTime"
            java.lang.String r34 = "retryScheduleMinutes"
            java.lang.String r35 = "independentProcess"
            java.lang.String r36 = "auxiliaryJsonobjectString"
            java.lang.String r37 = "iconUrl"
            java.lang.String r38 = "appVersionCode"
            java.lang.String r39 = "taskId"
            java.lang.String[] r0 = new java.lang.String[]{r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31, r32, r33, r34, r35, r36, r37, r38, r39}
            com.ss.android.socialbase.downloader.constants.DBDefinition.DOWNLOAD_ALL_COLUMNS = r0
            java.lang.String r0 = "_id"
            java.lang.String[] r1 = new java.lang.String[]{r0}
            com.ss.android.socialbase.downloader.constants.DBDefinition.DOWNLOAD_PK_COLUMNS = r1
            java.lang.String r2 = "_id"
            java.lang.String r3 = "chunkIndex"
            java.lang.String r4 = "startOffset"
            java.lang.String r5 = "curOffset"
            java.lang.String r6 = "endOffset"
            java.lang.String r7 = "chunkContentLen"
            java.lang.String r8 = "hostChunkIndex"
            java.lang.String[] r1 = new java.lang.String[]{r2, r3, r4, r5, r6, r7, r8}
            com.ss.android.socialbase.downloader.constants.DBDefinition.CHUNK_ALL_COLUMNS = r1
            java.lang.String[] r1 = new java.lang.String[]{r0}
            com.ss.android.socialbase.downloader.constants.DBDefinition.CHUNK_PK_COLUMNS = r1
            java.lang.String r1 = "info"
            java.lang.String[] r1 = new java.lang.String[]{r0, r1}
            com.ss.android.socialbase.downloader.constants.DBDefinition.SEGMENT_ALL_COLUMNS = r1
            java.lang.String[] r0 = new java.lang.String[]{r0}
            com.ss.android.socialbase.downloader.constants.DBDefinition.SEGMENT_PK_COLUMNS = r0
            return
    }
}
