-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "乐清麻将", order = 1, SpeakText = "糖金杏捣裂", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "乐清麻将", order = 2, SpeakText = "人等睡着了", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "乐清麻将", order = 3, SpeakText = "动作快点~", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "乐清麻将", order = 4, SpeakText = "看大字报？", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "乐清麻将", order = 5, SpeakText = "你凶西~", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "乐清麻将", order = 6, SpeakText = "没味儿！", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "乐清麻将", order = 7, SpeakText = "破牌==", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "乐清麻将", order = 8, SpeakText = "哈哈！偷鸡", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "乐清麻将", order = 9, SpeakText = "没吃不倒霉", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "乐清麻将", order = 10, SpeakText = "形势看透西", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "乐清麻将", order = 11, SpeakText = "逃哪里去~", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "乐清麻将", order = 12, SpeakText = "定点，别慌", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab