-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "长兴玩法", order = 1, SpeakText = "打牌动作快点呐", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "长兴玩法", order = 2, SpeakText = "你老人家快点哈！", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "长兴玩法", order = 3, SpeakText = "哎呀~对不住了！", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "长兴玩法", order = 4, SpeakText = "回家再练练吧您呐~", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "长兴玩法", order = 5, SpeakText = "太谢谢你啦！", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "长兴玩法", order = 6, SpeakText = "运气太好怪我喽！", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "长兴玩法", order = 7, SpeakText = "我的天呐!心里苦啊", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "长兴玩法", order = 8, SpeakText = "真是晕了", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "长兴玩法", order = 9, SpeakText = "想想先，别慌~", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "长兴玩法", order = 10, SpeakText = "坐你下家人都饿死了", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "长兴玩法", order = 11, SpeakText = "牌太烂了", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "长兴玩法", order = 12, SpeakText = "哪有你这么出牌的", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 13, GameName = "长兴玩法", order = 13, SpeakText = "给张牌吃吃嘛", M_SpeakFileName = "M_Speak13.mp3", W_SpeakFileName = "W_Speak13.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 14, GameName = "长兴玩法", order = 14, SpeakText = "牛牛牛牛！！！", M_SpeakFileName = "M_Speak14.mp3", W_SpeakFileName = "W_Speak14.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab