-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 201, GameName = "龙港麻将", order = 1, SpeakText = "打快点", M_SpeakFileName = "M_Speak201.mp3", W_SpeakFileName = "W_Speak201.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 202, GameName = "龙港麻将", order = 2, SpeakText = "真会碰", M_SpeakFileName = "M_Speak202.mp3", W_SpeakFileName = "W_Speak202.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 203, GameName = "龙港麻将", order = 3, SpeakText = "打给我吃", M_SpeakFileName = "M_Speak203.mp3", W_SpeakFileName = "W_Speak203.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 204, GameName = "龙港麻将", order = 4, SpeakText = "打的真好", M_SpeakFileName = "M_Speak204.mp3", W_SpeakFileName = "W_Speak204.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 205, GameName = "龙港麻将", order = 5, SpeakText = "牌别乱打", M_SpeakFileName = "M_Speak205.mp3", W_SpeakFileName = "W_Speak205.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 206, GameName = "龙港麻将", order = 6, SpeakText = "盯牢头家", M_SpeakFileName = "M_Speak206.mp3", W_SpeakFileName = "W_Speak206.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 207, GameName = "龙港麻将", order = 7, SpeakText = "打通宵", M_SpeakFileName = "M_Speak207.mp3", W_SpeakFileName = "W_Speak207.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab