-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "嘉兴硬自摸", order = 1, SpeakText = "快点吧，我等得花都谢了", M_SpeakFileName = "talk_1.mp3", W_SpeakFileName = "talk_1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "嘉兴硬自摸", order = 2, SpeakText = "急什么，让我想想怎么打", M_SpeakFileName = "talk_2.mp3", W_SpeakFileName = "talk_2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "嘉兴硬自摸", order = 3, SpeakText = "和你合作真是太愉快啦", M_SpeakFileName = "talk_3.mp3", W_SpeakFileName = "talk_3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "嘉兴硬自摸", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "talk_4.mp3", W_SpeakFileName = "talk_4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "嘉兴硬自摸", order = 5, SpeakText = "好牌好牌", M_SpeakFileName = "talk_5.mp3", W_SpeakFileName = "talk_5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "嘉兴硬自摸", order = 6, SpeakText = "只想安静地做个美男子(宝宝）", M_SpeakFileName = "talk_6.mp3", W_SpeakFileName = "talk_6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "嘉兴硬自摸", order = 7, SpeakText = "好好打牌，表说话", M_SpeakFileName = "talk_7.mp3", W_SpeakFileName = "talk_7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "嘉兴硬自摸", order = 8, SpeakText = "牌友诚可贵，且打且珍惜", M_SpeakFileName = "talk_8.mp3", W_SpeakFileName = "talk_8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "嘉兴硬自摸", order = 9, SpeakText = "你这么打牌，我也是醉了", M_SpeakFileName = "talk_9.mp3", W_SpeakFileName = "talk_9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "嘉兴硬自摸", order = 10, SpeakText = "和你合作我也是蛮拼的", M_SpeakFileName = "talk_10.mp3", W_SpeakFileName = "talk_10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "嘉兴硬自摸", order = 11, SpeakText = "这手牌，我的内心几乎是崩溃的", M_SpeakFileName = "talk_11.mp3", W_SpeakFileName = "talk_11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "嘉兴硬自摸", order = 12, SpeakText = "快出！快出！快出！重要的事情说三遍", M_SpeakFileName = "talk_12.mp3", W_SpeakFileName = "talk_12.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 13, GameName = "嘉兴硬自摸", order = 13, SpeakText = "不作死就不会死", M_SpeakFileName = "talk_13.mp3", W_SpeakFileName = "talk_13.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 16, GameName = "嘉兴硬自摸", order = 16, SpeakText = "你们城里人真会玩", M_SpeakFileName = "talk_16.mp3", W_SpeakFileName = "talk_16.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 17, GameName = "嘉兴硬自摸", order = 17, SpeakText = "we are 伐木累, 好牌友一辈子", M_SpeakFileName = "talk_17.mp3", W_SpeakFileName = "talk_17.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 18, GameName = "嘉兴硬自摸", order = 18, SpeakText = "duang~~", M_SpeakFileName = "talk_18.mp3", W_SpeakFileName = "talk_18.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 19, GameName = "嘉兴硬自摸", order = 19, SpeakText = "666", M_SpeakFileName = "talk_19.mp3", W_SpeakFileName = "talk_19.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 20, GameName = "嘉兴硬自摸", order = 20, SpeakText = "还有谁！！！", M_SpeakFileName = "talk_20.mp3", W_SpeakFileName = "talk_20.mp3", listIndex = 1 	},
		{ ConfID = 1021, index = 21, GameName = "嘉兴硬自摸", order = 21, SpeakText = "人要赢得起，也要输得起", M_SpeakFileName = "talk_21.mp3", W_SpeakFileName = "talk_21.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab