-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	DoubleKouShare = {
		{ ConfID = 30289, GameName = "青田双扣", PackageName = "青田（茶）", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30297, GameName = "丽水双扣", PackageName = "丽水（茶）", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30313, GameName = "温州双扣", PackageName = "温州（茶）", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"温州双扣,二人对杀速度来！\"", Title_2_0 = "\"温州双扣,二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"温州双扣,一等三牌搭子呢?\"", Title_2_2 = "\"温州双扣,二拖二好着急呀!\"", Title_3_1 = "\"温州双扣,三缺一速来速来!\"", Title_4_0 = "\"温州双扣,正在火拼速来组局!\"" 	},
		{ ConfID = 30067, GameName = "温州双扣", PackageName = "熟客温州麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"温州双扣,二人对杀速度来！\"", Title_2_0 = "\"温州双扣,二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"温州双扣,一等三牌搭子呢?\"", Title_2_2 = "\"温州双扣,二拖二好着急呀!\"", Title_3_1 = "\"温州双扣,三缺一速来速来!\"", Title_4_0 = "\"温州双扣,正在火拼速来组局!\"" 	},
		{ ConfID = 30142, GameName = "杭州双扣", PackageName = "杭麻圈", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30388, GameName = "建德双扣", PackageName = "杭麻圈", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30160, GameName = "宝宝双扣", PackageName = "宝宝杭州麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30063, GameName = "双扣", PackageName = "衢州麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30273, GameName = "温州双扣", PackageName = "瑞安麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30222, GameName = "温州双扣", PackageName = "乐清麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30172, GameName = "浙中双扣", PackageName = "浙中麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30405, GameName = "衢州双扣", PackageName = "衢州麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
        { ConfID = 30130, GameName = "双扣", PackageName = "台州", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
		{ ConfID = 30419, GameName = "绍兴双扣玩法", PackageName = "绍兴麻将", WinLostToFriend = "", WinLostToCircle = "", SensitiveWords = { "\"支付\"", "\"麻将\"", "\"扑克\"" }, Title_1_1 = "\"二人对杀速度来！\"", Title_2_0 = "\"二人对杀速度来！\"", Title_1_2 = "\"一等二好无奈呀!\"", Title_2_1 = "\"二缺一速来速来!\"\",正在火拼速来组局!\"", Title_3_0 = "\"正在火拼速来组局!\"", Title_1_3 = "\"一等三牌搭子呢?\"", Title_2_2 = "\"二拖二好着急呀!\"", Title_3_1 = "\"三缺一速来速来!\"", Title_4_0 = "\"正在火拼速来组局!\"" 	},
	}

}


-- ConfID
tab.DoubleKouShareByConfID = {}
for _, rec in pairs(tab.DoubleKouShare) do
	tab.DoubleKouShareByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab�"  