-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "开化玩法", order = 1, SpeakText = "打快点", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "开化玩法", order = 2, SpeakText = "真会碰", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "开化玩法", order = 3, SpeakText = "不搭牌", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "开化玩法", order = 4, SpeakText = "暗杠碰没了", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "开化玩法", order = 5, SpeakText = "牌太烂", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "开化玩法", order = 6, SpeakText = "大对子哇", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "开化玩法", order = 7, SpeakText = "抓张杠杠", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "开化玩法", order = 8, SpeakText = "跟住", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 109, GameName = "开化玩法", order = 9, SpeakText = "流局", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 110, GameName = "开化玩法", order = 10, SpeakText = "没法玩了", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "开化玩法", order = 11, SpeakText = "要胡了", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab'	