-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "三人杭麻", order = 1, SpeakText = "打的嘎慢，同老太婆一样", M_SpeakFileName = "talk_1.mp3", W_SpeakFileName = "talk_1.mp3", listIndex = 2 	},
		{ ConfID = 1002, index = 2, GameName = "三人杭麻", order = 2, SpeakText = "总要让我看看灵清", M_SpeakFileName = "talk_2.mp3", W_SpeakFileName = "talk_2.mp3", listIndex = 2 	},
		{ ConfID = 1003, index = 3, GameName = "三人杭麻", order = 3, SpeakText = "你个牌儿打了太老级了", M_SpeakFileName = "talk_3.mp3", W_SpeakFileName = "talk_3.mp3", listIndex = 2 	},
		{ ConfID = 1004, index = 4, GameName = "三人杭麻", order = 4, SpeakText = "要命的个牌横打竖打都是输", M_SpeakFileName = "talk_4.mp3", W_SpeakFileName = "talk_4.mp3", listIndex = 2 	},
		{ ConfID = 1005, index = 5, GameName = "三人杭麻", order = 5, SpeakText = "接个牌儿真当好", M_SpeakFileName = "talk_5.mp3", W_SpeakFileName = "talk_5.mp3", listIndex = 2 	},
		{ ConfID = 1006, index = 6, GameName = "三人杭麻", order = 6, SpeakText = "财神财神救救穷人", M_SpeakFileName = "talk_6.mp3", W_SpeakFileName = "talk_6.mp3", listIndex = 2 	},
		{ ConfID = 1007, index = 7, GameName = "三人杭麻", order = 7, SpeakText = "两个财神都没得胡个，这个麻将搓不来的", M_SpeakFileName = "talk_7.mp3", W_SpeakFileName = "talk_7.mp3", listIndex = 2 	},
		{ ConfID = 1008, index = 8, GameName = "三人杭麻", order = 8, SpeakText = "驻的牢输的少", M_SpeakFileName = "talk_8.mp3", W_SpeakFileName = "talk_8.mp3", listIndex = 2 	},
		{ ConfID = 1009, index = 1, GameName = "三人杭麻", order = 1, SpeakText = "快点吧，我等得花都谢了", M_SpeakFileName = "talk_1.mp3", W_SpeakFileName = "talk_1.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 2, GameName = "三人杭麻", order = 2, SpeakText = "急什么，让我想想怎么打", M_SpeakFileName = "talk_2.mp3", W_SpeakFileName = "talk_2.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 3, GameName = "三人杭麻", order = 3, SpeakText = "和你合作真是太愉快啦", M_SpeakFileName = "talk_3.mp3", W_SpeakFileName = "talk_3.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 4, GameName = "三人杭麻", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "talk_4.mp3", W_SpeakFileName = "talk_4.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 5, GameName = "三人杭麻", order = 5, SpeakText = "好牌好牌", M_SpeakFileName = "talk_5.mp3", W_SpeakFileName = "talk_5.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 6, GameName = "三人杭麻", order = 6, SpeakText = "各路财神爷行行好", M_SpeakFileName = "talk_6.mp3", W_SpeakFileName = "talk_6.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 7, GameName = "三人杭麻", order = 7, SpeakText = "摸再多的财神也胡不了啊", M_SpeakFileName = "talk_7.mp3", W_SpeakFileName = "talk_7.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 8, GameName = "三人杭麻", order = 8, SpeakText = "管住庄家就输的少", M_SpeakFileName = "talk_8.mp3", W_SpeakFileName = "talk_8.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

-- index
tab.GameSpeakConfigByindex = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByindex[rec.index] = rec
end

tab.Enum = {
}

return tab�