-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "德清麻将", order = 1, SpeakText = "快点打呀，快点打呀", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "德清麻将", order = 2, SpeakText = "弄张吃吃", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "德清麻将", order = 3, SpeakText = "噶好牌都胡不了", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "德清麻将", order = 4, SpeakText = "这些牌真腻心啊", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "德清麻将", order = 5, SpeakText = "财神都没有胡什么胡", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "德清麻将", order = 6, SpeakText = "我就要听张了", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "德清麻将", order = 7, SpeakText = "碰碰碰，就知道碰", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "德清麻将", order = 8, SpeakText = "这副牌财神啊没有", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "德清麻将", order = 9, SpeakText = "上碰下自摸", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "德清麻将", order = 10, SpeakText = "我要拉杠的", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "德清麻将", order = 11, SpeakText = "财神已经很久没见了", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "德清麻将", order = 12, SpeakText = "吃什么拉什么", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 13, GameName = "德清麻将", order = 13, SpeakText = "这个牌太好了", M_SpeakFileName = "M_Speak13.mp3", W_SpeakFileName = "W_Speak13.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 14, GameName = "德清麻将", order = 14, SpeakText = "这个牌真垃圾啊", M_SpeakFileName = "M_Speak14.mp3", W_SpeakFileName = "W_Speak14.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab�