-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "沈家门玩法", order = 1, SpeakText = "快点啊，都等到我花儿都谢了！", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "沈家门玩法", order = 2, SpeakText = "不要走，决战到天亮！", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "沈家门玩法", order = 3, SpeakText = "怎么又断线了，网络怎么这么差啊！", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "沈家门玩法", order = 4, SpeakText = "大家好，很高兴见到各位！", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "沈家门玩法", order = 5, SpeakText = "各位，真是不好意思，我得离开一会。", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "沈家门玩法", order = 6, SpeakText = "和你合作真是太愉快了！", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "沈家门玩法", order = 7, SpeakText = "你的牌打的也忒好啦！", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "沈家门玩法", order = 9, SpeakText = "交个朋友吧，能告诉我你的联系方式吗？", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "沈家门玩法", order = 10, SpeakText = "下次我们再玩吧，我要走了！", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "沈家门玩法", order = 11, SpeakText = "再见咯，我会想念大家的！", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "沈家门玩法", order = 12, SpeakText = "不要吵了，有什么好吵的，专心玩游戏吧。", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tabl
