-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "杭州玩法", order = 1, SpeakText = "打快点", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "杭州玩法", order = 2, SpeakText = "真会碰", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "杭州玩法", order = 3, SpeakText = "不搭牌", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "杭州玩法", order = 4, SpeakText = "暗杠碰没了", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "杭州玩法", order = 5, SpeakText = "牌太烂了", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "杭州玩法", order = 6, SpeakText = "大对子哇", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "杭州玩法", order = 7, SpeakText = "抓张杠杠", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "杭州玩法", order = 8, SpeakText = "跟住", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "杭州玩法", order = 9, SpeakText = "流局", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "杭州玩法", order = 10, SpeakText = "要全包了", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "杭州玩法", order = 11, SpeakText = "要胡了", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab�