-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 109, GameName = "杭麻双扣", order = 1, SpeakText = "炸弹带回家？", M_SpeakFileName = "talk_9.mp3", W_SpeakFileName = "talk_9.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 110, GameName = "杭麻双扣", order = 2, SpeakText = "我手牌太差，你自己先走", M_SpeakFileName = "talk_10.mp3", W_SpeakFileName = "talk_10.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 111, GameName = "杭麻双扣", order = 3, SpeakText = "我已经稳坐钓鱼台", M_SpeakFileName = "talk_11.mp3", W_SpeakFileName = "talk_11.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 101, GameName = "杭麻双扣", order = 4, SpeakText = "快点吧，我等的花都谢了", M_SpeakFileName = "talk_1.mp3", W_SpeakFileName = "talk_1.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 102, GameName = "杭麻双扣", order = 5, SpeakText = "急什么，让我想想", M_SpeakFileName = "talk_2.mp3", W_SpeakFileName = "talk_2.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 104, GameName = "杭麻双扣", order = 6, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "talk_4.mp3", W_SpeakFileName = "talk_4.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 105, GameName = "杭麻双扣", order = 7, SpeakText = "好牌好牌", M_SpeakFileName = "talk_5.mp3", W_SpeakFileName = "talk_5.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 115, GameName = "杭麻双扣", order = 8, SpeakText = "生活不止眼前的苟且，还有杭牌和远方的田野", M_SpeakFileName = "talk_15.mp3", W_SpeakFileName = "talk_15.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 116, GameName = "杭麻双扣", order = 9, SpeakText = "安静地做美男子(宝宝)", M_SpeakFileName = "talk_16.mp3", W_SpeakFileName = "talk_16.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 117, GameName = "杭麻双扣", order = 10, SpeakText = "好好打牌，表说话", M_SpeakFileName = "talk_17.mp3", W_SpeakFileName = "talk_17.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 118, GameName = "杭麻双扣", order = 11, SpeakText = "boss带我装逼带我飞", M_SpeakFileName = "talk_18.mp3", W_SpeakFileName = "talk_18.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 119, GameName = "杭麻双扣", order = 12, SpeakText = "牌友诚可贵，且打且珍惜", M_SpeakFileName = "talk_19.mp3", W_SpeakFileName = "talk_19.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 120, GameName = "杭麻双扣", order = 13, SpeakText = "你这么打牌，我也是醉了\",", M_SpeakFileName = "talk_20.mp3", W_SpeakFileName = "talk_20.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 121, GameName = "杭麻双扣", order = 14, SpeakText = "和你合作我也是蛮拼的", M_SpeakFileName = "talk_21.mp3", W_SpeakFileName = "talk_21.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 122, GameName = "杭麻双扣", order = 15, SpeakText = "大牌这么厉害，你妈妈知道吗？", M_SpeakFileName = "talk_22.mp3", W_SpeakFileName = "talk_22.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 123, GameName = "杭麻双扣", order = 16, SpeakText = "这手牌，我是崩溃了", M_SpeakFileName = "talk_23.mp3", W_SpeakFileName = "talk_23.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 124, GameName = "杭麻双扣", order = 17, SpeakText = "快出！快出！快出！重要的事说三遍", M_SpeakFileName = "talk_24.mp3", W_SpeakFileName = "talk_24.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 125, GameName = "杭麻双扣", order = 18, SpeakText = "不作死就不会死", M_SpeakFileName = "talk_25.mp3", W_SpeakFileName = "talk_25.mp3", listIndex = 1 	},
		{ ConfID = 1021, index = 128, GameName = "杭麻双扣", order = 21, SpeakText = "你们城里人真会玩", M_SpeakFileName = "talk_28.mp3", W_SpeakFileName = "talk_28.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 129, GameName = "杭麻双扣", order = 22, SpeakText = "we are 伐木累，好牌友一被子", M_SpeakFileName = "talk_29.mp3", W_SpeakFileName = "talk_29.mp3", listIndex = 1 	},
		{ ConfID = 1023, index = 130, GameName = "杭麻双扣", order = 23, SpeakText = "NND，容我喝一杯82年的龙井", M_SpeakFileName = "talk_30.mp3", W_SpeakFileName = "talk_30.mp3", listIndex = 1 	},
		{ ConfID = 1025, index = 132, GameName = "杭麻双扣", order = 25, SpeakText = "duang~", M_SpeakFileName = "talk_32.mp3", W_SpeakFileName = "talk_32.mp3", listIndex = 1 	},
		{ ConfID = 1026, index = 133, GameName = "杭麻双扣", order = 26, SpeakText = "666", M_SpeakFileName = "talk_33.mp3", W_SpeakFileName = "talk_33.mp3", listIndex = 1 	},
		{ ConfID = 1027, index = 134, GameName = "杭麻双扣", order = 27, SpeakText = "还有谁！！！", M_SpeakFileName = "talk_34.mp3", W_SpeakFileName = "talk_34.mp3", listIndex = 1 	},
		{ ConfID = 1028, index = 135, GameName = "杭麻双扣", order = 28, SpeakText = "what are you 弄啥嘞", M_SpeakFileName = "talk_35.mp3", W_SpeakFileName = "talk_35.mp3", listIndex = 1 	},
		{ ConfID = 1029, index = 137, GameName = "杭麻双扣", order = 29, SpeakText = "人要赢得起，也要输得起", M_SpeakFileName = "talk_37.mp3", W_SpeakFileName = "talk_37.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tabW