-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "浙中连连看", order = 1, SpeakText = "很高兴见到各位", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "浙中连连看", order = 2, SpeakText = "快一点", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "浙中连连看", order = 3, SpeakText = "慢工出细活", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "浙中连连看", order = 4, SpeakText = "老是被打枪", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "浙中连连看", order = 5, SpeakText = "这牌太烂了", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "浙中连连看", order = 6, SpeakText = "牌超好", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "浙中连连看", order = 7, SpeakText = "请我们吃夜宵吧", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "浙中连连看", order = 8, SpeakText = "今天真倒霉", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 109, GameName = "浙中连连看", order = 9, SpeakText = "给我来点好牌吧", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 110, GameName = "浙中连连看", order = 10, SpeakText = "给你来一枪", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "浙中连连看", order = 11, SpeakText = "你的牌运太好了", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 112, GameName = "浙中连连看", order = 12, SpeakText = "有事先离开", M_SpeakFileName = "M_Speak112.mp3", W_SpeakFileName = "W_Speak112.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 113, GameName = "浙中连连看", order = 13, SpeakText = "太爽了", M_SpeakFileName = "M_Speak113.mp3", W_SpeakFileName = "W_Speak113.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 114, GameName = "浙中连连看", order = 14, SpeakText = "没时间玩了", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab�