-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 1, GameName = "连连看", order = 1, SpeakText = "很高兴见到各位", M_SpeakFileName = "M_Speak1.mp3", W_SpeakFileName = "W_Speak1.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 2, GameName = "连连看", order = 2, SpeakText = "快一点", M_SpeakFileName = "M_Speak2.mp3", W_SpeakFileName = "W_Speak2.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 3, GameName = "连连看", order = 3, SpeakText = "慢工出细活", M_SpeakFileName = "M_Speak3.mp3", W_SpeakFileName = "W_Speak3.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 4, GameName = "连连看", order = 4, SpeakText = "老是被打枪", M_SpeakFileName = "M_Speak4.mp3", W_SpeakFileName = "W_Speak4.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 5, GameName = "连连看", order = 5, SpeakText = "这牌太烂了", M_SpeakFileName = "M_Speak5.mp3", W_SpeakFileName = "W_Speak5.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 6, GameName = "连连看", order = 6, SpeakText = "牌超好", M_SpeakFileName = "M_Speak6.mp3", W_SpeakFileName = "W_Speak6.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 7, GameName = "连连看", order = 7, SpeakText = "请我们吃夜宵吧", M_SpeakFileName = "M_Speak7.mp3", W_SpeakFileName = "W_Speak7.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 8, GameName = "连连看", order = 8, SpeakText = "今天真倒霉", M_SpeakFileName = "M_Speak8.mp3", W_SpeakFileName = "W_Speak8.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 9, GameName = "连连看", order = 9, SpeakText = "给我来点好牌吧", M_SpeakFileName = "M_Speak9.mp3", W_SpeakFileName = "W_Speak9.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 10, GameName = "连连看", order = 10, SpeakText = "给你来一枪", M_SpeakFileName = "M_Speak10.mp3", W_SpeakFileName = "W_Speak10.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 11, GameName = "连连看", order = 11, SpeakText = "你的牌运太好了", M_SpeakFileName = "M_Speak11.mp3", W_SpeakFileName = "W_Speak11.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 12, GameName = "连连看", order = 12, SpeakText = "有事先离开", M_SpeakFileName = "M_Speak12.mp3", W_SpeakFileName = "W_Speak12.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 13, GameName = "连连看", order = 13, SpeakText = "太爽了", M_SpeakFileName = "M_Speak13.mp3", W_SpeakFileName = "W_Speak13.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 14, GameName = "连连看", order = 14, SpeakText = "没时间玩了", M_SpeakFileName = "M_Speak14.mp3", W_SpeakFileName = "W_Speak14.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab: