-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 121, GameName = "瑞安双扣", order = 1, SpeakText = "人都等睡着了", M_SpeakFileName = "M_Speak121.mp3", W_SpeakFileName = "W_Speak121.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 101, GameName = "瑞安双扣", order = 2, SpeakText = "动作快点~~", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 122, GameName = "瑞安双扣", order = 3, SpeakText = "看大字报？~~", M_SpeakFileName = "M_Speak122.mp3", W_SpeakFileName = "W_Speak122.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 123, GameName = "瑞安双扣", order = 4, SpeakText = "快打快打！", M_SpeakFileName = "M_Speak123.mp3", W_SpeakFileName = "W_Speak123.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 124, GameName = "瑞安双扣", order = 5, SpeakText = "快来那", M_SpeakFileName = "M_Speak124.mp3", W_SpeakFileName = "W_Speak124.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 125, GameName = "瑞安双扣", order = 6, SpeakText = "逃哪里去", M_SpeakFileName = "M_Speak125.mp3", W_SpeakFileName = "W_Speak125.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 126, GameName = "瑞安双扣", order = 7, SpeakText = "形势看透西", M_SpeakFileName = "M_Speak126.mp3", W_SpeakFileName = "W_Speak126.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 103, GameName = "瑞安双扣", order = 8, SpeakText = "定点！别慌", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 127, GameName = "瑞安双扣", order = 9, SpeakText = "自打错了没怨", M_SpeakFileName = "M_Speak127.mp3", W_SpeakFileName = "W_Speak127.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 128, GameName = "瑞安双扣", order = 10, SpeakText = "你凶西", M_SpeakFileName = "M_Speak128.mp3", W_SpeakFileName = "W_Speak128.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "瑞安双扣", order = 11, SpeakText = "一世痛苦", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 131, GameName = "瑞安双扣", order = 12, SpeakText = "牌像中石油", M_SpeakFileName = "M_Speak131.mp3", W_SpeakFileName = "W_Speak131.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 114, GameName = "瑞安双扣", order = 13, SpeakText = "南斯拉夫", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 132, GameName = "瑞安双扣", order = 14, SpeakText = "没味儿", M_SpeakFileName = "M_Speak132.mp3", W_SpeakFileName = "W_Speak132.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 117, GameName = "瑞安双扣", order = 15, SpeakText = "强生针", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 133, GameName = "瑞安双扣", order = 16, SpeakText = "关公面前舞大刀", M_SpeakFileName = "M_Speak133.mp3", W_SpeakFileName = "W_Speak133.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 118, GameName = "瑞安双扣", order = 17, SpeakText = "哈哈，偷机", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 134, GameName = "瑞安双扣", order = 18, SpeakText = "糖金杏捣裂", M_SpeakFileName = "M_Speak134.mp3", W_SpeakFileName = "W_Speak134.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 135, GameName = "瑞安双扣", order = 19, SpeakText = "人毛嫌刀钝", M_SpeakFileName = "M_Speak135.mp3", W_SpeakFileName = "W_Speak135.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 136, GameName = "瑞安双扣", order = 20, SpeakText = "赖歪肉吃不壮", M_SpeakFileName = "M_Speak136.mp3", W_SpeakFileName = "W_Speak136.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab