-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "浙中双扣", order = 1, SpeakText = "我等的花都谢了", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "浙中双扣", order = 2, SpeakText = "急什么，让我想想", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "浙中双扣", order = 3, SpeakText = "和你合作真是太愉快啦", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "浙中双扣", order = 4, SpeakText = "天下还有这样的烂牌", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "浙中双扣", order = 5, SpeakText = "好牌！好牌！", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 109, GameName = "浙中双扣", order = 6, SpeakText = "炸弹带回家？", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 110, GameName = "浙中双扣", order = 7, SpeakText = "我手牌太差，你自己先走", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 111, GameName = "浙中双扣", order = 8, SpeakText = "我已经稳坐钓鱼台", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 115, GameName = "浙中双扣", order = 9, SpeakText = "生活不止眼前", M_SpeakFileName = "M_Speak115.mp3", W_SpeakFileName = "W_Speak115.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 116, GameName = "浙中双扣", order = 10, SpeakText = "安静地做美男子(宝宝)", M_SpeakFileName = "M_Speak116.mp3", W_SpeakFileName = "W_Speak116.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 117, GameName = "浙中双扣", order = 11, SpeakText = "好好打牌，表说话", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 118, GameName = "浙中双扣", order = 12, SpeakText = "BOSS带我装B带我飞", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 119, GameName = "浙中双扣", order = 13, SpeakText = "牌友诚可贵，且打且珍惜", M_SpeakFileName = "M_Speak119.mp3", W_SpeakFileName = "W_Speak119.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 120, GameName = "浙中双扣", order = 14, SpeakText = "你这么打牌，我也是醉了", M_SpeakFileName = "M_Speak120.mp3", W_SpeakFileName = "W_Speak120.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 121, GameName = "浙中双扣", order = 15, SpeakText = "和你合作我也是蛮拼的", M_SpeakFileName = "M_Speak121.mp3", W_SpeakFileName = "W_Speak121.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 122, GameName = "浙中双扣", order = 16, SpeakText = "这么厉害，你妈妈知道吗", M_SpeakFileName = "M_Speak122.mp3", W_SpeakFileName = "W_Speak122.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 123, GameName = "浙中双扣", order = 17, SpeakText = "这手牌，我是崩溃了", M_SpeakFileName = "M_Speak123.mp3", W_SpeakFileName = "W_Speak123.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 124, GameName = "浙中双扣", order = 18, SpeakText = "快出！快出！快出！", M_SpeakFileName = "M_Speak124.mp3", W_SpeakFileName = "W_Speak124.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 125, GameName = "浙中双扣", order = 19, SpeakText = "不作死就不会死", M_SpeakFileName = "M_Speak125.mp3", W_SpeakFileName = "W_Speak125.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 128, GameName = "浙中双扣", order = 22, SpeakText = "你们城里人真会玩", M_SpeakFileName = "M_Speak128.mp3", W_SpeakFileName = "W_Speak128.mp3", listIndex = 1 	},
		{ ConfID = 1023, index = 129, GameName = "浙中双扣", order = 23, SpeakText = "we are 伐木累", M_SpeakFileName = "M_Speak129.mp3", W_SpeakFileName = "W_Speak129.mp3", listIndex = 1 	},
		{ ConfID = 1024, index = 130, GameName = "浙中双扣", order = 24, SpeakText = "NND，容我喝杯茶压压惊", M_SpeakFileName = "M_Speak130.mp3", W_SpeakFileName = "W_Speak130.mp3", listIndex = 1 	},
		{ ConfID = 1026, index = 132, GameName = "浙中双扣", order = 26, SpeakText = "duang~", M_SpeakFileName = "M_Speak132.mp3", W_SpeakFileName = "W_Speak132.mp3", listIndex = 1 	},
		{ ConfID = 1027, index = 133, GameName = "浙中双扣", order = 27, SpeakText = "666", M_SpeakFileName = "M_Speak133.mp3", W_SpeakFileName = "W_Speak133.mp3", listIndex = 1 	},
		{ ConfID = 1028, index = 134, GameName = "浙中双扣", order = 28, SpeakText = "还有谁！！！", M_SpeakFileName = "M_Speak134.mp3", W_SpeakFileName = "W_Speak134.mp3", listIndex = 1 	},
		{ ConfID = 1029, index = 135, GameName = "浙中双扣", order = 29, SpeakText = "what are you 弄啥嘞", M_SpeakFileName = "M_Speak135.mp3", W_SpeakFileName = "W_Speak135.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab