package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.m.k;
import java.util.HashMap;
import java.util.Map;

public final class ex {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aou;

    static {
        HashMap map = new HashMap();
        aou = map;
        map.put(AdInfo.AdAggregateInfo.class, new h());
        aou.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new he());
        aou.put(AdInfo.SmallAppJumpInfo.class, new hs());
        aou.put(AdMatrixInfo.CycleAggregateInfo.class, new cf());
        aou.put(PhotoInfo.class, new gj());
        aou.put(AdInfo.AdvertiserInfo.class, new am());
        aou.put(AdStyleInfo.AdBrowseInfo.class, new k());
        aou.put(WebViewLoadMsg.class, new jm());
        aou.put(AdMatrixInfo.AggregationCardInfo.class, new an());
        aou.put(AdProductInfo.SpikeInfo.class, new ht());
        aou.put(com.kwad.sdk.core.request.model.b.class, new cl());
        aou.put(StatusInfo.SplashAdInfo.class, new hv());
        aou.put(StatusInfo.class, new ij());
        aou.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new gi());
        aou.put(HybridLoadMsg.class, new ed());
        aou.put(com.kwad.sdk.internal.api.b.class, new hx());
        aou.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new cu());
        aou.put(AdInfo.H5Config.class, new dw());
        aou.put(AdMatrixInfo.InterstitialCardInfo.class, new ep());
        aou.put(AdMatrixInfo.MatrixTemplate.class, new fk());
        aou.put(FeedSlideConf.class, new de());
        aou.put(TemplateConfig.class, new ir());
        aou.put(AdInfo.AdFeedInfo.class, new o());
        aou.put(VideoPlayerStatus.class, new jg());
        aou.put(AdInfo.AdPreloadInfo.class, new aa());
        aou.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new al());
        aou.put(com.kwad.sdk.internal.api.a.class, new u());
        aou.put(AdInfo.ComplianceInfo.class, new br());
        aou.put(AdInfo.AdTrackInfo.class, new aj());
        aou.put(HttpDnsInfo.IpInfo.class, new es());
        aou.put(AdStyleInfo.FeedAdInfo.class, new db());
        aou.put(com.kwad.sdk.core.network.k.class, new fw());
        aou.put(AdMatrixInfo.RotateInfo.class, new hh());
        aou.put(AdMatrixInfo.MatrixTag.class, new fj());
        aou.put(AdMatrixInfo.SplashInfo.class, new hy());
        aou.put(com.kwad.sdk.h.a.b.class, new gc());
        aou.put(AdInfo.AdMaterialInfo.class, new y());
        aou.put(com.kwad.sdk.utils.b.a.class, new fa());
        aou.put(AdMatrixInfo.BaseMatrixTemplate.class, new bb());
        aou.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new ci());
        aou.put(k.a.class, new jo());
        aou.put(AdInfo.PlayableStyleInfo.class, new gq());
        aou.put(AdStyleInfo.ExposeTagInfo.class, new cx());
        aou.put(AdMatrixInfo.AdInteractionInfo.class, new t());
        aou.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new fh());
        aou.put(TKAdLiveShopItemInfo.class, new in());
        aou.put(AdInfo.AdBaseInfo.class, new i());
        aou.put(AdInfo.AdInsertScreenInfo.class, new s());
        aou.put(NativeAdExtraDataImpl.class, new fo());
        aou.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new gh());
        aou.put(com.kwad.sdk.core.network.j.class, new fv());
        aou.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new fc());
        aou.put(SDKInitMsg.class, new hi());
        aou.put(AdMatrixInfo.class, new z());
        aou.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aou.put(AdInfo.CallBackStrategyInfo.class, new bh());
        aou.put(k.a.a.class, new ig());
        aou.put(AdStyleInfo.class, new ah());
        aou.put(HttpDnsInfo.class, new ec());
        aou.put(AdInfo.AdShowVideoH5Info.class, new ad());
        aou.put(AdMatrixInfo.SplashSlideInfo.class, new id());
        aou.put(AdMatrixInfo.EndCardInfo.class, new ct());
        aou.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new ck());
        aou.put(AdMatrixInfo.PreLandingPageTKInfo.class, new gs());
        aou.put(AdInfo.FullScreenVideoInfo.class, new dn());
        aou.put(AdInfo.NativeAdInfo.class, new fp());
        aou.put(AdInfo.CutRuleInfo.class, new ce());
        aou.put(AdMatrixInfo.SplashEndCardTKInfo.class, new hw());
        aou.put(AdStyleInfo.PlayDetailInfo.class, new gk());
        aou.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new cr());
        aou.put(AdInfo.MaterialSize.class, new fi());
        aou.put(AdMatrixInfo.StyleInfo.class, new il());
        aou.put(WebViewCommercialMsg.class, new jl());
        aou.put(StatusInfo.NativeAdStyleControl.class, new fs());
        aou.put(AdMatrixInfo.AdDataV2.class, new n());
        aou.put(AdInfo.AdRewardInfo.class, new ac());
        aou.put(AdStyleInfo.PlayEndInfo.class, new gm());
        aou.put(AdMatrixInfo.ShakeInfo.class, new hm());
        aou.put(URLPackage.class, new iy());
        aou.put(StatusInfo.NativeAdRequestInfo.class, new fq());
        aou.put(AdMatrixInfo.FullScreenInfo.class, new dm());
        aou.put(PageInfo.class, new ge());
        aou.put(SceneImpl.class, new hl());
        aou.put(AdInfo.UnDownloadConf.class, new iz());
        aou.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new ch());
        aou.put(AdInfo.AdConversionInfo.class, new l());
        aou.put(CouponInfo.class, new cb());
        aou.put(AdProductInfo.class, new ab());
        aou.put(com.kwad.sdk.core.threads.d.class, new iv());
        aou.put(AdMatrixInfo.FeedInfo.class, new dc());
        aou.put(AdTemplate.class, new ai());
        aou.put(AdInfo.AdStyleConfInfo.class, new ag());
        aou.put(AdMatrixInfo.RewardVideoInteractInfo.class, new hc());
        aou.put(AdInfo.NativeAdShakeInfo.class, new fr());
        aou.put(AdMatrixInfo.DownloadTexts.class, new cq());
        aou.put(ABParams.class, new a());
        aou.put(com.kwad.sdk.core.report.m.class, new cv());
        aou.put(AdMatrixInfo.InstalledActivateInfo.class, new em());
        aou.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new fl());
        aou.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new jn());
        aou.put(AdInfo.AdSplashInfo.class, new ae());
        aou.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aou.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new cj());
        aou.put(ImageLoaderInfo.class, new eg());
        aou.put(AdInfo.class, new r());
        aou.put(AdMatrixInfo.TemplateData.class, new it());
        aou.put(AdStatusInfo.class, new af());
        aou.put(com.kwad.sdk.h.a.a.class, new gb());
        aou.put(StatusInfo.SplashStyleControl.class, new ie());
        aou.put(AdMatrixInfo.SplashActionBarInfo.class, new hu());
        aou.put(AdStyleInfo.ExtraDisplayInfo.class, new cz());
        aou.put(PhotoInfo.BaseInfo.class, new ba());
        aou.put(AdMatrixInfo.BottomBannerInfo.class, new bf());
        aou.put(AdInfo.DownloadSafeInfo.class, new co());
        aou.put(AdMatrixInfo.Styles.class, new im());
        aou.put(WebCloseStatus.class, new jk());
        aou.put(com.kwad.sdk.core.request.model.f.class, new ip());
        aou.put(AdMatrixInfo.RotateDegreeInfo.class, new hg());
        aou.put(AdInfo.UnDownloadRegionConf.class, new ja());
        aou.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aou.put(AdMatrixInfo.RewardVideoTaskInfo.class, new hd());
        aou.put(AdMatrixInfo.NeoVideoInfo.class, new fu());
        aou.put(PhotoInfo.VideoInfo.class, new je());
        aou.put(com.kwad.sdk.core.threads.b.class, new iu());
        AQ();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void AQ() {
        bs.AQ();
        bt.AQ();
        bu.AQ();
        bv.AQ();
        bw.AQ();
        bx.AQ();
        by.AQ();
        bz.AQ();
        dg.AQ();
        dh.AQ();
        di.AQ();
        dj.AQ();
        dk.AQ();
        dl.AQ();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> AR() {
        return aou;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aou.get(cls);
    }
}
