
void FUN_0132a994(long param_1,Node *param_2)

{
  CommonOperatorBuilder *this;
  Operator *pOVar1;
  Node *pNVar2;
  Operator *pOVar3;
  Node *pNVar4;
  Node *pNVar5;
  Node *pNVar6;
  undefined8 uVar7;
  undefined8 *puVar8;
  Node *pNVar9;
  MachineOperatorBuilder *pMVar10;
  Graph *pGVar11;
  Graph *pGVar12;
  undefined8 uVar13;
  undefined8 uVar14;
  Node *local_78;
  Node *pNStack_70;
  undefined8 local_68;
  
  puVar8 = *(undefined8 **)(param_1 + 8);
  this = (CommonOperatorBuilder *)puVar8[1];
  pMVar10 = (MachineOperatorBuilder *)puVar8[2];
  pGVar11 = (Graph *)*puVar8;
  pNVar9 = (Node *)**(undefined8 **)(param_1 + 0x20);
  uVar14 = **(undefined8 **)(param_1 + 0x18);
  pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::RoundFloat64ToInt32(pMVar10);
  local_78 = param_2;
  pNVar2 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::Float64Equal(pMVar10);
  pGVar12 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar3 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToFloat64(pMVar10)
  ;
  local_78 = pNVar2;
  pNStack_70 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar12,pOVar3,1,&local_78,false);
  local_78 = param_2;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Branch(this,0,1);
  local_78 = pNVar4;
  pNStack_70 = (Node *)uVar14;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfTrue(this);
  local_78 = pNVar4;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfFalse(this);
  local_78 = pNVar4;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::Word32Equal(pMVar10);
  pNStack_70 = (Node *)v8::internal::compiler::MachineGraph::Int32Constant
                                 (*(MachineGraph **)(param_1 + 8),0);
  local_78 = pNVar2;
  pNVar5 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Branch(this,2,1);
  local_78 = pNVar5;
  pNStack_70 = (Node *)uVar14;
  pNVar5 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfTrue(this);
  local_78 = pNVar5;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfFalse(this);
  local_78 = pNVar5;
  pNVar5 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(pMVar10);
  pGVar12 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar3 = (Operator *)
           v8::internal::compiler::MachineOperatorBuilder::Float64ExtractHighWord32(pMVar10);
  local_78 = param_2;
  pNVar6 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar12,pOVar3,1,&local_78,false);
  pNStack_70 = (Node *)v8::internal::compiler::MachineGraph::Int32Constant
                                 (*(MachineGraph **)(param_1 + 8),0);
  local_78 = pNVar6;
  pNVar6 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Branch(this,2,1);
  local_78 = pNVar6;
  pNStack_70 = (Node *)uVar14;
  pNVar6 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfTrue(this);
  local_78 = pNVar6;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfFalse(this);
  local_78 = pNVar6;
  uVar7 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Merge(this,2);
  local_78 = pNVar5;
  pNStack_70 = (Node *)uVar7;
  uVar7 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Merge(this,2);
  local_78 = pNVar4;
  pNStack_70 = (Node *)uVar14;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::Int32AddWithOverflow(pMVar10)
  ;
  local_78 = pNVar2;
  pNStack_70 = pNVar2;
  local_68 = uVar7;
  pNVar2 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,3,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Projection(this,1);
  local_78 = pNVar2;
  pNStack_70 = (Node *)uVar7;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Branch(this,2,1);
  local_78 = pNVar4;
  pNStack_70 = (Node *)uVar7;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfTrue(this);
  local_78 = pNVar4;
  pNVar5 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Merge(this,2);
  local_78 = pNVar5;
  pNStack_70 = (Node *)uVar14;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::IfFalse(this);
  local_78 = pNVar4;
  pNVar4 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Projection(this,0);
  local_78 = pNVar2;
  pNStack_70 = pNVar4;
  pNVar2 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  pMVar10 = (MachineOperatorBuilder *)(*(undefined8 **)(param_1 + 8))[2];
  if (pMVar10[0x10] == (MachineOperatorBuilder)0x5) {
    pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
    pOVar1 = (Operator *)v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToInt64(pMVar10)
    ;
    local_78 = pNVar2;
    pNVar2 = (Node *)v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,1,&local_78,false);
  }
  uVar7 = FUN_0132afe4(param_1,param_2,uVar14);
  uVar13 = **(undefined8 **)(param_1 + 0x20);
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Merge(this,2);
  local_78 = pNVar4;
  pNStack_70 = (Node *)uVar14;
  uVar14 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,2,&local_78,false);
  **(undefined8 **)(param_1 + 0x18) = uVar14;
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::EffectPhi(this,2);
  local_78 = pNVar9;
  pNStack_70 = (Node *)uVar13;
  local_68 = uVar14;
  uVar13 = v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,3,&local_78,false);
  **(undefined8 **)(param_1 + 0x20) = uVar13;
  pGVar11 = (Graph *)**(undefined8 **)(param_1 + 8);
  pOVar1 = (Operator *)v8::internal::compiler::CommonOperatorBuilder::Phi(this,8,2);
  local_78 = pNVar2;
  pNStack_70 = (Node *)uVar7;
  local_68 = uVar14;
  v8::internal::compiler::Graph::NewNode(pGVar11,pOVar1,3,&local_78,false);
  return;
}

