
void FUN_00a1d7cc(long param_1,int param_2)

{
  long *plVar1;
  char *pcVar2;
  char *pcVar3;
  char *pcVar4;
  char *pcVar5;
  char *pcVar6;
  bool bVar7;
  int iVar8;
  time_t tVar9;
  code *__s;
  long lVar10;
  char *pcVar11;
  char *pcVar12;
  char *pcVar13;
  long *plVar14;
  long *plVar16;
  long *plVar17;
  long *plVar15;
  
  if (*(long *)(param_1 + 0x698) == 0) {
    if ((param_2 != 0) && (*(long *)(param_1 + 0x928) != 0)) {
      FUN_00a16c3c();
      *(undefined8 *)(param_1 + 0x928) = 0;
    }
    FUN_00a3557c(param_1,2,2);
  }
  else {
    if (*(long *)(param_1 + 0x928) != 0) {
                    /* try { // try from 00a1d808 to 00b1d80f has its CatchHandler @ 00a1d9b8 */
      FUN_00a1b940(param_1);
    }
                    /* try { // try from 00a1d810 to 00b1d88f has its CatchHandler @ 00a1d768 */
    FUN_00a3557c(param_1,2,2);
    plVar16 = *(long **)(param_1 + 0x938);
    if ((plVar16 != (long *)0x0) && (plVar16[3] != 0)) {
      pcVar13 = *(char **)(param_1 + 0x698);
      tVar9 = time((time_t *)0x0);
      if ((long *)*plVar16 != (long *)0x0) {
        plVar17 = (long *)*plVar16;
        plVar14 = (long *)0x0;
        do {
          while( true ) {
            plVar15 = plVar17;
            plVar17 = (long *)*plVar15;
            if ((plVar15[6] == 0) || (tVar9 <= plVar15[6])) break;
            plVar1 = plVar16;
            if (plVar15 != (long *)*plVar16) {
              plVar1 = plVar14;
            }
            *plVar1 = (long)plVar17;
            plVar16[3] = plVar16[3] + -1;
                    /* try { // try from 00a1d890 to 00b1d897 has its CatchHandler @ 00a1d9a8 */
            (*(code *)PTR_free_01d1b748)(plVar15[7]);
                    /* try { // try from 00a1d898 to 00b1d8bb has its CatchHandler @ 00a1d768 */
            (*(code *)PTR_free_01d1b748)(plVar15[5]);
            (*(code *)PTR_free_01d1b748)(plVar15[3]);
            (*(code *)PTR_free_01d1b748)(plVar15[4]);
                    /* try { // try from 00a1d8bc to 00b1d8cf has its CatchHandler @ 00a1da08 */
            (*(code *)PTR_free_01d1b748)(plVar15[1]);
            (*(code *)PTR_free_01d1b748)(plVar15[2]);
            (*(code *)PTR_free_01d1b748)(plVar15[10]);
            (*(code *)PTR_free_01d1b748)(plVar15[9]);
                    /* try { // try from 00a1d8ec to 00b1d8f3 has its CatchHandler @ 00a1d9c8 */
            (*(code *)PTR_free_01d1b748)(plVar15);
                    /* try { // try from 00a1d8f4 to 00b1d997 has its CatchHandler @ 00a1d768 */
            if (plVar17 == (long *)0x0) goto LAB_00a1d904;
          }
          plVar14 = plVar15;
        } while (plVar17 != (long *)0x0);
      }
LAB_00a1d904:
      iVar8 = strcmp("-",pcVar13);
      if (iVar8 == 0) {
        __s = waitpid;
        bVar7 = true;
      }
      else {
        __s = (code *)fopen(pcVar13,"w");
        if ((FILE *)__s == (FILE *)0x0) {
LAB_00a1dab4:
          FUN_00a22d58(param_1,"WARNING: failed to save cookies in %s\n",
                       *(undefined8 *)(param_1 + 0x698));
          goto joined_r0x00a1d95c;
        }
        bVar7 = false;
      }
      fwrite("# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n"
             ,0x88,1,(FILE *)__s);
      plVar16 = (long *)*plVar16;
                    /* try { // try from 00a1d998 to 00b1d99f has its CatchHandler @ 00a1d9b8 */
      if (plVar16 != (long *)0x0) {
                    /* try { // try from 00a1d9a0 to 00b1d9a7 has its CatchHandler @ 00a1d9a8 */
                    /* catch() { ... } // from try @ 00a1d890 with catch @ 00a1d9a8
                       catch() { ... } // from try @ 00a1d9a0 with catch @ 00a1d9a8
                       try { // try from 00a1d9a8 to 00b1da43 has its CatchHandler @ 00a1d768 */
        pcVar13 = "";
                    /* catch() { ... } // from try @ 00a1d808 with catch @ 00a1d9b8
                       catch() { ... } // from try @ 00a1d998 with catch @ 00a1d9b8 */
                    /* catch() { ... } // from try @ 00a1d8ec with catch @ 00a1d9c8 */
        do {
          pcVar12 = (char *)plVar16[5];
          if (pcVar12 != (char *)0x0) {
            pcVar2 = "#HttpOnly_";
            if (*(char *)((long)plVar16 + 0x5a) == '\0') {
              pcVar2 = pcVar13;
            }
            pcVar11 = pcVar13;
            if (((char)plVar16[8] != '\0') && (pcVar11 = ".", *pcVar12 == '.')) {
              pcVar11 = pcVar13;
            }
            pcVar3 = "TRUE";
            if ((char)plVar16[8] == '\0') {
              pcVar3 = "FALSE";
            }
            pcVar4 = "/";
            if ((char *)plVar16[3] != (char *)0x0) {
              pcVar4 = (char *)plVar16[3];
            }
            pcVar5 = "TRUE";
            if ((char)plVar16[0xb] == '\0') {
              pcVar5 = "FALSE";
            }
            pcVar6 = pcVar13;
            if ((char *)plVar16[2] != (char *)0x0) {
              pcVar6 = (char *)plVar16[2];
            }
            lVar10 = FUN_00a0e870("%s%s%s\t%s\t%s\t%s\t%ld\t%s\t%s",pcVar2,pcVar11,pcVar12,pcVar3,
                                  pcVar4,pcVar5,plVar16[6],plVar16[1],pcVar6);
            if (lVar10 == 0) {
              FUN_00a0ec44(__s,"#\n# Fatal libcurl error\n");
                    /* try { // try from 00a1daa8 to 00b1daab has its CatchHandler @ 00a1dad4 */
              if (!bVar7) {
                    /* try { // try from 00a1daac to 00b1daef has its CatchHandler @ 00a1da80 */
                fclose((FILE *)__s);
              }
              goto LAB_00a1dab4;
            }
            FUN_00a0ec44(__s,"%s\n",lVar10);
            (*(code *)PTR_free_01d1b748)(lVar10);
          }
          plVar16 = (long *)*plVar16;
        } while (plVar16 != (long *)0x0);
      }
                    /* catch(type#1 @ 00000000) { ... } // from try @ 00a1daac with catch @ 00a1da80
                        */
      if (!bVar7) {
        fclose((FILE *)__s);
      }
    }
  }
joined_r0x00a1d95c:
  if (param_2 != 0) {
    plVar16 = *(long **)(param_1 + 0x938);
                    /* catch(type#1 @ 00000000) { ... } // from try @ 00a1daa8 with catch @ 00a1dad4
                        */
    if (((*(long *)(param_1 + 0x70) == 0) ||
        (plVar16 != *(long **)(*(long *)(param_1 + 0x70) + 0x50))) && (plVar16 != (long *)0x0)) {
      (*(code *)PTR_free_01d1b748)(plVar16[1]);
      plVar17 = (long *)*plVar16;
      while (plVar17 != (long *)0x0) {
        lVar10 = *plVar17;
                    /* catch(type#1 @ 00000000) { ... } // from try @ 00a1db3c with catch @ 00a1db10
                        */
        (*(code *)PTR_free_01d1b748)(plVar17[7]);
        (*(code *)PTR_free_01d1b748)(plVar17[5]);
        (*(code *)PTR_free_01d1b748)(plVar17[3]);
        (*(code *)PTR_free_01d1b748)(plVar17[4]);
                    /* try { // try from 00a1db38 to 00b1db3b has its CatchHandler @ 00a1db6c */
                    /* try { // try from 00a1db3c to 00b1db87 has its CatchHandler @ 00a1db10 */
        (*(code *)PTR_free_01d1b748)(plVar17[1]);
        (*(code *)PTR_free_01d1b748)(plVar17[2]);
        (*(code *)PTR_free_01d1b748)(plVar17[10]);
        (*(code *)PTR_free_01d1b748)(plVar17[9]);
                    /* catch(type#1 @ 00000000) { ... } // from try @ 00a1db38 with catch @ 00a1db6c
                        */
        (*(code *)PTR_free_01d1b748)(plVar17);
        plVar17 = (long *)lVar10;
      }
      (*(code *)PTR_free_01d1b748)(plVar16);
    }
  }
  FUN_00a355d4(param_1,2);
  return;
}

