
/* v8::internal::ObjectStats::PrintJSON(char const*) */

void __thiscall v8::internal::ObjectStats::PrintJSON(ObjectStats *this,char *param_1)

{
  uint uVar1;
  long lVar2;
  double dVar3;
  double dVar4;
  
  lVar2 = *(long *)this;
  dVar3 = (double)Heap::MonotonicallyIncreasingTimeInMs();
  dVar4 = *(double *)(lVar2 + 0x2e70);
  uVar1 = *(uint *)(*(long *)this + 0x1b4);
  PrintF("{ ");
  PrintF("\"isolate\": \"%p\", \"id\": %d, \"key\": \"%s\", ",*(long *)this + -0x8850,(ulong)uVar1,
         param_1);
  PrintF("\"type\": \"gc_descriptor\", \"time\": %f }\n",dVar3 - dVar4);
  PrintF("{ ");
  PrintF("\"isolate\": \"%p\", \"id\": %d, \"key\": \"%s\", ",*(long *)this + -0x8850,(ulong)uVar1,
         param_1);
  PrintF("\"type\": \"field_data\"");
  PrintF(", \"tagged_fields\": %zu",*(long *)(this + 0x53e70) << 2);
  PrintF(", \"embedder_fields\": %zu",*(long *)(this + 0x53e78) << 3);
  PrintF(", \"inobject_smi_fields\": %zu",*(long *)(this + 0x53e80) << 2);
  PrintF(", \"unboxed_double_fields\": %zu",*(long *)(this + 0x53e88) << 3);
  PrintF(", \"boxed_double_fields\": %zu",*(long *)(this + 0x53e90) << 3);
  PrintF(", \"string_data\": %zu",*(long *)(this + 0x53e98) << 2);
  PrintF(", \"other_raw_fields\": %zu",*(long *)(this + 0x53ea0) << 3);
  PrintF(" }\n");
  PrintF("{ ");
  PrintF("\"isolate\": \"%p\", \"id\": %d, \"key\": \"%s\", ",*(long *)this + -0x8850,(ulong)uVar1,
         param_1);
  PrintF("\"type\": \"bucket_sizes\", \"sizes\": [ ");
  PrintF("%d",0x20);
  PrintF(", ");
  PrintF("%d",0x40);
  PrintF(", ");
  PrintF("%d",0x80);
  PrintF(", ");
  PrintF("%d",0x100);
  PrintF(", ");
  PrintF("%d",0x200);
  PrintF(", ");
  PrintF("%d",0x400);
  PrintF(", ");
  PrintF("%d",0x800);
  PrintF(", ");
  PrintF("%d",0x1000);
  PrintF(", ");
  PrintF("%d",0x2000);
  PrintF(", ");
  PrintF("%d",0x4000);
  PrintF(", ");
  PrintF("%d",0x8000);
  PrintF(", ");
  PrintF("%d",0x10000);
  PrintF(", ");
  PrintF("%d",0x20000);
  PrintF(", ");
  PrintF("%d",0x40000);
  PrintF(", ");
  PrintF("%d",0x80000);
  PrintF(", ");
  PrintF("%d",0x100000);
  PrintF(" ] }\n");
  PrintInstanceTypeJSON(this,param_1,uVar1,"INTERNALIZED_STRING_TYPE",0);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EXTERNAL_INTERNALIZED_STRING_TYPE",2);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ONE_BYTE_INTERNALIZED_STRING_TYPE",8);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EXTERNAL_ONE_BYTE_INTERNALIZED_STRING_TYPE",10);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCACHED_EXTERNAL_INTERNALIZED_STRING_TYPE",0x12);
  PrintInstanceTypeJSON
            (this,param_1,uVar1,"UNCACHED_EXTERNAL_ONE_BYTE_INTERNALIZED_STRING_TYPE",0x1a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STRING_TYPE",0x20);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CONS_STRING_TYPE",0x21);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EXTERNAL_STRING_TYPE",0x22);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SLICED_STRING_TYPE",0x23);
  PrintInstanceTypeJSON(this,param_1,uVar1,"THIN_STRING_TYPE",0x25);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ONE_BYTE_STRING_TYPE",0x28);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CONS_ONE_BYTE_STRING_TYPE",0x29);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EXTERNAL_ONE_BYTE_STRING_TYPE",0x2a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SLICED_ONE_BYTE_STRING_TYPE",0x2b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"THIN_ONE_BYTE_STRING_TYPE",0x2d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCACHED_EXTERNAL_STRING_TYPE",0x32);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE",0x3a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SYMBOL_TYPE",0x40);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BIG_INT_BASE_TYPE",0x41);
  PrintInstanceTypeJSON(this,param_1,uVar1,"HEAP_NUMBER_TYPE",0x42);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ODDBALL_TYPE",0x43);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SOURCE_TEXT_MODULE_TYPE",0x44);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SYNTHETIC_MODULE_TYPE",0x45);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FOREIGN_TYPE",0x46);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROMISE_FULFILL_REACTION_JOB_TASK_TYPE",0x47);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROMISE_REJECT_REACTION_JOB_TASK_TYPE",0x48);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CALLABLE_TASK_TYPE",0x49);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CALLBACK_TASK_TYPE",0x4a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROMISE_RESOLVE_THENABLE_JOB_TASK_TYPE",0x4b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"LOAD_HANDLER_TYPE",0x4c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STORE_HANDLER_TYPE",0x4d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FUNCTION_TEMPLATE_INFO_TYPE",0x4e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_TEMPLATE_INFO_TYPE",0x4f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ACCESS_CHECK_INFO_TYPE",0x50);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ACCESSOR_INFO_TYPE",0x51);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ACCESSOR_PAIR_TYPE",0x52);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ALIASED_ARGUMENTS_ENTRY_TYPE",0x53);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ALLOCATION_MEMENTO_TYPE",0x54);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ALLOCATION_SITE_TYPE",0x55);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ARRAY_BOILERPLATE_DESCRIPTION_TYPE",0x56);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ASM_WASM_DATA_TYPE",0x57);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ASYNC_GENERATOR_REQUEST_TYPE",0x58);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CALL_HANDLER_INFO_TYPE",0x59);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CLASS_POSITIONS_TYPE",0x5a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DEBUG_INFO_TYPE",0x5b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ENUM_CACHE_TYPE",0x5c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_CELL_TYPE",0x5d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FUNCTION_TEMPLATE_RARE_DATA_TYPE",0x5e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"INTERCEPTOR_INFO_TYPE",0x5f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"INTERNAL_CLASS_TYPE",0x60);
  PrintInstanceTypeJSON(this,param_1,uVar1,"INTERPRETER_DATA_TYPE",0x61);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROMISE_CAPABILITY_TYPE",0x62);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROMISE_REACTION_TYPE",99);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROTOTYPE_INFO_TYPE",100);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_TYPE",0x65);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SMI_BOX_TYPE",0x66);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SMI_PAIR_TYPE",0x67);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SORT_STATE_TYPE",0x68);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SOURCE_POSITION_TABLE_WITH_FRAME_CACHE_TYPE",0x69);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SOURCE_TEXT_MODULE_INFO_ENTRY_TYPE",0x6a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STACK_FRAME_INFO_TYPE",0x6b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STACK_TRACE_FRAME_TYPE",0x6c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"TEMPLATE_OBJECT_DESCRIPTION_TYPE",0x6d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"TUPLE2_TYPE",0x6e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"TUPLE3_TYPE",0x6f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_CAPI_FUNCTION_DATA_TYPE",0x70);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_DEBUG_INFO_TYPE",0x71);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_EXCEPTION_TAG_TYPE",0x72);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_EXPORTED_FUNCTION_DATA_TYPE",0x73);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_INDIRECT_FUNCTION_TABLE_TYPE",0x74);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_JS_FUNCTION_DATA_TYPE",0x75);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FIXED_ARRAY_TYPE",0x76);
  PrintInstanceTypeJSON(this,param_1,uVar1,"HASH_TABLE_TYPE",0x77);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EPHEMERON_HASH_TABLE_TYPE",0x78);
  PrintInstanceTypeJSON(this,param_1,uVar1,"GLOBAL_DICTIONARY_TYPE",0x79);
  PrintInstanceTypeJSON(this,param_1,uVar1,"NAME_DICTIONARY_TYPE",0x7a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"NUMBER_DICTIONARY_TYPE",0x7b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ORDERED_HASH_MAP_TYPE",0x7c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ORDERED_HASH_SET_TYPE",0x7d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ORDERED_NAME_DICTIONARY_TYPE",0x7e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SIMPLE_NUMBER_DICTIONARY_TYPE",0x7f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STRING_TABLE_TYPE",0x80);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CLOSURE_FEEDBACK_CELL_ARRAY_TYPE",0x81);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_BOILERPLATE_DESCRIPTION_TYPE",0x82);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCOPE_INFO_TYPE",0x83);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_CONTEXT_TABLE_TYPE",0x84);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BYTE_ARRAY_TYPE",0x85);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BYTECODE_ARRAY_TYPE",0x86);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FIXED_DOUBLE_ARRAY_TYPE",0x87);
  PrintInstanceTypeJSON(this,param_1,uVar1,"AWAIT_CONTEXT_TYPE",0x88);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BLOCK_CONTEXT_TYPE",0x89);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CATCH_CONTEXT_TYPE",0x8a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DEBUG_EVALUATE_CONTEXT_TYPE",0x8b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EVAL_CONTEXT_TYPE",0x8c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FUNCTION_CONTEXT_TYPE",0x8d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MODULE_CONTEXT_TYPE",0x8e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"NATIVE_CONTEXT_TYPE",0x8f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_CONTEXT_TYPE",0x90);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WITH_CONTEXT_TYPE",0x91);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SMALL_ORDERED_HASH_MAP_TYPE",0x92);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SMALL_ORDERED_HASH_SET_TYPE",0x93);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SMALL_ORDERED_NAME_DICTIONARY_TYPE",0x94);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCOMPILED_DATA_WITH_PREPARSE_DATA_TYPE",0x95);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCOMPILED_DATA_WITHOUT_PREPARSE_DATA_TYPE",0x96);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WEAK_FIXED_ARRAY_TYPE",0x97);
  PrintInstanceTypeJSON(this,param_1,uVar1,"TRANSITION_ARRAY_TYPE",0x98);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CELL_TYPE",0x99);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CODE_TYPE",0x9a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"CODE_DATA_CONTAINER_TYPE",0x9b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DESCRIPTOR_ARRAY_TYPE",0x9c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EMBEDDER_DATA_ARRAY_TYPE",0x9d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_METADATA_TYPE",0x9e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_TYPE",0x9f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FILLER_TYPE",0xa0);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FREE_SPACE_TYPE",0xa1);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_TYPE",0xa2);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PREPARSE_DATA_TYPE",0xa3);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROPERTY_ARRAY_TYPE",0xa4);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROPERTY_CELL_TYPE",0xa5);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SHARED_FUNCTION_INFO_TYPE",0xa6);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WEAK_ARRAY_LIST_TYPE",0xa7);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WEAK_CELL_TYPE",0xa8);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_PROXY_TYPE",0xa9);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_OBJECT_TYPE",0x421);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_GLOBAL_OBJECT_TYPE",0xaa);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_GLOBAL_PROXY_TYPE",0xab);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MODULE_NAMESPACE_TYPE",0xac);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_SPECIAL_API_OBJECT_TYPE",0x410);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_PRIMITIVE_WRAPPER_TYPE",0x411);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MAP_KEY_ITERATOR_TYPE",0x412);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MAP_KEY_VALUE_ITERATOR_TYPE",0x413);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MAP_VALUE_ITERATOR_TYPE",0x414);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_SET_KEY_VALUE_ITERATOR_TYPE",0x415);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_SET_VALUE_ITERATOR_TYPE",0x416);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_GENERATOR_OBJECT_TYPE",0x417);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ASYNC_FUNCTION_OBJECT_TYPE",0x418);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ASYNC_GENERATOR_OBJECT_TYPE",0x419);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_DATA_VIEW_TYPE",0x41a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_TYPED_ARRAY_TYPE",0x41b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MAP_TYPE",0x41c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_SET_TYPE",0x41d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_WEAK_MAP_TYPE",0x41e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_WEAK_SET_TYPE",0x41f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_API_OBJECT_TYPE",0x420);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ARGUMENTS_OBJECT_TYPE",0x422);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ARRAY_TYPE",0x423);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ARRAY_BUFFER_TYPE",0x424);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ARRAY_ITERATOR_TYPE",0x425);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ASYNC_FROM_SYNC_ITERATOR_TYPE",0x426);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_CONTEXT_EXTENSION_OBJECT_TYPE",0x427);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_DATE_TYPE",0x428);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ERROR_TYPE",0x429);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_FINALIZATION_GROUP_TYPE",0x42a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_FINALIZATION_GROUP_CLEANUP_ITERATOR_TYPE",0x42b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_MESSAGE_OBJECT_TYPE",0x42c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_PROMISE_TYPE",0x42d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_REG_EXP_TYPE",0x42e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_REG_EXP_STRING_ITERATOR_TYPE",0x42f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_STRING_ITERATOR_TYPE",0x430);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_WEAK_REF_TYPE",0x431);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_EXCEPTION_OBJECT_TYPE",0x432);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_GLOBAL_OBJECT_TYPE",0x433);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_INSTANCE_OBJECT_TYPE",0x434);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_MEMORY_OBJECT_TYPE",0x435);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_MODULE_OBJECT_TYPE",0x436);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_TABLE_OBJECT_TYPE",0x437);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_BOUND_FUNCTION_TYPE",0x438);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_FUNCTION_TYPE",0x439);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OPTIMIZED_FUNCTION",0x43a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BYTECODE_HANDLER",0x43b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STUB",0x43c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BUILTIN",0x43d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"REGEXP",0x43e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_FUNCTION",0x43f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_TO_CAPI_FUNCTION",0x440);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_TO_JS_FUNCTION",0x441);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_TO_WASM_FUNCTION",0x442);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_TO_JS_FUNCTION",0x443);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WASM_INTERPRETER_ENTRY",0x444);
  PrintInstanceTypeJSON(this,param_1,uVar1,"C_WASM_ENTRY",0x445);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ARRAY_BOILERPLATE_DESCRIPTION_ELEMENTS_TYPE",0x446);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ARRAY_DICTIONARY_ELEMENTS_TYPE",0x447);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ARRAY_ELEMENTS_TYPE",0x448);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BOILERPLATE_ELEMENTS_TYPE",0x449);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BOILERPLATE_PROPERTY_ARRAY_TYPE",0x44a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BOILERPLATE_PROPERTY_DICTIONARY_TYPE",1099);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BYTECODE_ARRAY_CONSTANT_POOL_TYPE",0x44c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"BYTECODE_ARRAY_HANDLER_TABLE_TYPE",0x44d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"COW_ARRAY_TYPE",0x44e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DEOPTIMIZATION_DATA_TYPE",0x44f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DEPENDENT_CODE_TYPE",0x450);
  PrintInstanceTypeJSON(this,param_1,uVar1,"DEPRECATED_DESCRIPTOR_ARRAY_TYPE",0x451);
  PrintInstanceTypeJSON(this,param_1,uVar1,"EMBEDDED_OBJECT_TYPE",0x452);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ENUM_KEYS_CACHE_TYPE",0x453);
  PrintInstanceTypeJSON(this,param_1,uVar1,"ENUM_INDICES_CACHE_TYPE",0x454);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_ENTRY_TYPE",0x455);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_HEADER_TYPE",0x456);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_CALL_TYPE",0x457);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_CALL_UNUSED_TYPE",0x458);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_ENUM_TYPE",0x459);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_LOAD_TYPE",0x45a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_LOAD_UNUSED_TYPE",0x45b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_OTHER_TYPE",0x45c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_STORE_TYPE",0x45d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FEEDBACK_VECTOR_SLOT_STORE_UNUSED_TYPE",0x45e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"FUNCTION_TEMPLATE_INFO_ENTRIES_TYPE",0x45f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"GLOBAL_ELEMENTS_TYPE",0x460);
  PrintInstanceTypeJSON(this,param_1,uVar1,"GLOBAL_PROPERTIES_TYPE",0x461);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_ARRAY_BOILERPLATE_TYPE",0x462);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_COLLECTION_TABLE_TYPE",0x463);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_OBJECT_BOILERPLATE_TYPE",0x464);
  PrintInstanceTypeJSON(this,param_1,uVar1,"JS_UNCOMPILED_FUNCTION_TYPE",0x465);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_ABANDONED_PROTOTYPE_TYPE",0x466);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_DEPRECATED_TYPE",0x467);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_DICTIONARY_TYPE",0x468);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_PROTOTYPE_DICTIONARY_TYPE",0x469);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_PROTOTYPE_TYPE",0x46a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"MAP_STABLE_TYPE",0x46b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"NUMBER_STRING_CACHE_TYPE",0x46c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_DICTIONARY_ELEMENTS_TYPE",0x46d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_ELEMENTS_TYPE",0x46e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_PROPERTY_ARRAY_TYPE",0x46f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_PROPERTY_DICTIONARY_TYPE",0x470);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OBJECT_TO_CODE_TYPE",0x471);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OPTIMIZED_CODE_LITERALS_TYPE",0x472);
  PrintInstanceTypeJSON(this,param_1,uVar1,"OTHER_CONTEXT_TYPE",0x473);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROTOTYPE_DESCRIPTOR_ARRAY_TYPE",0x474);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROTOTYPE_PROPERTY_ARRAY_TYPE",0x475);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROTOTYPE_PROPERTY_DICTIONARY_TYPE",0x476);
  PrintInstanceTypeJSON(this,param_1,uVar1,"PROTOTYPE_USERS_TYPE",0x477);
  PrintInstanceTypeJSON(this,param_1,uVar1,"REGEXP_MULTIPLE_CACHE_TYPE",0x478);
  PrintInstanceTypeJSON(this,param_1,uVar1,"RELOC_INFO_TYPE",0x479);
  PrintInstanceTypeJSON(this,param_1,uVar1,"RETAINED_MAPS_TYPE",0x47a);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_LIST_TYPE",0x47b);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_SHARED_FUNCTION_INFOS_TYPE",0x47c);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_SOURCE_EXTERNAL_ONE_BYTE_TYPE",0x47d);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_SOURCE_EXTERNAL_TWO_BYTE_TYPE",0x47e);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_SOURCE_NON_EXTERNAL_ONE_BYTE_TYPE",0x47f);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SCRIPT_SOURCE_NON_EXTERNAL_TWO_BYTE_TYPE",0x480);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SERIALIZED_OBJECTS_TYPE",0x481);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SINGLE_CHARACTER_STRING_CACHE_TYPE",0x482);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STRING_SPLIT_CACHE_TYPE",0x483);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STRING_EXTERNAL_RESOURCE_ONE_BYTE_TYPE",0x484);
  PrintInstanceTypeJSON(this,param_1,uVar1,"STRING_EXTERNAL_RESOURCE_TWO_BYTE_TYPE",0x485);
  PrintInstanceTypeJSON(this,param_1,uVar1,"SOURCE_POSITION_TABLE_TYPE",0x486);
  PrintInstanceTypeJSON(this,param_1,uVar1,"UNCOMPILED_SHARED_FUNCTION_INFO_TYPE",0x487);
  PrintInstanceTypeJSON(this,param_1,uVar1,"WEAK_NEW_SPACE_OBJECT_TO_CODE_TYPE",0x488);
  return;
}

