
/* v8::internal::RegExpBytecodeDisassemble(unsigned char const*, int, char const*) */

void v8::internal::RegExpBytecodeDisassemble(uchar *param_1,int param_2,char *param_3)

{
  byte *pbVar1;
  uchar *puVar2;
  long lVar3;
  
  PrintF("[generated bytecode for regexp pattern: \'%s\']\n",param_3);
  if (0 < param_2) {
    lVar3 = 0;
    do {
      pbVar1 = param_1 + lVar3;
      puVar2 = (uchar *)PrintF("%p  %4tx  ",pbVar1,lVar3);
      RegExpBytecodeDisassembleSingle(puVar2,pbVar1);
      lVar3 = lVar3 + *(int *)(&DAT_01a4af9c + (ulong)*pbVar1 * 4);
    } while (lVar3 < param_2);
  }
  return;
}

