
/* v8::internal::compiler::PipelineImpl::SelectInstructions(v8::internal::compiler::Linkage*) */

void __thiscall
v8::internal::compiler::PipelineImpl::SelectInstructions(PipelineImpl *this,Linkage *param_1)

{
  basic_string<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>> *this_00;
  ulong __n;
  basic_string<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>> bVar1;
  long lVar2;
  char cVar3;
  bool bVar4;
  int iVar5;
  undefined8 uVar6;
  undefined8 *puVar7;
  basic_ostream *pbVar8;
  size_t sVar9;
  ZoneVector *pZVar10;
  OptimizedCompilationInfo *pOVar11;
  RegisterConfiguration *pRVar12;
  InstructionSequence *this_01;
  Frame *this_02;
  __sFILE *p_Var13;
  ulong uVar14;
  ulong uVar15;
  ulong uVar16;
  Zone *pZVar17;
  int *piVar18;
  CallDescriptor *pCVar19;
  char *pcVar20;
  void *__dest;
  undefined8 *puVar21;
  long lVar22;
  ulong local_1e0;
  ulong local_1d8;
  char *local_1d0;
  char *pcStack_1c8;
  Linkage *local_1c0;
  undefined **local_1b8;
  undefined **local_1b0;
  locale alStack_1a8 [8];
  undefined8 local_1a0;
  undefined8 uStack_198;
  undefined8 local_190;
  undefined8 uStack_188;
  undefined8 uStack_180;
  undefined8 uStack_178;
  ulong local_170;
  undefined **ppuStack_168;
  void *local_160;
  undefined8 uStack_158;
  undefined4 local_150;
  undefined **local_148 [17];
  undefined8 local_c0;
  undefined4 local_b8;
  long local_70;
  
  lVar2 = tpidr_el0;
  local_70 = *(long *)(lVar2 + 0x28);
  pCVar19 = *(CallDescriptor **)param_1;
  puVar21 = *(undefined8 **)this;
  local_1c0 = param_1;
  if (FLAG_turbo_profiling != '\0') {
    uVar6 = BasicBlockInstrumentor::Instrument
                      ((OptimizedCompilationInfo *)puVar21[3],(Graph *)puVar21[0x14],
                       (Schedule *)puVar21[0x1d],(Isolate *)*puVar21);
    puVar21[0x2f] = uVar6;
  }
  pcVar20 = FLAG_turbo_verify_machine_graph;
  if (*(char *)((long)puVar21 + 0x41) == '\0') {
    if (FLAG_turbo_verify_machine_graph == (char *)0x0) {
      bVar4 = false;
      piVar18 = (int *)puVar21[0x33];
    }
    else {
      iVar5 = strcmp(FLAG_turbo_verify_machine_graph,"*");
      if (iVar5 == 0) goto LAB_012a48ec;
      iVar5 = strcmp(pcVar20,(char *)puVar21[4]);
      bVar4 = iVar5 == 0;
      piVar18 = (int *)puVar21[0x33];
    }
    if (piVar18 != (int *)0x0) goto LAB_012a48f8;
LAB_012a4950:
    if (bVar4) {
LAB_012a4954:
      if (FLAG_trace_verify_csa != '\0') {
        if ((WasmEngine *)puVar21[1] == (WasmEngine *)0x0) {
          puVar7 = (undefined8 *)Isolate::GetCodeTracer();
        }
        else {
          puVar7 = (undefined8 *)wasm::WasmEngine::GetCodeTracer((WasmEngine *)puVar21[1]);
        }
        p_Var13 = (__sFILE *)puVar7[0x12];
        if (FLAG_redirect_code_traces != '\0') {
          if (p_Var13 == (__sFILE *)0x0) {
            p_Var13 = (__sFILE *)base::OS::FOpen((char *)*puVar7,"ab");
            puVar7[0x12] = p_Var13;
          }
          *(int *)(puVar7 + 0x13) = *(int *)(puVar7 + 0x13) + 1;
        }
        OFStream::OFStream((OFStream *)&local_1b8,p_Var13);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           ((basic_ostream *)&local_1b8,
                            "--------------------------------------------------\n",0x33);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,"--- Verifying ",0xe);
        pcVar20 = (char *)puVar21[4];
        sVar9 = strlen(pcVar20);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,pcVar20,sVar9);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8," generated by TurboFan\n",0x17);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,"--------------------------------------------------\n",0x33);
        pbVar8 = (basic_ostream *)compiler::operator<<(pbVar8,(Schedule *)puVar21[0x1d]);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,"--------------------------------------------------\n",0x33);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,"--- End of ",0xb);
        pcVar20 = (char *)puVar21[4];
        sVar9 = strlen(pcVar20);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8,pcVar20,sVar9);
        pbVar8 = std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                           (pbVar8," generated by TurboFan\n",0x17);
        std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                  (pbVar8,"--------------------------------------------------\n",0x33);
        local_1b8 = &PTR__OFStream_01ca1000;
        ppuStack_168 = &PTR__OFStream_01ca1028;
        local_1b0 = &PTR__basic_streambuf_01c671a8;
        std::__ndk1::locale::~locale(alStack_1a8);
        std::__ndk1::ios_base::~ios_base((ios_base *)&ppuStack_168);
        if ((FLAG_redirect_code_traces != '\0') &&
           (iVar5 = *(int *)(puVar7 + 0x13), *(int *)(puVar7 + 0x13) = iVar5 + -1, iVar5 + -1 == 0))
        {
          fclose((FILE *)puVar7[0x12]);
          puVar7[0x12] = 0;
        }
      }
      Zone::Zone((Zone *)&local_1b8,(AccountingAllocator *)puVar21[2],"machine-graph-verifier-zone")
      ;
      MachineGraphVerifier::Run
                ((Graph *)puVar21[0x14],(Schedule *)puVar21[0x1d],local_1c0,
                 *(int *)(puVar21[3] + 8) != 0 && *(int *)(puVar21[3] + 8) != 5,(char *)puVar21[4],
                 (Zone *)&local_1b8);
      Zone::~Zone((Zone *)&local_1b8);
    }
  }
  else {
LAB_012a48ec:
    bVar4 = true;
    piVar18 = (int *)puVar21[0x33];
    if (piVar18 == (int *)0x0) goto LAB_012a4950;
LAB_012a48f8:
    if ((bool)(bVar4 & *piVar18 != 1)) goto LAB_012a4954;
  }
  pZVar10 = (ZoneVector *)
            InstructionSequence::InstructionBlocksFor
                      ((Zone *)puVar21[0x21],(Schedule *)puVar21[0x1d]);
  pZVar17 = (Zone *)puVar21[0x21];
  this_01 = *(InstructionSequence **)(pZVar17 + 0x10);
  if ((ulong)(*(long *)(pZVar17 + 0x18) - (long)this_01) < 0x178) {
    this_01 = (InstructionSequence *)Zone::NewExpand(pZVar17,0x178);
  }
  else {
    *(InstructionSequence **)(pZVar17 + 0x10) = this_01 + 0x178;
  }
  InstructionSequence::InstructionSequence
            (this_01,(Isolate *)*puVar21,(Zone *)puVar21[0x21],pZVar10);
  puVar21[0x22] = this_01;
  if (pCVar19 == (CallDescriptor *)0x0) {
    iVar5 = 0;
  }
  else {
    if ((*(uint *)pCVar19 < 5) && ((1 << (ulong)(*(uint *)pCVar19 & 0x1f) & 0x16U) != 0)) {
      *(undefined1 *)(*(long *)**(undefined8 **)(this_01 + 0x10) + 0x7c) = 1;
    }
    iVar5 = CallDescriptor::CalculateFixedFrameSize(pCVar19,*(undefined4 *)(puVar21[3] + 8));
  }
  pZVar17 = (Zone *)puVar21[0x26];
  this_02 = *(Frame **)(pZVar17 + 0x10);
  if ((ulong)(*(long *)(pZVar17 + 0x18) - (long)this_02) < 0x20) {
    this_02 = (Frame *)Zone::NewExpand(pZVar17,0x20);
  }
  else {
    *(Frame **)(pZVar17 + 0x10) = this_02 + 0x20;
  }
  Frame::Frame(this_02,iVar5);
  puVar21[0x29] = this_02;
  Run<v8::internal::compiler::InstructionSelectionPhase,v8::internal::compiler::Linkage*&>
            (this,&local_1c0);
  pOVar11 = (OptimizedCompilationInfo *)(*(undefined8 **)this)[3];
  if (*(char *)(puVar21 + 8) == '\0') {
    if (((byte)pOVar11[1] >> 5 & 1) != 0) {
      if (*(char *)(puVar21 + 5) == '\0') {
        TurboCfgFile::TurboCfgFile((TurboCfgFile *)&local_1b8,(Isolate *)**(undefined8 **)this);
        local_1d8 = puVar21[0x22];
        local_1e0 = puVar21[0x1d];
        local_1d0 = (char *)puVar21[0x15];
        pcStack_1c8 = "CodeGen";
        compiler::operator<<((basic_ostream *)&local_1b8,(AsC1V *)&local_1e0);
        TurboCfgFile::~TurboCfgFile((TurboCfgFile *)&local_1b8);
        if ((*(byte *)(*(long *)(*(long *)this + 0x18) + 1) >> 5 & 1) == 0) goto LAB_012a4eb4;
      }
      local_1b8 = (undefined **)0x1c6c8a8;
      local_148[0] = (undefined **)0x1c6c8d0;
      std::__ndk1::ios_base::init((ios_base *)local_148,&local_1b0);
      local_b8 = 0xffffffff;
      local_1b8 = &PTR__basic_ostringstream_01c6c858;
      local_148[0] = &PTR__basic_ostringstream_01c6c880;
      local_1b0 = &PTR__basic_streambuf_01c671a8;
      local_c0 = 0;
      std::__ndk1::locale::locale(alStack_1a8);
      uStack_188 = 0;
      local_190 = 0;
      uStack_178 = 0;
      uStack_180 = 0;
      local_1b0 = &PTR__basic_stringbuf_01c67100;
      uStack_198 = 0;
      local_1a0 = 0;
      ppuStack_168 = (undefined **)0x0;
      local_170 = 0;
      uStack_158 = 0;
      local_160 = (void *)0x0;
      local_150 = 0x10;
      if (*(SourcePositionTable **)(*(long *)this + 0xa8) == (SourcePositionTable *)0x0) {
        std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                  ((basic_ostream *)&local_1b8,"{}",2);
      }
      else {
        SourcePositionTable::PrintJson
                  (*(SourcePositionTable **)(*(long *)this + 0xa8),(basic_ostream *)&local_1b8);
      }
      std::__ndk1::__put_character_sequence<char,std::__ndk1::char_traits<char>>
                ((basic_ostream *)&local_1b8,",\n\"NodeOrigins\" : ",0x12);
      NodeOriginTable::PrintJson
                (*(NodeOriginTable **)(*(long *)this + 0xb0),(basic_ostream *)&local_1b8);
      lVar22 = *(long *)this;
      std::__ndk1::basic_stringbuf<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>>
      ::str();
      this_00 = (basic_string<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>> *)
                (lVar22 + 0x180);
      if (this_00 !=
          (basic_string<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>> *)
          &local_1e0) {
        bVar1 = *this_00;
        __n = local_1e0 >> 1 & 0x7f;
        pcVar20 = (char *)((ulong)&local_1e0 | 1);
        if ((local_1e0 & 1) != 0) {
          __n = local_1d8;
          pcVar20 = local_1d0;
        }
        if (((byte)bVar1 & 1) == 0) {
          uVar14 = 0x16;
          uVar15 = __n - 0x16;
          if (0x15 < __n && uVar15 != 0) {
LAB_012a4e08:
            if (((byte)bVar1 & 1) == 0) {
              uVar16 = (ulong)((byte)bVar1 >> 1);
            }
            else {
              uVar16 = *(ulong *)(lVar22 + 0x188);
            }
            std::__ndk1::
            basic_string<char,std::__ndk1::char_traits<char>,std::__ndk1::allocator<char>>::
            __grow_by_and_replace(this_00,uVar14,uVar15,uVar16,0,uVar16,__n,pcVar20);
            goto joined_r0x012a4e54;
          }
        }
        else {
          uVar14 = (*(ulong *)this_00 & 0xfffffffffffffffe) - 1;
          uVar15 = __n - uVar14;
          if (uVar14 <= __n && uVar15 != 0) goto LAB_012a4e08;
        }
        if (((byte)bVar1 & 1) == 0) {
          __dest = (void *)(lVar22 + 0x181);
        }
        else {
          __dest = *(void **)(lVar22 + 400);
        }
        if (__n != 0) {
          memmove(__dest,pcVar20,__n);
        }
        *(undefined1 *)((long)__dest + __n) = 0;
        if (((byte)*this_00 & 1) == 0) {
          *this_00 = SUB41((int)__n << 1,0);
        }
        else {
          *(ulong *)(lVar22 + 0x188) = __n;
        }
      }
joined_r0x012a4e54:
      if ((local_1e0 & 1) != 0) {
        operator_delete(local_1d0);
      }
      local_1b8 = &PTR__basic_ostringstream_01c6c858;
      local_148[0] = &PTR__basic_ostringstream_01c6c880;
      local_1b0 = &PTR__basic_stringbuf_01c67100;
      if ((local_170 & 1) != 0) {
        operator_delete(local_160);
      }
      local_1b0 = &PTR__basic_streambuf_01c671a8;
      std::__ndk1::locale::~locale(alStack_1a8);
      std::__ndk1::ios_base::~ios_base((ios_base *)local_148);
    }
LAB_012a4eb4:
    if (puVar21[0x13] != 0) {
      if (puVar21[0x12] != 0) {
        ZoneStats::ReturnZone((Zone *)puVar21[0x11]);
      }
      puVar21[0x1b] = 0;
      puVar21[0x1a] = 0;
      puVar21[0x1d] = 0;
      puVar21[0x1c] = 0;
      puVar21[0x17] = 0;
      puVar21[0x16] = 0;
      puVar21[0x19] = 0;
      puVar21[0x18] = 0;
      puVar21[0x13] = 0;
      puVar21[0x12] = 0;
      puVar21[0x15] = 0;
      puVar21[0x14] = 0;
    }
    if ((PipelineStatistics *)puVar21[7] != (PipelineStatistics *)0x0) {
      PipelineStatistics::BeginPhaseKind((PipelineStatistics *)puVar21[7],"V8.TFRegisterAllocation")
      ;
    }
    cVar3 = FLAG_turbo_verify_allocation;
    if (*(ulong *)(pCVar19 + 0x40) == 0) {
      if (*(int *)(puVar21[3] + 4) == 1) {
        pRVar12 = (RegisterConfiguration *)RegisterConfiguration::Default();
      }
      else {
        pRVar12 = (RegisterConfiguration *)RegisterConfiguration::Poisoning();
      }
      AllocateRegisters(this,pRVar12,pCVar19,cVar3 != '\0');
    }
    else {
      bVar4 = FLAG_turbo_verify_allocation != '\0';
      pRVar12 = (RegisterConfiguration *)
                RegisterConfiguration::RestrictGeneralRegisters(*(ulong *)(pCVar19 + 0x40));
      AllocateRegisters(this,pRVar12,pCVar19,bVar4);
      if (pRVar12 != (RegisterConfiguration *)0x0) {
        (**(code **)(*(long *)pRVar12 + 8))(pRVar12);
      }
    }
    VerifyGeneratedCodeIsIdempotent(this);
    Run<v8::internal::compiler::FrameElisionPhase>(this);
    if (*(char *)(puVar21 + 8) == '\0') {
      local_1b8 = (undefined **)
                  CONCAT71(local_1b8._1_7_,
                           *(undefined1 *)
                            (*(long *)**(undefined8 **)(*(long *)(*(long *)this + 0x110) + 0x10) +
                            0x7d));
      if (FLAG_turbo_jt != '\0') {
        Run<v8::internal::compiler::JumpThreadingPhase,bool&>(this,(bool *)&local_1b8);
      }
      if ((PipelineStatistics *)puVar21[7] != (PipelineStatistics *)0x0) {
        PipelineStatistics::EndPhaseKind((PipelineStatistics *)puVar21[7]);
      }
      uVar6 = 1;
      goto LAB_012a5008;
    }
    uVar6 = 9;
    pOVar11 = *(OptimizedCompilationInfo **)(*(long *)this + 0x18);
  }
  else {
    uVar6 = 2;
  }
  OptimizedCompilationInfo::AbortOptimization(pOVar11,uVar6);
  uVar6 = 0;
  if ((PipelineStatistics *)puVar21[7] != (PipelineStatistics *)0x0) {
    PipelineStatistics::EndPhaseKind((PipelineStatistics *)puVar21[7]);
    uVar6 = 0;
  }
LAB_012a5008:
  if (*(long *)(lVar2 + 0x28) != local_70) {
                    /* WARNING: Subroutine does not return */
    __stack_chk_fail(uVar6);
  }
  return;
}

