
/* v8::internal::interpreter::Bytecodes::ToString(v8::internal::interpreter::Bytecode) */

char * v8::internal::interpreter::Bytecodes::ToString(undefined1 param_1)

{
  char *pcVar1;
  
  pcVar1 = "Wide";
  switch(param_1) {
  case 0:
    goto switchD_01040298_caseD_0;
  case 1:
    pcVar1 = "ExtraWide";
switchD_01040298_caseD_0:
    return pcVar1;
  case 2:
    return "DebugBreakWide";
  case 3:
    return "DebugBreakExtraWide";
  case 4:
    return "DebugBreak0";
  case 5:
    return "DebugBreak1";
  case 6:
    return "DebugBreak2";
  case 7:
    return "DebugBreak3";
  case 8:
    return "DebugBreak4";
  case 9:
    return "DebugBreak5";
  case 10:
    return "DebugBreak6";
  case 0xb:
    return "LdaZero";
  case 0xc:
    return "LdaSmi";
  case 0xd:
    return "LdaUndefined";
  case 0xe:
    return "LdaNull";
  case 0xf:
    return "LdaTheHole";
  case 0x10:
    return "LdaTrue";
  case 0x11:
    return "LdaFalse";
  case 0x12:
    return "LdaConstant";
  case 0x13:
    return "LdaGlobal";
  case 0x14:
    return "LdaGlobalInsideTypeof";
  case 0x15:
    return "StaGlobal";
  case 0x16:
    return "PushContext";
  case 0x17:
    return "PopContext";
  case 0x18:
    return "LdaContextSlot";
  case 0x19:
    return "LdaImmutableContextSlot";
  case 0x1a:
    return "LdaCurrentContextSlot";
  case 0x1b:
    return "LdaImmutableCurrentContextSlot";
  case 0x1c:
    return "StaContextSlot";
  case 0x1d:
    return "StaCurrentContextSlot";
  case 0x1e:
    return "LdaLookupSlot";
  case 0x1f:
    return "LdaLookupContextSlot";
  case 0x20:
    return "LdaLookupGlobalSlot";
  case 0x21:
    return "LdaLookupSlotInsideTypeof";
  case 0x22:
    return "LdaLookupContextSlotInsideTypeof";
  case 0x23:
    return "LdaLookupGlobalSlotInsideTypeof";
  case 0x24:
    return "StaLookupSlot";
  case 0x25:
    return "Ldar";
  case 0x26:
    return "Star";
  case 0x27:
    return "Mov";
  case 0x28:
    return "LdaNamedProperty";
  case 0x29:
    return "LdaNamedPropertyNoFeedback";
  case 0x2a:
    return "LdaKeyedProperty";
  case 0x2b:
    return "LdaModuleVariable";
  case 0x2c:
    return "StaModuleVariable";
  case 0x2d:
    return "StaNamedProperty";
  case 0x2e:
    return "StaNamedPropertyNoFeedback";
  case 0x2f:
    return "StaNamedOwnProperty";
  case 0x30:
    return "StaKeyedProperty";
  case 0x31:
    return "StaInArrayLiteral";
  case 0x32:
    return "StaDataPropertyInLiteral";
  case 0x33:
    return "CollectTypeProfile";
  case 0x34:
    return "Add";
  case 0x35:
    return "Sub";
  case 0x36:
    return "Mul";
  case 0x37:
    return "Div";
  case 0x38:
    return "Mod";
  case 0x39:
    return "Exp";
  case 0x3a:
    return "BitwiseOr";
  case 0x3b:
    return "BitwiseXor";
  case 0x3c:
    return "BitwiseAnd";
  case 0x3d:
    return "ShiftLeft";
  case 0x3e:
    return "ShiftRight";
  case 0x3f:
    return "ShiftRightLogical";
  case 0x40:
    return "AddSmi";
  case 0x41:
    return "SubSmi";
  case 0x42:
    return "MulSmi";
  case 0x43:
    return "DivSmi";
  case 0x44:
    return "ModSmi";
  case 0x45:
    return "ExpSmi";
  case 0x46:
    return "BitwiseOrSmi";
  case 0x47:
    return "BitwiseXorSmi";
  case 0x48:
    return "BitwiseAndSmi";
  case 0x49:
    return "ShiftLeftSmi";
  case 0x4a:
    return "ShiftRightSmi";
  case 0x4b:
    return "ShiftRightLogicalSmi";
  case 0x4c:
    return "Inc";
  case 0x4d:
    return "Dec";
  case 0x4e:
    return "Negate";
  case 0x4f:
    return "BitwiseNot";
  case 0x50:
    return "ToBooleanLogicalNot";
  case 0x51:
    return "LogicalNot";
  case 0x52:
    return "TypeOf";
  case 0x53:
    return "DeletePropertyStrict";
  case 0x54:
    return "DeletePropertySloppy";
  case 0x55:
    return "GetSuperConstructor";
  case 0x56:
    return "CallAnyReceiver";
  case 0x57:
    return "CallProperty";
  case 0x58:
    return "CallProperty0";
  case 0x59:
    return "CallProperty1";
  case 0x5a:
    return "CallProperty2";
  case 0x5b:
    return "CallUndefinedReceiver";
  case 0x5c:
    return "CallUndefinedReceiver0";
  case 0x5d:
    return "CallUndefinedReceiver1";
  case 0x5e:
    return "CallUndefinedReceiver2";
  case 0x5f:
    return "CallNoFeedback";
  case 0x60:
    return "CallWithSpread";
  case 0x61:
    return "CallRuntime";
  case 0x62:
    return "CallRuntimeForPair";
  case 99:
    return "CallJSRuntime";
  case 100:
    return "InvokeIntrinsic";
  case 0x65:
    return "Construct";
  case 0x66:
    return "ConstructWithSpread";
  case 0x67:
    return "TestEqual";
  case 0x68:
    return "TestEqualStrict";
  case 0x69:
    return "TestLessThan";
  case 0x6a:
    return "TestGreaterThan";
  case 0x6b:
    return "TestLessThanOrEqual";
  case 0x6c:
    return "TestGreaterThanOrEqual";
  case 0x6d:
    return "TestReferenceEqual";
  case 0x6e:
    return "TestInstanceOf";
  case 0x6f:
    return "TestIn";
  case 0x70:
    return "TestUndetectable";
  case 0x71:
    return "TestNull";
  case 0x72:
    return "TestUndefined";
  case 0x73:
    return "TestTypeOf";
  case 0x74:
    return "ToName";
  case 0x75:
    return "ToNumber";
  case 0x76:
    return "ToNumeric";
  case 0x77:
    return "ToObject";
  case 0x78:
    return "ToString";
  case 0x79:
    return "CreateRegExpLiteral";
  case 0x7a:
    return "CreateArrayLiteral";
  case 0x7b:
    return "CreateArrayFromIterable";
  case 0x7c:
    return "CreateEmptyArrayLiteral";
  case 0x7d:
    return "CreateObjectLiteral";
  case 0x7e:
    return "CreateEmptyObjectLiteral";
  case 0x7f:
    return "CloneObject";
  case 0x80:
    return "GetTemplateObject";
  case 0x81:
    return "CreateClosure";
  case 0x82:
    return "CreateBlockContext";
  case 0x83:
    return "CreateCatchContext";
  case 0x84:
    return "CreateFunctionContext";
  case 0x85:
    return "CreateEvalContext";
  case 0x86:
    return "CreateWithContext";
  case 0x87:
    return "CreateMappedArguments";
  case 0x88:
    return "CreateUnmappedArguments";
  case 0x89:
    return "CreateRestParameter";
  case 0x8a:
    return "JumpLoop";
  case 0x8b:
    return "Jump";
  case 0x8c:
    return "JumpConstant";
  case 0x8d:
    return "JumpIfNullConstant";
  case 0x8e:
    return "JumpIfNotNullConstant";
  case 0x8f:
    return "JumpIfUndefinedConstant";
  case 0x90:
    return "JumpIfNotUndefinedConstant";
  case 0x91:
    return "JumpIfUndefinedOrNullConstant";
  case 0x92:
    return "JumpIfTrueConstant";
  case 0x93:
    return "JumpIfFalseConstant";
  case 0x94:
    return "JumpIfJSReceiverConstant";
  case 0x95:
    return "JumpIfToBooleanTrueConstant";
  case 0x96:
    return "JumpIfToBooleanFalseConstant";
  case 0x97:
    return "JumpIfToBooleanTrue";
  case 0x98:
    return "JumpIfToBooleanFalse";
  case 0x99:
    return "JumpIfTrue";
  case 0x9a:
    return "JumpIfFalse";
  case 0x9b:
    return "JumpIfNull";
  case 0x9c:
    return "JumpIfNotNull";
  case 0x9d:
    return "JumpIfUndefined";
  case 0x9e:
    return "JumpIfNotUndefined";
  case 0x9f:
    return "JumpIfUndefinedOrNull";
  case 0xa0:
    return "JumpIfJSReceiver";
  case 0xa1:
    return "SwitchOnSmiNoFeedback";
  case 0xa2:
    return "ForInEnumerate";
  case 0xa3:
    return "ForInPrepare";
  case 0xa4:
    return "ForInContinue";
  case 0xa5:
    return "ForInNext";
  case 0xa6:
    return "ForInStep";
  case 0xa7:
    return "StackCheck";
  case 0xa8:
    return "SetPendingMessage";
  case 0xa9:
    return "Throw";
  case 0xaa:
    return "ReThrow";
  case 0xab:
    return "Return";
  case 0xac:
    return "ThrowReferenceErrorIfHole";
  case 0xad:
    return "ThrowSuperNotCalledIfHole";
  case 0xae:
    return "ThrowSuperAlreadyCalledIfNotHole";
  case 0xaf:
    return "SwitchOnGeneratorState";
  case 0xb0:
    return "SuspendGenerator";
  case 0xb1:
    return "ResumeGenerator";
  case 0xb2:
    return "GetIterator";
  case 0xb3:
    return "Debugger";
  case 0xb4:
    return "IncBlockCounter";
  case 0xb5:
    return "Abort";
  case 0xb6:
    return "Illegal";
  default:
                    /* WARNING: Subroutine does not return */
    V8_Fatal("unreachable code");
  }
}

