
void FUN_00a331b4(long param_1,int param_2)

{
  long *plVar1;
  char *pcVar2;
  char *pcVar3;
  undefined *puVar4;
  char *pcVar5;
  char *pcVar6;
  bool bVar7;
  int iVar8;
  time_t tVar9;
  code *__s;
  long lVar10;
  char *pcVar11;
  char *pcVar12;
  char *pcVar13;
  long *plVar14;
  long *plVar16;
  long *plVar17;
  long *plVar15;
  
  if (*(long *)(param_1 + 0x698) == 0) {
    if ((param_2 != 0) && (*(long *)(param_1 + 0x928) != 0)) {
      FUN_00a2c624();
      *(undefined8 *)(param_1 + 0x928) = 0;
    }
    FUN_00a4bf64(param_1,2,2);
  }
  else {
    if (*(long *)(param_1 + 0x928) != 0) {
      FUN_00a31328(param_1);
    }
    FUN_00a4bf64(param_1,2,2);
    plVar16 = *(long **)(param_1 + 0x938);
    if ((plVar16 != (long *)0x0) && (plVar16[3] != 0)) {
      pcVar13 = *(char **)(param_1 + 0x698);
      tVar9 = time((time_t *)0x0);
      if ((long *)*plVar16 != (long *)0x0) {
        plVar17 = (long *)*plVar16;
        plVar14 = (long *)0x0;
        do {
          while( true ) {
            plVar15 = plVar17;
            plVar17 = (long *)*plVar15;
            if ((plVar15[6] == 0) || (tVar9 <= plVar15[6])) break;
            plVar1 = plVar16;
            if (plVar15 != (long *)*plVar16) {
              plVar1 = plVar14;
            }
            *plVar1 = (long)plVar17;
            plVar16[3] = plVar16[3] + -1;
            (*(code *)PTR_free_01769a00)(plVar15[7]);
            (*(code *)PTR_free_01769a00)(plVar15[5]);
            (*(code *)PTR_free_01769a00)(plVar15[3]);
            (*(code *)PTR_free_01769a00)(plVar15[4]);
            (*(code *)PTR_free_01769a00)(plVar15[1]);
            (*(code *)PTR_free_01769a00)(plVar15[2]);
            (*(code *)PTR_free_01769a00)(plVar15[10]);
            (*(code *)PTR_free_01769a00)(plVar15[9]);
            (*(code *)PTR_free_01769a00)(plVar15);
            if (plVar17 == (long *)0x0) goto LAB_00a332ec;
          }
          plVar14 = plVar15;
        } while (plVar17 != (long *)0x0);
      }
LAB_00a332ec:
      iVar8 = strcmp("-",pcVar13);
      if (iVar8 == 0) {
        __s = glUniformMatrix2fv;
        bVar7 = true;
      }
      else {
        __s = (code *)fopen(pcVar13,"w");
        if ((FILE *)__s == (FILE *)0x0) {
LAB_00a3349c:
          FUN_00a38740(param_1,"WARNING: failed to save cookies in %s\n",
                       *(undefined8 *)(param_1 + 0x698));
          goto joined_r0x00a33344;
        }
        bVar7 = false;
      }
      fwrite("# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n"
             ,0x88,1,(FILE *)__s);
      plVar16 = (long *)*plVar16;
      if (plVar16 != (long *)0x0) {
                    /* try { // try from 00a3339c to 00b33417 has its CatchHandler @ 00a3339c
                       catch() { ... } // from try @ 00a3339c with catch @ 00a3339c
                       catch() { ... } // from try @ 00a33424 with catch @ 00a3339c */
        pcVar13 = "";
        do {
          pcVar12 = (char *)plVar16[5];
          if (pcVar12 != (char *)0x0) {
            pcVar2 = "#HttpOnly_";
            if (*(char *)((long)plVar16 + 0x5a) == '\0') {
              pcVar2 = pcVar13;
            }
            pcVar11 = pcVar13;
            if (((char)plVar16[8] != '\0') && (pcVar11 = ".", *pcVar12 == '.')) {
              pcVar11 = pcVar13;
            }
            pcVar3 = "TRUE";
            if ((char)plVar16[8] == '\0') {
              pcVar3 = "FALSE";
            }
            puVar4 = &DAT_0144b7ba;
            if ((undefined *)plVar16[3] != (undefined *)0x0) {
              puVar4 = (undefined *)plVar16[3];
            }
            pcVar5 = "TRUE";
                    /* try { // try from 00a33418 to 00b33423 has its CatchHandler @ 00a33458 */
            if ((char)plVar16[0xb] == '\0') {
              pcVar5 = "FALSE";
            }
            pcVar6 = pcVar13;
            if ((char *)plVar16[2] != (char *)0x0) {
              pcVar6 = (char *)plVar16[2];
            }
                    /* try { // try from 00a33424 to 00b3346b has its CatchHandler @ 00a3339c */
            lVar10 = FUN_00a24258("%s%s%s\t%s\t%s\t%s\t%ld\t%s\t%s",pcVar2,pcVar11,pcVar12,pcVar3,
                                  puVar4,pcVar5,plVar16[6],plVar16[1],pcVar6);
            if (lVar10 == 0) {
              FUN_00a2462c(__s,"#\n# Fatal libcurl error\n");
              if (!bVar7) {
                fclose((FILE *)__s);
              }
              goto LAB_00a3349c;
            }
            FUN_00a2462c(__s,"%s\n",lVar10);
                    /* catch() { ... } // from try @ 00a33418 with catch @ 00a33458 */
            (*(code *)PTR_free_01769a00)(lVar10);
          }
          plVar16 = (long *)*plVar16;
        } while (plVar16 != (long *)0x0);
      }
      if (!bVar7) {
        fclose((FILE *)__s);
      }
    }
  }
joined_r0x00a33344:
  if (param_2 != 0) {
    plVar16 = *(long **)(param_1 + 0x938);
    if (((*(long *)(param_1 + 0x70) == 0) ||
        (plVar16 != *(long **)(*(long *)(param_1 + 0x70) + 0x50))) && (plVar16 != (long *)0x0)) {
      (*(code *)PTR_free_01769a00)(plVar16[1]);
      plVar17 = (long *)*plVar16;
      while (plVar17 != (long *)0x0) {
        lVar10 = *plVar17;
        (*(code *)PTR_free_01769a00)(plVar17[7]);
        (*(code *)PTR_free_01769a00)(plVar17[5]);
        (*(code *)PTR_free_01769a00)(plVar17[3]);
        (*(code *)PTR_free_01769a00)(plVar17[4]);
        (*(code *)PTR_free_01769a00)(plVar17[1]);
        (*(code *)PTR_free_01769a00)(plVar17[2]);
        (*(code *)PTR_free_01769a00)(plVar17[10]);
        (*(code *)PTR_free_01769a00)(plVar17[9]);
        (*(code *)PTR_free_01769a00)(plVar17);
        plVar17 = (long *)lVar10;
      }
      (*(code *)PTR_free_01769a00)(plVar16);
    }
  }
  FUN_00a4bfbc(param_1,2);
  return;
}

