
undefined8 luaopen_lua_m_socket_tp(undefined8 param_1)

{
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- Unified SMTP/FTP subsystem\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-----------------------------------------------------------------------------\nlocal base = _G\nlocal string = require(\"string\")\nlocal socket = require(\"socket.socket\")\nlocal ltn12 = require(\"socket.ltn12\")\n\nsocket.tp = {}\nlocal _M = socket.tp\n\n-----------------------------------------------------------------------------\n-- Program constants\n-----------------------------------------------------------------------------\n_M.TIMEOUT = 60\n\n-----------------------------------------------------------------------------\n-- Implementation\n-----------------------------------------------------------------------------\n-- gets server reply (works for SMTP and FTP)\nlocal function get_reply(c)\n    local code, current, sep\n    local line, err = c:receive()\n    local reply = line\n    if err then return nil, err end\n    code, sep = socket.skip(2, string.find(line, \"^(%d%d%d)(.?)\"))\n    if not code then return nil, \"invalid server reply\" end\n    if sep == \"-\" then -- reply is multiline\n        repeat\n            line, err = c:receive()\n            if err then return nil, err end\n            current, sep = socket.skip(2, string.find(line, \"^(%d%d%d)(.?)\"))\n            reply = reply .. \"\\n\" .. line\n        -- reply ends with same code\n        until code == current and sep == \" \"\n    end\n    return code, reply\nend\n\n-- metatable for sock object\nlocal metat = { __index = {} }\n\nfunction metat.__index:check(ok)\n    local code, reply = get_reply(self.c)\n    if not code then return nil, reply end\n    if base.type(ok) ~= \"function\" then\n        if base.type(ok) == \"table\" then\n            for i, v in base.ipairs(ok) do\n                if string.find(code, v) then\n                    return base.tonu..." /* TRUNCATED STRING LITERAL */
                 );
  return 1;
}

