
undefined8 luaopen_lua_m_socket_http(undefined8 param_1)

{
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- HTTP/1.1 client support for the Lua language.\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-------------------------------------------------------------------------------\nlocal socket = require(\"socket.socket\")\nlocal url = require(\"socket.url\")\nlocal ltn12 = require(\"socket.ltn12\")\nlocal mime = require(\"socket.mime\")\nlocal string = require(\"string\")\nlocal headers = require(\"socket.headers\")\nlocal base = _G\nlocal table = require(\"table\")\nsocket.http = {}\nlocal _M = socket.http\n\n-----------------------------------------------------------------------------\n-- Program constants\n-----------------------------------------------------------------------------\n-- connection timeout in seconds\nTIMEOUT = 60\n-- default port for document retrieval\n_M.PORT = 80\n-- user agent field sent in request\n_M.USERAGENT = socket._VERSION\n\n-----------------------------------------------------------------------------\n-- Reads MIME headers from a connection, unfolding where needed\n-----------------------------------------------------------------------------\nlocal function receiveheaders(sock, headers)\n    local line, name, value, err\n    headers = headers or {}\n    -- get first line\n    line, err = sock:receive()\n    if err then return nil, err end\n    -- headers go until a blank line is found\n    while line ~= \"\" do\n        -- get field-name and value\n        name, value = socket.skip(2, string.find(line, \"^(.-):%s*(.*)\"))\n        if not (name and value) then return nil, \"malformed reponse headers\" end\n        name = string.lower(name)\n        -- get next line (value might be folded)\n        line, err  = sock:receive()\n        if err then return nil, err end\n        -- unfold any folded values\n        while string.find(line, \"^%s\") do\n            value = value .. li..." /* TRUNCATED STRING LITERAL */
                 );
  return 1;
}

