
undefined8 luaopen_lua_m_socket_mbox(undefined8 param_1)

{
  luaL_loadstring(param_1,
                  "local _M = {}\n\nif module then\n    mbox = _M\nend \n\nfunction _M.split_message(message_s)\n    local message = {}\n    message_s = string.gsub(message_s, \"\\r\\n\", \"\\n\")\n    string.gsub(message_s, \"^(.-\\n)\\n\", function (h) message.headers = h end)\n    string.gsub(message_s, \"^.-\\n\\n(.*)\", function (b) message.body = b end)\n    if not message.body then\n        string.gsub(message_s, \"^\\n(.*)\", function (b) message.body = b end)\n    end\n    if not message.headers and not message.body then\n        message.headers = message_s\n    end\n    return message.headers or \"\", message.body or \"\"\nend\n\nfunction _M.split_headers(headers_s)\n    local headers = {}\n    headers_s = string.gsub(headers_s, \"\\r\\n\", \"\\n\")\n    headers_s = string.gsub(headers_s, \"\\n[ ]+\", \" \")\n    string.gsub(\"\\n\" .. headers_s, \"\\n([^\\n]+)\", function (h) table.insert(headers, h) end)\n    return headers\nend\n\nfunction _M.parse_header(header_s)\n    header_s = string.gsub(header_s, \"\\n[ ]+\", \" \")\n    header_s = string.gsub(header_s, \"\\n+\", \"\")\n    local _, __, name, value = string.find(header_s, \"([^%s:]-):%s*(.*)\")\n    return name, value\nend\n\nfunction _M.parse_headers(headers_s)\n    local headers_t = _M.split_headers(headers_s)\n    local headers = {}\n    for i = 1, #headers_t do\n        local name, value = _M.parse_header(headers_t[i])\n        if name then\n            name = string.lower(name)\n            if headers[name] then\n                headers[name] = headers[name] .. \", \" .. value\n            else headers[name] = value end\n        end\n    end\n    return headers\nend\n\nfunction _M.parse_from(from)\n    local _, __, name, address = string.find(from, \"^%s*(.-)%s*%<(.-)%>\")\n    if not address then\n        _, __, address = string.find(from, \"%s*(.+)%s*\")\n    end\n    name = name or \"\"\n    address = address or \"\"\n    if name == \"\" then name = address end\n    name = string.gsub(name, \'\"\', \"\")\n    return name, address\nend\n\nfunction _M.split_mbox(mbox_s)\n    mbox = {}\n    mbox_s = string.gsub(mbox_s, \"\\r\\n\", \"\\n\") ..\"\\n\\nFrom \\n\"\n    local nj, i, j = 1, 1, 1\n    while 1 ..." /* TRUNCATED STRING LITERAL */
                 );
  return 1;
}

