
void luaopen_luasocket_scripts(undefined8 param_1)

{
  lua_getfield(param_1,0xffffd8ee,"package");
  lua_getfield(param_1,0xffffffff,"preload");
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- LTN12 - Filters, sources, sinks and pumps.\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module\n-----------------------------------------------------------------------------\nlocal string = require(\"string\")\nlocal table = require(\"table\")\nlocal base = _G\nlocal _M = {}\nif module then -- heuristic for exporting a global package table\n    ltn12 = _M\nend\nlocal filter,source,sink,pump = {},{},{},{}\n\n_M.filter = filter\n_M.source = source\n_M.sink = sink\n_M.pump = pump\n\n-- 2048 seems to be better in windows...\n_M.BLOCKSIZE = 2048\n_M._VERSION = \"LTN12 1.0.3\"\n\n-----------------------------------------------------------------------------\n-- Filter stuff\n-----------------------------------------------------------------------------\n-- returns a high level filter that cycles a low-level filter\nfunction filter.cycle(low, ctx, extra)\n    base.assert(low)\n    return function(chunk)\n        local ret\n        ret, ctx = low(ctx, chunk, extra)\n        return ret\n    end\nend\n\n-- chains a bunch of filters together\n-- (thanks to Wim Couwenberg)\nfunction filter.chain(...)\n    local arg = {...}\n    local n = select(\'#\',...)\n    local top, index = 1, 1\n    local retry = \"\"\n    return function(chunk)\n        retry = chunk and retry\n        while true do\n            if index == top then\n                chunk = arg[index](chunk)\n                if chunk == \"\" or top == n then return chunk\n                elseif chunk then index = index + 1\n                else\n                    top = top+1\n                    index = top\n                end\n            else\n                chunk = arg[index](chunk or \"\")\n                if chunk == \"\" then\n                    index = index - 1\n                    chunk = retry\n                elseif chunk then\n                    if index == n then return chunk\n  ..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"ltn12");
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- MIME support for the Lua language.\n-- Author: Diego Nehab\n-- Conforming to RFCs 2045-2049\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-----------------------------------------------------------------------------\nlocal base = _G\nlocal ltn12 = require(\"ltn12\")\nlocal mime = require(\"mime.core\")\nlocal io = require(\"io\")\nlocal string = require(\"string\")\nlocal _M = mime\n\n-- encode, decode and wrap algorithm tables\nlocal encodet, decodet, wrapt = {},{},{}\n\n_M.encodet = encodet\n_M.decodet = decodet\n_M.wrapt   = wrapt  \n\n-- creates a function that chooses a filter by name from a given table\nlocal function choose(table)\n    return function(name, opt1, opt2)\n        if base.type(name) ~= \"string\" then\n            name, opt1, opt2 = \"default\", name, opt1\n        end\n        local f = table[name or \"nil\"]\n        if not f then \n            base.error(\"unknown key (\" .. base.tostring(name) .. \")\", 3)\n        else return f(opt1, opt2) end\n    end\nend\n\n-- define the encoding filters\nencodet[\'base64\'] = function()\n    return ltn12.filter.cycle(_M.b64, \"\")\nend\n\nencodet[\'quoted-printable\'] = function(mode)\n    return ltn12.filter.cycle(_M.qp, \"\",\n        (mode == \"binary\") and \"=0D=0A\" or \"\\r\\n\")\nend\n\n-- define the decoding filters\ndecodet[\'base64\'] = function()\n    return ltn12.filter.cycle(_M.unb64, \"\")\nend\n\ndecodet[\'quoted-printable\'] = function()\n    return ltn12.filter.cycle(_M.unqp, \"\")\nend\n\nlocal function format(chunk)\n    if chunk then\n        if chunk == \"\" then return \"\'\'\"\n        else return string.len(chunk) end\n    else return \"nil\" end\nend\n\n-- define the line-wrap filters\nwrapt[\'text\'] = function(length)\n    length = length or 76\n    return ltn12.filter.cycle(_M.wrp, length, length)\nend\nwrapt[\'base64\'] = wrapt[\'text\']\nwrapt[\'default\'] = wrapt[\'text\']\n\nwrapt[\'quoted-printable\'] = functio..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"mime");
  luaL_loadstring(param_1,&DAT_012b809b);
  lua_setfield(param_1,0xfffffffe,"socket.ftp");
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- Canonic header field capitalization\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\nlocal socket = require(\"socket.socket\")\nsocket.headers = {}\nlocal _M = socket.headers\n\n_M.canonic = {\n    [\"accept\"] = \"Accept\",\n    [\"accept-charset\"] = \"Accept-Charset\",\n    [\"accept-encoding\"] = \"Accept-Encoding\",\n    [\"accept-language\"] = \"Accept-Language\",\n    [\"accept-ranges\"] = \"Accept-Ranges\",\n    [\"action\"] = \"Action\",\n    [\"alternate-recipient\"] = \"Alternate-Recipient\",\n    [\"age\"] = \"Age\",\n    [\"allow\"] = \"Allow\",\n    [\"arrival-date\"] = \"Arrival-Date\",\n    [\"authorization\"] = \"Authorization\",\n    [\"bcc\"] = \"Bcc\",\n    [\"cache-control\"] = \"Cache-Control\",\n    [\"cc\"] = \"Cc\",\n    [\"comments\"] = \"Comments\",\n    [\"connection\"] = \"Connection\",\n    [\"content-description\"] = \"Content-Description\",\n    [\"content-disposition\"] = \"Content-Disposition\",\n    [\"content-encoding\"] = \"Content-Encoding\",\n    [\"content-id\"] = \"Content-ID\",\n    [\"content-language\"] = \"Content-Language\",\n    [\"content-length\"] = \"Content-Length\",\n    [\"content-location\"] = \"Content-Location\",\n    [\"content-md5\"] = \"Content-MD5\",\n    [\"content-range\"] = \"Content-Range\",\n    [\"content-transfer-encoding\"] = \"Content-Transfer-Encoding\",\n    [\"content-type\"] = \"Content-Type\",\n    [\"cookie\"] = \"Cookie\",\n    [\"date\"] = \"Date\",\n    [\"diagnostic-code\"] = \"Diagnostic-Code\",\n    [\"dsn-gateway\"] = \"DSN-Gateway\",\n    [\"etag\"] = \"ETag\",\n    [\"expect\"] = \"Expect\",\n    [\"expires\"] = \"Expires\",\n    [\"final-log-id\"] = \"Final-Log-ID\",\n    [\"final-recipient\"] = \"Final-Recipient\",\n    [\"from\"] = \"From\",\n    [\"host\"] = \"Host\",\n    [\"if-match\"] = \"If-Match\",\n    [\"if-modified-since\"] = \"If-Modified-Since\",\n    [\"if-none-match\"] = \"If-None-Match\",\n    [\"if-range\"] = \"If-Range\",\n    [\"if-unmodified-since\"] = \"If-Unmodified-Since\",\n    [\"in-reply-to\"] = \"In-Reply-To\",\n    [\"keywords\"] = \"Keywords\",\n    [\"last-attempt-date\"] = \"La..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"socket.headers");
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- HTTP/1.1 client support for the Lua language.\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-------------------------------------------------------------------------------\nlocal socket = require(\"socket.socket\")\nlocal url = require(\"socket.url\")\nlocal ltn12 = require(\"socket.ltn12\")\nlocal mime = require(\"socket.mime\")\nlocal string = require(\"string\")\nlocal headers = require(\"socket.headers\")\nlocal base = _G\nlocal table = require(\"table\")\nsocket.http = {}\nlocal _M = socket.http\n\n-----------------------------------------------------------------------------\n-- Program constants\n-----------------------------------------------------------------------------\n-- connection timeout in seconds\nTIMEOUT = 60\n-- default port for document retrieval\n_M.PORT = 80\n-- user agent field sent in request\n_M.USERAGENT = socket._VERSION\n\n-----------------------------------------------------------------------------\n-- Reads MIME headers from a connection, unfolding where needed\n-----------------------------------------------------------------------------\nlocal function receiveheaders(sock, headers)\n    local line, name, value, err\n    headers = headers or {}\n    -- get first line\n    line, err = sock:receive()\n    if err then return nil, err end\n    -- headers go until a blank line is found\n    while line ~= \"\" do\n        -- get field-name and value\n        name, value = socket.skip(2, string.find(line, \"^(.-):%s*(.*)\"))\n        if not (name and value) then return nil, \"malformed reponse headers\" end\n        name = string.lower(name)\n        -- get next line (value might be folded)\n        line, err  = sock:receive()\n        if err then return nil, err end\n        -- unfold any folded values\n        while string.find(line, \"^%s\") do\n            value = value .. li..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"socket.http");
  luaL_loadstring(param_1,
                  "local _M = {}\n\nif module then\n    mbox = _M\nend \n\nfunction _M.split_message(message_s)\n    local message = {}\n    message_s = string.gsub(message_s, \"\\r\\n\", \"\\n\")\n    string.gsub(message_s, \"^(.-\\n)\\n\", function (h) message.headers = h end)\n    string.gsub(message_s, \"^.-\\n\\n(.*)\", function (b) message.body = b end)\n    if not message.body then\n        string.gsub(message_s, \"^\\n(.*)\", function (b) message.body = b end)\n    end\n    if not message.headers and not message.body then\n        message.headers = message_s\n    end\n    return message.headers or \"\", message.body or \"\"\nend\n\nfunction _M.split_headers(headers_s)\n    local headers = {}\n    headers_s = string.gsub(headers_s, \"\\r\\n\", \"\\n\")\n    headers_s = string.gsub(headers_s, \"\\n[ ]+\", \" \")\n    string.gsub(\"\\n\" .. headers_s, \"\\n([^\\n]+)\", function (h) table.insert(headers, h) end)\n    return headers\nend\n\nfunction _M.parse_header(header_s)\n    header_s = string.gsub(header_s, \"\\n[ ]+\", \" \")\n    header_s = string.gsub(header_s, \"\\n+\", \"\")\n    local _, __, name, value = string.find(header_s, \"([^%s:]-):%s*(.*)\")\n    return name, value\nend\n\nfunction _M.parse_headers(headers_s)\n    local headers_t = _M.split_headers(headers_s)\n    local headers = {}\n    for i = 1, #headers_t do\n        local name, value = _M.parse_header(headers_t[i])\n        if name then\n            name = string.lower(name)\n            if headers[name] then\n                headers[name] = headers[name] .. \", \" .. value\n            else headers[name] = value end\n        end\n    end\n    return headers\nend\n\nfunction _M.parse_from(from)\n    local _, __, name, address = string.find(from, \"^%s*(.-)%s*%<(.-)%>\")\n    if not address then\n        _, __, address = string.find(from, \"%s*(.+)%s*\")\n    end\n    name = name or \"\"\n    address = address or \"\"\n    if name == \"\" then name = address end\n    name = string.gsub(name, \'\"\', \"\")\n    return name, address\nend\n\nfunction _M.split_mbox(mbox_s)\n    mbox = {}\n    mbox_s = string.gsub(mbox_s, \"\\r\\n\", \"\\n\") ..\"\\n\\nFrom \\n\"\n    local nj, i, j = 1, 1, 1\n    while 1 ..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"socket.mbox");
  luaL_loadstring(param_1,&DAT_012bedcf);
  lua_setfield(param_1,0xfffffffe,"socket.smtp");
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- Unified SMTP/FTP subsystem\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-----------------------------------------------------------------------------\nlocal base = _G\nlocal string = require(\"string\")\nlocal socket = require(\"socket.socket\")\nlocal ltn12 = require(\"socket.ltn12\")\n\nsocket.tp = {}\nlocal _M = socket.tp\n\n-----------------------------------------------------------------------------\n-- Program constants\n-----------------------------------------------------------------------------\n_M.TIMEOUT = 60\n\n-----------------------------------------------------------------------------\n-- Implementation\n-----------------------------------------------------------------------------\n-- gets server reply (works for SMTP and FTP)\nlocal function get_reply(c)\n    local code, current, sep\n    local line, err = c:receive()\n    local reply = line\n    if err then return nil, err end\n    code, sep = socket.skip(2, string.find(line, \"^(%d%d%d)(.?)\"))\n    if not code then return nil, \"invalid server reply\" end\n    if sep == \"-\" then -- reply is multiline\n        repeat\n            line, err = c:receive()\n            if err then return nil, err end\n            current, sep = socket.skip(2, string.find(line, \"^(%d%d%d)(.?)\"))\n            reply = reply .. \"\\n\" .. line\n        -- reply ends with same code\n        until code == current and sep == \" \"\n    end\n    return code, reply\nend\n\n-- metatable for sock object\nlocal metat = { __index = {} }\n\nfunction metat.__index:check(ok)\n    local code, reply = get_reply(self.c)\n    if not code then return nil, reply end\n    if base.type(ok) ~= \"function\" then\n        if base.type(ok) == \"table\" then\n            for i, v in base.ipairs(ok) do\n                if string.find(code, v) then\n                    return base.tonu..." /* TRUNCATED STRING LITERAL */
                 );
  lua_setfield(param_1,0xfffffffe,"socket.tp");
  luaL_loadstring(param_1,&DAT_012c1b9e);
  lua_setfield(param_1,0xfffffffe,"socket.url");
  luaL_loadstring(param_1,&DAT_012c46bd);
  lua_setfield(param_1,0xfffffffe,"socket");
  lua_settop(param_1,0xfffffffd);
  return;
}

