
undefined8 luaopen_lua_m_mime(undefined8 param_1)

{
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- MIME support for the Lua language.\n-- Author: Diego Nehab\n-- Conforming to RFCs 2045-2049\n-----------------------------------------------------------------------------\n\n-----------------------------------------------------------------------------\n-- Declare module and import dependencies\n-----------------------------------------------------------------------------\nlocal base = _G\nlocal ltn12 = require(\"ltn12\")\nlocal mime = require(\"mime.core\")\nlocal io = require(\"io\")\nlocal string = require(\"string\")\nlocal _M = mime\n\n-- encode, decode and wrap algorithm tables\nlocal encodet, decodet, wrapt = {},{},{}\n\n_M.encodet = encodet\n_M.decodet = decodet\n_M.wrapt   = wrapt  \n\n-- creates a function that chooses a filter by name from a given table\nlocal function choose(table)\n    return function(name, opt1, opt2)\n        if base.type(name) ~= \"string\" then\n            name, opt1, opt2 = \"default\", name, opt1\n        end\n        local f = table[name or \"nil\"]\n        if not f then \n            base.error(\"unknown key (\" .. base.tostring(name) .. \")\", 3)\n        else return f(opt1, opt2) end\n    end\nend\n\n-- define the encoding filters\nencodet[\'base64\'] = function()\n    return ltn12.filter.cycle(_M.b64, \"\")\nend\n\nencodet[\'quoted-printable\'] = function(mode)\n    return ltn12.filter.cycle(_M.qp, \"\",\n        (mode == \"binary\") and \"=0D=0A\" or \"\\r\\n\")\nend\n\n-- define the decoding filters\ndecodet[\'base64\'] = function()\n    return ltn12.filter.cycle(_M.unb64, \"\")\nend\n\ndecodet[\'quoted-printable\'] = function()\n    return ltn12.filter.cycle(_M.unqp, \"\")\nend\n\nlocal function format(chunk)\n    if chunk then\n        if chunk == \"\" then return \"\'\'\"\n        else return string.len(chunk) end\n    else return \"nil\" end\nend\n\n-- define the line-wrap filters\nwrapt[\'text\'] = function(length)\n    length = length or 76\n    return ltn12.filter.cycle(_M.wrp, length, length)\nend\nwrapt[\'base64\'] = wrapt[\'text\']\nwrapt[\'default\'] = wrapt[\'text\']\n\nwrapt[\'quoted-printable\'] = functio..." /* TRUNCATED STRING LITERAL */
                 );
  return 1;
}

