
undefined8 luaopen_lua_m_socket_headers(undefined8 param_1)

{
  luaL_loadstring(param_1,
                  "-----------------------------------------------------------------------------\n-- Canonic header field capitalization\n-- LuaSocket toolkit.\n-- Author: Diego Nehab\n-----------------------------------------------------------------------------\nlocal socket = require(\"socket.socket\")\nsocket.headers = {}\nlocal _M = socket.headers\n\n_M.canonic = {\n    [\"accept\"] = \"Accept\",\n    [\"accept-charset\"] = \"Accept-Charset\",\n    [\"accept-encoding\"] = \"Accept-Encoding\",\n    [\"accept-language\"] = \"Accept-Language\",\n    [\"accept-ranges\"] = \"Accept-Ranges\",\n    [\"action\"] = \"Action\",\n    [\"alternate-recipient\"] = \"Alternate-Recipient\",\n    [\"age\"] = \"Age\",\n    [\"allow\"] = \"Allow\",\n    [\"arrival-date\"] = \"Arrival-Date\",\n    [\"authorization\"] = \"Authorization\",\n    [\"bcc\"] = \"Bcc\",\n    [\"cache-control\"] = \"Cache-Control\",\n    [\"cc\"] = \"Cc\",\n    [\"comments\"] = \"Comments\",\n    [\"connection\"] = \"Connection\",\n    [\"content-description\"] = \"Content-Description\",\n    [\"content-disposition\"] = \"Content-Disposition\",\n    [\"content-encoding\"] = \"Content-Encoding\",\n    [\"content-id\"] = \"Content-ID\",\n    [\"content-language\"] = \"Content-Language\",\n    [\"content-length\"] = \"Content-Length\",\n    [\"content-location\"] = \"Content-Location\",\n    [\"content-md5\"] = \"Content-MD5\",\n    [\"content-range\"] = \"Content-Range\",\n    [\"content-transfer-encoding\"] = \"Content-Transfer-Encoding\",\n    [\"content-type\"] = \"Content-Type\",\n    [\"cookie\"] = \"Cookie\",\n    [\"date\"] = \"Date\",\n    [\"diagnostic-code\"] = \"Diagnostic-Code\",\n    [\"dsn-gateway\"] = \"DSN-Gateway\",\n    [\"etag\"] = \"ETag\",\n    [\"expect\"] = \"Expect\",\n    [\"expires\"] = \"Expires\",\n    [\"final-log-id\"] = \"Final-Log-ID\",\n    [\"final-recipient\"] = \"Final-Recipient\",\n    [\"from\"] = \"From\",\n    [\"host\"] = \"Host\",\n    [\"if-match\"] = \"If-Match\",\n    [\"if-modified-since\"] = \"If-Modified-Since\",\n    [\"if-none-match\"] = \"If-None-Match\",\n    [\"if-range\"] = \"If-Range\",\n    [\"if-unmodified-since\"] = \"If-Unmodified-Since\",\n    [\"in-reply-to\"] = \"In-Reply-To\",\n    [\"keywords\"] = \"Keywords\",\n    [\"last-attempt-date\"] = \"La..." /* TRUNCATED STRING LITERAL */
                 );
  return 1;
}

