
void RC4(RC4_KEY *key,size_t len,uchar *indata,uchar *outdata)

{
  byte *pbVar1;
  uint uVar2;
  byte *pbVar3;
  char cVar4;
  char cVar5;
  char cVar6;
  char cVar7;
  char cVar8;
  char cVar9;
  char cVar10;
  char cVar11;
  char cVar12;
  byte bVar13;
  int iVar14;
  ulong uVar15;
  byte bVar16;
  byte bVar17;
  ulong uVar18;
  long lVar19;
  byte *pbVar20;
  ulong uVar21;
  
  bVar13 = (byte)key->x;
  uVar15 = (ulong)bVar13;
  bVar17 = *(byte *)((long)&key->x + 1);
  uVar18 = len >> 3;
  bVar16 = bVar17;
  if (uVar18 != 0) {
    pbVar3 = indata + (len & 0xfffffffffffffff8);
    lVar19 = -uVar18;
    pbVar20 = outdata;
    do {
      iVar14 = (int)uVar15;
      uVar15 = (ulong)(iVar14 + 1) & 0xff;
      cVar4 = *(char *)((long)key->data + (uVar15 - 6));
      lVar19 = lVar19 + 1;
      cVar12 = cVar4 + bVar17;
      bVar17 = cVar4 + bVar17;
      cVar5 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar5;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar4;
      uVar15 = (ulong)(iVar14 + 2) & 0xff;
      *pbVar20 = *indata ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar5 + cVar4) - 6));
      cVar4 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar4;
      cVar5 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar5;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar4;
      uVar15 = (ulong)(iVar14 + 3) & 0xff;
      pbVar20[1] = indata[1] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar5 + cVar4) - 6));
      cVar5 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar5;
      cVar6 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar6;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar5;
      uVar15 = (ulong)(iVar14 + 4) & 0xff;
      pbVar20[2] = indata[2] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar6 + cVar5) - 6));
      cVar6 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar6;
      cVar7 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar7;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar6;
      uVar15 = (ulong)(iVar14 + 5) & 0xff;
      pbVar20[3] = indata[3] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar7 + cVar6) - 6));
      cVar7 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar7;
      cVar8 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar8;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar7;
      uVar15 = (ulong)(iVar14 + 6) & 0xff;
      pbVar20[4] = indata[4] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar8 + cVar7) - 6));
      cVar8 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar8;
      cVar9 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar9;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar8;
      uVar21 = (ulong)(iVar14 + 7) & 0xff;
      uVar15 = (ulong)(iVar14 + 8);
      pbVar20[5] = indata[5] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar9 + cVar8) - 6));
      cVar9 = *(char *)((long)key->data + (uVar21 - 6));
      bVar17 = bVar17 + cVar9;
      cVar10 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar21 - 6)) = cVar10;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar9;
      pbVar20[6] = indata[6] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar10 + cVar9) - 6));
      cVar10 = *(char *)((long)key->data + ((uVar15 & 0xff) - 6));
      bVar17 = bVar17 + cVar10;
      cVar11 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + ((uVar15 & 0xff) - 6)) = cVar11;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar10;
      pbVar1 = indata + 7;
      indata = indata + 8;
      pbVar20[7] = *pbVar1 ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar11 + cVar10) - 6));
      pbVar20 = pbVar20 + 8;
    } while (lVar19 != 0);
    uVar2 = (uint)bVar13 + (int)uVar18 * 8 + 0x100;
    bVar13 = (byte)uVar2;
    uVar15 = (ulong)uVar2;
    outdata = outdata + (len & 0xfffffffffffffff8);
    bVar16 = cVar12 + cVar4 + cVar5 + cVar6 + cVar7 + cVar8 + cVar9 + cVar10;
    indata = pbVar3;
  }
  if ((len & 7) != 0) {
    lVar19 = 6 - (len & 7);
    do {
      iVar14 = (int)uVar15;
      bVar13 = (byte)(iVar14 + 1U);
      uVar15 = (ulong)(iVar14 + 1U) & 0xff;
      cVar12 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = cVar12 + bVar16;
      cVar4 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar4;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar12;
      *outdata = *indata ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar4 + cVar12) - 6));
      if (lVar19 == 5) break;
      bVar13 = (byte)(iVar14 + 2U);
      uVar15 = (ulong)(iVar14 + 2U) & 0xff;
      cVar4 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar4;
      cVar5 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar5;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar4;
      outdata[1] = indata[1] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar5 + cVar4) - 6));
      if (lVar19 == 4) break;
      bVar13 = (byte)(iVar14 + 3U);
      uVar15 = (ulong)(iVar14 + 3U) & 0xff;
      cVar5 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar5;
      cVar6 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar6;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar5;
      outdata[2] = indata[2] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar6 + cVar5) - 6));
      if (lVar19 == 3) break;
      bVar13 = (byte)(iVar14 + 4U);
      uVar15 = (ulong)(iVar14 + 4U) & 0xff;
      cVar6 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar6;
      cVar7 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar7;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar6;
      outdata[3] = indata[3] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar7 + cVar6) - 6));
      if (lVar19 == 2) break;
      bVar13 = (byte)(iVar14 + 5U);
      uVar15 = (ulong)(iVar14 + 5U) & 0xff;
      cVar7 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar7;
      cVar8 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar8;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar7;
      outdata[4] = indata[4] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar8 + cVar7) - 6));
      if (lVar19 == 1) break;
      bVar13 = (byte)(iVar14 + 6U);
      uVar15 = (ulong)(iVar14 + 6U) & 0xff;
      cVar8 = *(char *)((long)key->data + (uVar15 - 6));
      bVar17 = bVar17 + cVar8;
      cVar9 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + (uVar15 - 6)) = cVar9;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar8;
      outdata[5] = indata[5] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar9 + cVar8) - 6));
      if (lVar19 == 0) break;
      bVar13 = (byte)(iVar14 + 7U);
      uVar15 = (ulong)(iVar14 + 7U);
      cVar9 = *(char *)((long)key->data + ((uVar15 & 0xff) - 6));
      lVar19 = lVar19 + 7;
      bVar16 = cVar12 + bVar16 + cVar4 + cVar5 + cVar6 + cVar7 + cVar8 + cVar9;
      bVar17 = bVar17 + cVar9;
      cVar12 = *(char *)((long)key->data + ((ulong)bVar17 - 6));
      *(char *)((long)key->data + ((uVar15 & 0xff) - 6)) = cVar12;
      *(char *)((long)key->data + ((ulong)bVar17 - 6)) = cVar9;
      outdata[6] = indata[6] ^ *(byte *)((long)key->data + ((ulong)(byte)(cVar12 + cVar9) - 6));
    } while (lVar19 != 6);
  }
  *(byte *)&key->x = bVar13;
  *(byte *)((long)&key->x + 1) = bVar17;
  return;
}

