local HttpDefine = { }

local BASE_HTTP_DEFINE_START = 100000

HttpDefine.askid = 1

-- 商城相关
HttpDefine.URL_STORE_PRODUCT_LIST = BASE_HTTP_DEFINE_START + 1
HttpDefine.URL_STORE_EXCHANGE_PRODUCT_LIST = BASE_HTTP_DEFINE_START + 2
HttpDefine.URL_STORE_EXCHANGE_PRODUCT = BASE_HTTP_DEFINE_START + 3
HttpDefine.URL_STORE_MODIFY_USER_INFO = BASE_HTTP_DEFINE_START + 4
HttpDefine.URL_STORE_SPECIAL_SCENE_GOODS = BASE_HTTP_DEFINE_START + 5

-- 公告
HttpDefine.URL_NOTIFY_ID = BASE_HTTP_DEFINE_START + 4
--礼券商城兑换记录
HttpDefine.URL_TICKETSTORE_EXCHANGE_HISTORY = BASE_HTTP_DEFINE_START + 9
HttpDefine.URL_TICKETSTORE_EXCHANGE_KAMI = BASE_HTTP_DEFINE_START + 10

--请求国外网络
HttpDefine.URL_IS_FOREIGN_IP = BASE_HTTP_DEFINE_START + 17

--H5支付
HttpDefine.H5PAY_INFO = BASE_HTTP_DEFINE_START + 18

--请求优惠卡券接口
HttpDefine.COUPON_INFO = BASE_HTTP_DEFINE_START + 19

--请求优惠卡券兑换
HttpDefine.COUPON_CHANGE = BASE_HTTP_DEFINE_START + 20

HttpDefine.REQ_CACHE_WINDOW = BASE_HTTP_DEFINE_START + 1005
HttpDefine.REQ_GAMEPLAY_REACH = BASE_HTTP_DEFINE_START + 1008 -- 玩法触达IOP列表
HttpDefine.REQ_PHONE_VERIFY_CODE = BASE_HTTP_DEFINE_START + 1006

HttpDefine.REQ_SYSTEMTIME = BASE_HTTP_DEFINE_START + 1007

--礼券商城兑换话费相关
HttpDefine.REQ_SHOP_FEE_PHONE_CODE_CHECK = BASE_HTTP_DEFINE_START + 1012
HttpDefine.REQ_SHOP_FEE_EXCHANGE = BASE_HTTP_DEFINE_START + 1013

--请求H5 游戏 微信注册的UserID
HttpDefine.REQ_H5_WECAHT_USERID = BASE_HTTP_DEFINE_START + 1014

--走风信配置后台链接
HttpDefine.HTTP_ID_DYNAMIC_URL = BASE_HTTP_DEFINE_START + 1015

--绑定功能
HttpDefine.HTTP_ID_DO_BIND_AGENT = BASE_HTTP_DEFINE_START + 1016
HttpDefine.HTTP_ID_RELEASEBIND_AGENT = BASE_HTTP_DEFINE_START + 1017
HttpDefine.HTTP_ID_GETBIND_INFO = BASE_HTTP_DEFINE_START + 1018
HttpDefine.HTTP_ID_GETAGENT_INFO = BASE_HTTP_DEFINE_START + 1019

--杭麻圈分享活动
HttpDefine.HTTP_ID_GETSHARE_INFO = BASE_HTTP_DEFINE_START + 1020
HttpDefine.HTTP_ID_HANGMA_SHARE_AWARD = BASE_HTTP_DEFINE_START + 1021

--领奖中心相关
HttpDefine.HTTP_ID_AWARD_CENTER_RECORD = BASE_HTTP_DEFINE_START + 1022
HttpDefine.HTTP_ID_USER_ADDRESS_GET = BASE_HTTP_DEFINE_START + 1023
HttpDefine.HTTP_ID_USER_ADDRESS_CHANGE = BASE_HTTP_DEFINE_START + 1024
HttpDefine.URL_STORE_PRODUCT_TYPE_LIST = BASE_HTTP_DEFINE_START + 1025

--数据抛送相关
HttpDefine.HTTP_ID_THROW_DATA = BASE_HTTP_DEFINE_START + 1026

--实名认证
HttpDefine.URL_DEFEND_IDENTITY = BASE_HTTP_DEFINE_START + 1027

-- H5入口配置
HttpDefine.HTTP_ID_H5_GAME_SHOE_LIST = BASE_HTTP_DEFINE_START + 1033

-- 大厅Icons
HttpDefine.HTTP_ID_WEB_ICONS = BASE_HTTP_DEFINE_START + 1034

-- 休闲场快捷入口
HttpDefine.HTTP_ID_LEISURE_ENTRANCE = BASE_HTTP_DEFINE_START + 1035

-- 请求Token
HttpDefine.HTTP_ID_REQ_TOKEN = BASE_HTTP_DEFINE_START + 1037

-- 获取所有web维护的联运游戏id
HttpDefine.REQ_H5_WECAHT_ALL_USERID = BASE_HTTP_DEFINE_START + 1038

HttpDefine.HTTP_CALLBACK_TYPE = {
    CALL_BACK_STRING = 0,
    CALL_BACK_ARRAY = 1,
    CALL_BACK_BLOB = 2,
    CALL_BACK_DOCUMENT = 3,
    CALL_BACK_JSON = 4,
}

-- 合规白名单
HttpDefine.URL_LEGITIMACY_CHECK = BASE_HTTP_DEFINE_START + 1039

HttpDefine.URL_LOGOFF_DOCANCLE = BASE_HTTP_DEFINE_START + 1040

HttpDefine.HTTP_ID_LUCK_TASK_GETPAGE = BASE_HTTP_DEFINE_START + 1041
HttpDefine.HTTP_ID_LUCK_TASK_GETCONTENT = BASE_HTTP_DEFINE_START + 1042
HttpDefine.HTTP_ID_LUCK_TASK_GETDRAWLOGS = BASE_HTTP_DEFINE_START + 1043
HttpDefine.HTTP_ID_LUCK_TASK_GETREWARDS = BASE_HTTP_DEFINE_START + 1044
HttpDefine.HTTP_ID_LUCK_TASK_Participate = BASE_HTTP_DEFINE_START + 1045
HttpDefine.HTTP_ID_LUCK_TASK_ACTLIST = BASE_HTTP_DEFINE_START + 1046

HttpDefine.HTTP_ID_PRE_SHUFFLE = BASE_HTTP_DEFINE_START + 1047

-- 配置中心
HttpDefine.HTTP_ID_CONFIGURATION_MD5 = BASE_HTTP_DEFINE_START + 1048
HttpDefine.HTTP_ID_CONFIGURATION_FILE = BASE_HTTP_DEFINE_START + 1049

-- 洗牌5.0
HttpDefine.HTTP_ID_SHUFFLE_5 = BASE_HTTP_DEFINE_START + 1050
HttpDefine.URL_PROP_DISCOUNT = BASE_HTTP_DEFINE_START + 1051
HttpDefine.URL_ACCEPT_PRESENTER = BASE_HTTP_DEFINE_START + 1052

HttpDefine.URL_ARTICLE_LIST = BASE_HTTP_DEFINE_START + 1053
HttpDefine.URL_ARTICLE_THROW = BASE_HTTP_DEFINE_START + 1054

-- sxvip 新版会员
HttpDefine.URL_SXVIP_REMAINER = BASE_HTTP_DEFINE_START + 1055
HttpDefine.URL_SXVIP_CONFIG = BASE_HTTP_DEFINE_START + 1056
HttpDefine.URL_SXVIP_PRIVILEGE = BASE_HTTP_DEFINE_START + 1057
HttpDefine.URL_VIP_PROP_USE_FREE = BASE_HTTP_DEFINE_START + 1058
HttpDefine.URL_SXVIP_FRIEND_INFO = BASE_HTTP_DEFINE_START + 1059
HttpDefine.URL_SXVIP_GAMEPLAY_STATISTICS = BASE_HTTP_DEFINE_START + 1060
HttpDefine.URL_SXVIP_DAILY_REWARD = BASE_HTTP_DEFINE_START + 1061
HttpDefine.URL_SXVIP_FELLOW_SEND = BASE_HTTP_DEFINE_START + 1062

HttpDefine.HTTP_ID_LUCK_TASK_ACTDETAIL = BASE_HTTP_DEFINE_START + 1062
HttpDefine.HTTP_ID_ACT_50_BANKRUPT = BASE_HTTP_DEFINE_START + 1063
HttpDefine.HTTP_ID_ACT_50_DEDUCTIBLE = BASE_HTTP_DEFINE_START + 1064
HttpDefine.HTTP_ID_ACT_50_JOINROOM = BASE_HTTP_DEFINE_START + 1065
HttpDefine.URL_SIGN_DETAIL = BASE_HTTP_DEFINE_START + 1066
HttpDefine.URL_SIGN = BASE_HTTP_DEFINE_START + 1067
HttpDefine.URL_PROPS_COUONT_50 = BASE_HTTP_DEFINE_START + 1068

HttpDefine.URL_SXVIP_PAY_AFTER_SIGN = BASE_HTTP_DEFINE_START + 1069
HttpDefine.HTTP_ID_LIST_LABEL = BASE_HTTP_DEFINE_START + 2071
HttpDefine.HTTP_ID_PEAK_RACE = BASE_HTTP_DEFINE_START + 2072
HttpDefine.HTTP_ID_GETPROPSATTR = BASE_HTTP_DEFINE_START + 2073

HttpDefine.HTTP_ID_USE_EQUIP_CARD = BASE_HTTP_DEFINE_START + 1071
HttpDefine.HTTP_ID_USER_LOCATION = BASE_HTTP_DEFINE_START + 1072
HttpDefine.HTTP_ID_GET_GOLD_BILL = BASE_HTTP_DEFINE_START + 1073
HttpDefine.URL_SXVIP_REPORT_DATA = BASE_HTTP_DEFINE_START + 1074
HttpDefine.HTTP_ID_GET_GOLD_STATISTICS = BASE_HTTP_DEFINE_START + 1075

HttpDefine.HTTP_ID_SCORE_ASSISTANT = BASE_HTTP_DEFINE_START + 1076

HttpDefine.HTTP_ID_REQ_KICK_TIMES = BASE_HTTP_DEFINE_START + 1077
HttpDefine.HTTP_ID_CONTRIBUTE = BASE_HTTP_DEFINE_START + 1078
HttpDefine.HTTP_ID_CHOOSE_RANK = BASE_HTTP_DEFINE_START + 1079
HttpDefine.HTTP_ID_CLUB_RANK_RECORD = BASE_HTTP_DEFINE_START + 1080

HttpDefine.HTTP_ID_DO_BANKRUPTCY_AD = BASE_HTTP_DEFINE_START + 1081
HttpDefine.HTTP_ID_SHUFFLE_PLAN = BASE_HTTP_DEFINE_START + 1082

HttpDefine.HTTP_ID_ACT_TIME_LOGIN = BASE_HTTP_DEFINE_START + 1082
HttpDefine.HTTP_ID_CLAIM_LOGIN_REWARD = BASE_HTTP_DEFINE_START + 1083

HttpDefine.HTTP_ID_URL_AUTH_GETCODE = BASE_HTTP_DEFINE_START + 1084
HttpDefine.HTTP_ID_PHONE_BIND = BASE_HTTP_DEFINE_START + 1085

HttpDefine.HTTP_ID_GOLDFIRSTPAYGIFT_REQUEST = BASE_HTTP_DEFINE_START + 2001
HttpDefine.HTTP_ID_GOLD_RECORD_REQUEST = BASE_HTTP_DEFINE_START + 2002
HttpDefine.HTTP_ID_GOLD_PEGP_INFO_REQUEST = BASE_HTTP_DEFINE_START + 2003
HttpDefine.HTTP_ID_GOLD_PEGP_GETAWARD_REQUEST = BASE_HTTP_DEFINE_START + 2004
HttpDefine.HTTP_ID_GOLD_CRITHOFRANKLIST = BASE_HTTP_DEFINE_START + 2005
HttpDefine.HTTP_ID_GOLD_CRITHOFUSERINFO = BASE_HTTP_DEFINE_START + 2006
HttpDefine.HTTP_ID_GOLD_CRITHOFGETUSERRANKINFO = BASE_HTTP_DEFINE_START + 2007
HttpDefine.HTTP_ID_GOLD_CRITHOFBASEINFO = BASE_HTTP_DEFINE_START + 2008
HttpDefine.HTTP_ID_GOLD_CRITHOFGETCRITAWARD = BASE_HTTP_DEFINE_START + 2009
HttpDefine.HTTP_ID_SHOP_GOODS_LIST = BASE_HTTP_DEFINE_START + 2101
HttpDefine.HTTP_ID_SHOP_REPORT_ORDER = BASE_HTTP_DEFINE_START + 2102
HttpDefine.HTTP_ID_SHOP_CHECK_ORDER = BASE_HTTP_DEFINE_START + 2103
HttpDefine.HTTP_ID_EXCHANGE_GOODS_LIST = BASE_HTTP_DEFINE_START + 2104
HttpDefine.HTTP_ID_EXCHANGE_GOODS = BASE_HTTP_DEFINE_START + 2105

HttpDefine.URL_SXVIP_SEARCH_USERO = BASE_HTTP_DEFINE_START + 1093

HttpDefine.URL_ACT_VIP_DISCOUNT = BASE_HTTP_DEFINE_START + 1094
HttpDefine.URL_ACT_DETAILS = BASE_HTTP_DEFINE_START + 1095

-- 暗斗双扣
HttpDefine.HTTP_ID_REVIVE_GIFT = BASE_HTTP_DEFINE_START + 1096
HttpDefine.HTTP_ID_GET_TEACHING_INFO = BASE_HTTP_DEFINE_START + 1097
HttpDefine.HTTP_ID_COMPLETE_TEACHING = BASE_HTTP_DEFINE_START + 1098
HttpDefine.HTTP_ID_GAME_ROUND_CHALLENGE = BASE_HTTP_DEFINE_START + 1099
HttpDefine.HTTP_ID_DAILY_QUIZ_CHALLENGE = BASE_HTTP_DEFINE_START + 1100
HttpDefine.HTTP_ID_ANSWER = BASE_HTTP_DEFINE_START + 1101
HttpDefine.HTTP_ID_CARD_SKILL_CHALLENGE = BASE_HTTP_DEFINE_START + 1102
HttpDefine.HTTP_ID_CHALLENGE_GET_AWARD = BASE_HTTP_DEFINE_START + 1103

HttpDefine.HTTP_ID_WU_XIAN_JIN_BI_INFO = BASE_HTTP_DEFINE_START + 1107
HttpDefine.HTTP_ID_WU_XIAN_JIN_BI_OPT = BASE_HTTP_DEFINE_START + 1108
HttpDefine.HTTP_ID_WU_XIAN_DUI_JU_INFO = BASE_HTTP_DEFINE_START + 1113
HttpDefine.HTTP_ID_WU_XIAN_DUI_JU_OPT = BASE_HTTP_DEFINE_START + 1114
-- 50金币回放
HttpDefine.URL_GOLD50_PLAYBACK = BASE_HTTP_DEFINE_START + 1104

-- 战令
HttpDefine.HTTP_ID_BATTLE_PASS = BASE_HTTP_DEFINE_START + 1105
HttpDefine.HTTP_ID_GET_POOL_PRIZES = BASE_HTTP_DEFINE_START + 1106
HttpDefine.HTTP_ID_UNLIMITED_GIFT_INFO = BASE_HTTP_DEFINE_START + 1107
HttpDefine.HTTP_ID_UNLIMITED_GIFT_REWARD = BASE_HTTP_DEFINE_START + 1108

-- 会员优化
HttpDefine.URL_SXVIP_GAME_STATISTICS = BASE_HTTP_DEFINE_START + 1109
HttpDefine.URL_SXVIP_GAME_RECORD = BASE_HTTP_DEFINE_START + 1110
HttpDefine.URL_SXVIP_GET_SINGLE_RIGHT = BASE_HTTP_DEFINE_START + 1111
HttpDefine.URL_SXVIP_LOCK_SINGLE_RIGHT = BASE_HTTP_DEFINE_START + 1112


HttpDefine.HTTP_ID_CHANGECARD = BASE_HTTP_DEFINE_START + 1113


HttpDefine.HTTP_ID_USER_IS_SUB_VIP = BASE_HTTP_DEFINE_START + 1114
-- 包厢转化
HttpDefine.URL_BOX_GUIDE_INFO = BASE_HTTP_DEFINE_START + 1115
HttpDefine.URL_BOX_CREATE_FREE_CHECK = BASE_HTTP_DEFINE_START + 1116
HttpDefine.URL_BOX_CREATE_FREE_GAIN = BASE_HTTP_DEFINE_START + 1117

HttpDefine.HTTP_ID_LUCKY_BAG = BASE_HTTP_DEFINE_START + 1118
HttpDefine.HTTP_ID_URL_OPERATE_EQUIP = BASE_HTTP_DEFINE_START + 1119
HttpDefine.HTTP_ID_GET_EQUIP_STATE = BASE_HTTP_DEFINE_START + 1120
HttpDefine.HTTP_ID_GET_SYSTIME_50 = BASE_HTTP_DEFINE_START + 1121

HttpDefine.HTTP_ID_REAL_NAME_SUPPLEMENT = BASE_HTTP_DEFINE_START + 1122

HttpDefine.URL_MAIL_CHECKNEW = BASE_HTTP_DEFINE_START + 1123
HttpDefine.URL_MAIL_LIST = BASE_HTTP_DEFINE_START + 1124
HttpDefine.URL_MAIL_DETAIL = BASE_HTTP_DEFINE_START + 1125
HttpDefine.URL_MAIL_READALL = BASE_HTTP_DEFINE_START + 1126
HttpDefine.URL_MAIL_DEL = BASE_HTTP_DEFINE_START + 1127
HttpDefine.URL_MAIL_GETAWARD = BASE_HTTP_DEFINE_START + 1128

HttpDefine.HTTP_ID_PAY_CONSULT = BASE_HTTP_DEFINE_START + 1129
HttpDefine.HTTP_ID_RECALL_NEW_SUPPORT_INFO = BASE_HTTP_DEFINE_START + 1130
HttpDefine.HTTP_ID_RECALL_NEW_SUPPORT = BASE_HTTP_DEFINE_START + 1131
HttpDefine.HTTP_ID_RECALL_NEW_LIST_CLUB = BASE_HTTP_DEFINE_START + 1132
HttpDefine.HTTP_ID_RECALL_NEW_QUERY_CLUB = BASE_HTTP_DEFINE_START + 1133
HttpDefine.HTTP_ID_RECALL_NEW_REWARD_CLUB = BASE_HTTP_DEFINE_START + 1134
HttpDefine.HTTP_ID_RECALL_NEW_NOTIFY_INVITE = BASE_HTTP_DEFINE_START + 1135
HttpDefine.HTTP_ID_RECALL_NEW_RED_POINT = BASE_HTTP_DEFINE_START + 1136
HttpDefine.HTTP_ID_RECALL_NEW_CLICK_BACK = BASE_HTTP_DEFINE_START + 1137
HttpDefine.HTTP_ID_RECALL_NEW_BASE_INFO = BASE_HTTP_DEFINE_START + 1138
HttpDefine.HTTP_ID_RECALL_NEW_BACK_GIFT = BASE_HTTP_DEFINE_START + 1139
HttpDefine.HTTP_ID_RECALL_NEW_SIGN_INFO = BASE_HTTP_DEFINE_START + 1140
HttpDefine.HTTP_ID_RECALL_NEW_SIGN = BASE_HTTP_DEFINE_START + 1141
HttpDefine.HTTP_ID_RECALL_NEW_TASK_INFO = BASE_HTTP_DEFINE_START + 1142
HttpDefine.HTTP_ID_RECALL_NEW_NOTIFY_TASK = BASE_HTTP_DEFINE_START + 1143
HttpDefine.HTTP_ID_RECALL_NEW_REWARD_TASK = BASE_HTTP_DEFINE_START + 1144
HttpDefine.HTTP_ID_RECALL_NEW_TASK_STAGE = BASE_HTTP_DEFINE_START + 1145
HttpDefine.HTTP_ID_JUBAOPEN = BASE_HTTP_DEFINE_START + 1146

HttpDefine.HTTP_ID_TASK_V2_REQUEST = BASE_HTTP_DEFINE_START + 1147
HttpDefine.HTTP_ID_ACT_POINT_REWARDS_REQUEST = BASE_HTTP_DEFINE_START + 1148
HttpDefine.HTTP_ID_TASK_V2_REWARD_REQUEST = BASE_HTTP_DEFINE_START + 1149

HttpDefine.HTTP_ID_MONTHLY_CARD_INFO = BASE_HTTP_DEFINE_START + 1150
HttpDefine.HTTP_ID_GET_MONTHLY_CARD = BASE_HTTP_DEFINE_START + 1151
HttpDefine.HTTP_ID_TASK_V2_FINISH_REQUEST = BASE_HTTP_DEFINE_START + 1152

HttpDefine.HTTP_ID_LIST_HALL_FRIEND = BASE_HTTP_DEFINE_START + 1153
HttpDefine.HTTP_ID_CLUBSET = BASE_HTTP_DEFINE_START + 1154
HttpDefine.HTTP_ID_CLUBAPPLYFRIENDS = BASE_HTTP_DEFINE_START + 1155
HttpDefine.HTTP_ID_APPLYJOINCLUB = BASE_HTTP_DEFINE_START + 1156
HttpDefine.HTTP_ID_DEALJOINCLUB = BASE_HTTP_DEFINE_START + 1157
HttpDefine.HTTP_ID_DOUBLE12_INFO = BASE_HTTP_DEFINE_START + 1158
HttpDefine.HTTP_ID_DOUBLE12_AWARD = BASE_HTTP_DEFINE_START + 1159

HttpDefine.HTTP_ID_FINISHBILL_CLOSE = BASE_HTTP_DEFINE_START + 1160
HttpDefine.HTTP_ID_FEE_INFO = BASE_HTTP_DEFINE_START + 1161
HttpDefine.HTTP_ID_FEE_RECHARGE = BASE_HTTP_DEFINE_START + 1162
HttpDefine.HTTP_ID_SHARE_WIN_INFO = BASE_HTTP_DEFINE_START + 1163
HttpDefine.HTTP_ID_GET_SHARE_WIN_AWARD = BASE_HTTP_DEFINE_START + 1164
HttpDefine.HTTP_ID_SHARE_DETAIL = BASE_HTTP_DEFINE_START + 1165
HttpDefine.HTTP_ID_SHARE_REWARD = BASE_HTTP_DEFINE_START + 1166

HttpDefine.HTTP_CHANGE_CLUB_MODE = BASE_HTTP_DEFINE_START + 1168
HttpDefine.HTTP_ID_GET_SHARETYPE = BASE_HTTP_DEFINE_START + 1170

HttpDefine.HTTP_ID_GENERATE_TEMP_UUID = BASE_HTTP_DEFINE_START + 1171
HttpDefine.HTTP_ID_QUERY_TOKEN = BASE_HTTP_DEFINE_START + 1172

-- 新推广活动配置
HttpDefine.HTTP_ID_NEW_GAME_SPREAD_INFO = BASE_HTTP_DEFINE_START + 1173
HttpDefine.HTTP_ID_NEW_GAME_SPREAD_TASK = BASE_HTTP_DEFINE_START + 1174
HttpDefine.HTTP_ID_NEW_GAME_SPREAD_AWARD = BASE_HTTP_DEFINE_START + 1175

HttpDefine.HTTP_ID_GAMECENTER = BASE_HTTP_DEFINE_START + 1176

-- 上次登录信息（juno）
HttpDefine.HTTP_ID_GET_LAST_LOGIN_INFO = BASE_HTTP_DEFINE_START + 1177

-- 道具推送 RecommendProp
HttpDefine.HTTP_ID_PROPPUSH = BASE_HTTP_DEFINE_START + 1178

return HttpDefine�6