-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "温州关牌", order = 1, SpeakText = "人都等睡着了", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "温州关牌", order = 2, SpeakText = "动作快点~", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "温州关牌", order = 3, SpeakText = "看大字报?", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "温州关牌", order = 4, SpeakText = "快打快打!", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "温州关牌", order = 5, SpeakText = "没味儿", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "温州关牌", order = 6, SpeakText = "逃哪里去", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "温州关牌", order = 7, SpeakText = "形式看透西", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "温州关牌", order = 8, SpeakText = "定点!别慌", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 109, GameName = "温州关牌", order = 9, SpeakText = "自打错了没怨", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 110, GameName = "温州关牌", order = 10, SpeakText = "你凶西", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "温州关牌", order = 11, SpeakText = "一世痛苦", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 112, GameName = "温州关牌", order = 12, SpeakText = "牌像中石油", M_SpeakFileName = "M_Speak112.mp3", W_SpeakFileName = "W_Speak112.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 113, GameName = "温州关牌", order = 13, SpeakText = "南斯拉夫", M_SpeakFileName = "M_Speak113.mp3", W_SpeakFileName = "W_Speak113.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 114, GameName = "温州关牌", order = 14, SpeakText = "快来那", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 115, GameName = "温州关牌", order = 15, SpeakText = "强生针", M_SpeakFileName = "M_Speak115.mp3", W_SpeakFileName = "W_Speak115.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 116, GameName = "温州关牌", order = 16, SpeakText = "关公面前耍大刀", M_SpeakFileName = "M_Speak116.mp3", W_SpeakFileName = "W_Speak116.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 117, GameName = "温州关牌", order = 17, SpeakText = "哈哈，偷机", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 118, GameName = "温州关牌", order = 18, SpeakText = "糖金杏捣裂", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 119, GameName = "温州关牌", order = 19, SpeakText = "人毛嫌刀钝", M_SpeakFileName = "M_Speak119.mp3", W_SpeakFileName = "W_Speak119.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 120, GameName = "温州关牌", order = 20, SpeakText = "赖歪肉吃不壮", M_SpeakFileName = "M_Speak120.mp3", W_SpeakFileName = "W_Speak120.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab