-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	MahjongAnimation = {
		{ ConfID = 1, AnimationDescription = "吃碰杠胡动画", DirName = "cardtype_ani", JsonName = "cardtype_ani", AniNameList = { "chi", "peng", "hu", "gang", "angang", "ruanbao", "yingbao", "menhu", "tianting" } 	},
		{ ConfID = 2, AnimationDescription = "骰子动画", DirName = "saizi_ani", JsonName = "saizi_ani", AniNameList = { "loop", "1", "2", "3", "4", "5", "6" } 	},
		{ ConfID = 3, AnimationDescription = "飘财动画", DirName = "caishen_ani", JsonName = "caishen_ani", AniNameList = { "caishen_ani" } 	}
	}

}


-- ConfID
tab.MahjongAnimationByConfID = {}
for _, rec in pairs(tab.MahjongAnimation) do
	tab.MahjongAnimationByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab-