-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameSpeakConfig = {
		{ ConfID = 1001, index = 101, GameName = "衢州关牌", order = 1, SpeakText = "打到天亮", M_SpeakFileName = "M_Speak101.mp3", W_SpeakFileName = "W_Speak101.mp3", listIndex = 1 	},
		{ ConfID = 1002, index = 102, GameName = "衢州关牌", order = 2, SpeakText = "关公面前耍大刀", M_SpeakFileName = "M_Speak102.mp3", W_SpeakFileName = "W_Speak102.mp3", listIndex = 1 	},
		{ ConfID = 1003, index = 103, GameName = "衢州关牌", order = 3, SpeakText = "全是炸弹，要赢啦", M_SpeakFileName = "M_Speak103.mp3", W_SpeakFileName = "W_Speak103.mp3", listIndex = 1 	},
		{ ConfID = 1004, index = 104, GameName = "衢州关牌", order = 4, SpeakText = "哈哈哈，我先走啦", M_SpeakFileName = "M_Speak104.mp3", W_SpeakFileName = "W_Speak104.mp3", listIndex = 1 	},
		{ ConfID = 1005, index = 105, GameName = "衢州关牌", order = 5, SpeakText = "黄花菜都凉啦", M_SpeakFileName = "M_Speak105.mp3", W_SpeakFileName = "W_Speak105.mp3", listIndex = 1 	},
		{ ConfID = 1006, index = 106, GameName = "衢州关牌", order = 6, SpeakText = "好牌都被偷走了吧", M_SpeakFileName = "M_Speak106.mp3", W_SpeakFileName = "W_Speak106.mp3", listIndex = 1 	},
		{ ConfID = 1007, index = 107, GameName = "衢州关牌", order = 7, SpeakText = "决战到底！", M_SpeakFileName = "M_Speak107.mp3", W_SpeakFileName = "W_Speak107.mp3", listIndex = 1 	},
		{ ConfID = 1008, index = 108, GameName = "衢州关牌", order = 8, SpeakText = "癞皮狗，爽不久", M_SpeakFileName = "M_Speak108.mp3", W_SpeakFileName = "W_Speak108.mp3", listIndex = 1 	},
		{ ConfID = 1009, index = 109, GameName = "衢州关牌", order = 9, SpeakText = "你们就等着输吧", M_SpeakFileName = "M_Speak109.mp3", W_SpeakFileName = "W_Speak109.mp3", listIndex = 1 	},
		{ ConfID = 1010, index = 110, GameName = "衢州关牌", order = 10, SpeakText = "牌都捏烂了，赶紧打", M_SpeakFileName = "M_Speak110.mp3", W_SpeakFileName = "W_Speak110.mp3", listIndex = 1 	},
		{ ConfID = 1011, index = 111, GameName = "衢州关牌", order = 11, SpeakText = "牌太好，我也没办法~", M_SpeakFileName = "M_Speak111.mp3", W_SpeakFileName = "W_Speak111.mp3", listIndex = 1 	},
		{ ConfID = 1012, index = 112, GameName = "衢州关牌", order = 12, SpeakText = "就你的牌打得最好咯", M_SpeakFileName = "M_Speak112.mp3", W_SpeakFileName = "W_Speak112.mp3", listIndex = 1 	},
		{ ConfID = 1013, index = 113, GameName = "衢州关牌", order = 13, SpeakText = "扔炸弹啊", M_SpeakFileName = "M_Speak113.mp3", W_SpeakFileName = "W_Speak113.mp3", listIndex = 1 	},
		{ ConfID = 1014, index = 114, GameName = "衢州关牌", order = 14, SpeakText = "手气太差了，怎么回事", M_SpeakFileName = "M_Speak114.mp3", W_SpeakFileName = "W_Speak114.mp3", listIndex = 1 	},
		{ ConfID = 1015, index = 115, GameName = "衢州关牌", order = 15, SpeakText = "我去，这烂牌看不下去", M_SpeakFileName = "M_Speak115.mp3", W_SpeakFileName = "W_Speak115.mp3", listIndex = 1 	},
		{ ConfID = 1016, index = 116, GameName = "衢州关牌", order = 16, SpeakText = "能不能给力点", M_SpeakFileName = "M_Speak116.mp3", W_SpeakFileName = "W_Speak116.mp3", listIndex = 1 	},
		{ ConfID = 1017, index = 117, GameName = "衢州关牌", order = 17, SpeakText = "下次还要和你做搭档", M_SpeakFileName = "M_Speak117.mp3", W_SpeakFileName = "W_Speak117.mp3", listIndex = 1 	},
		{ ConfID = 1018, index = 118, GameName = "衢州关牌", order = 18, SpeakText = "再不出牌，都要发霉啦", M_SpeakFileName = "M_Speak118.mp3", W_SpeakFileName = "W_Speak118.mp3", listIndex = 1 	},
		{ ConfID = 1019, index = 119, GameName = "衢州关牌", order = 19, SpeakText = "再来一局", M_SpeakFileName = "M_Speak119.mp3", W_SpeakFileName = "W_Speak119.mp3", listIndex = 1 	},
		{ ConfID = 1020, index = 120, GameName = "衢州关牌", order = 20, SpeakText = "怎么这么木像", M_SpeakFileName = "M_Speak120.mp3", W_SpeakFileName = "W_Speak120.mp3", listIndex = 1 	},
		{ ConfID = 1021, index = 121, GameName = "衢州关牌", order = 21, SpeakText = "炸弹不炸带回家啊！", M_SpeakFileName = "M_Speak121.mp3", W_SpeakFileName = "W_Speak121.mp3", listIndex = 1 	},
		{ ConfID = 1022, index = 122, GameName = "衢州关牌", order = 22, SpeakText = "炸弹拿着当宝啊！", M_SpeakFileName = "M_Speak122.mp3", W_SpeakFileName = "W_Speak122.mp3", listIndex = 1 	}
	}

}


-- ConfID
tab.GameSpeakConfigByConfID = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByConfID[rec.ConfID] = rec
end

-- index
tab.GameSpeakConfigByindex = {}
for _, rec in pairs(tab.GameSpeakConfig) do
	tab.GameSpeakConfigByindex[rec.index] = rec
end

tab.Enum = {
}

return tab