package com.kwad.sdk.core.config;

import com.bykv.vk.openvk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import java.util.ArrayList;

public final class c {
    public static k akm = new k("batchReportCatchLimit", 20);
    public static k akn = new k("exceptionCollectorSwitch", 1);
    public static k ako = new k("mediaPlayerLogReport", 0);
    public static k akp = new k("didCopySwitch", 1);
    public static k akq = new k("enableHodor", 0);
    public static k akr = new k("speedLimitSwitch", 1);
    public static k aks = new k("speedLimitThreshold", 200);
    public static k akt = new k("ksNativeAdCustomSwitch", 0);
    public static k aku = new k("forceActivateAfterInstalled", 0);
    public static k akv = new k("spliceVideoInteractionType", 0);
    public static k akw = new k("feedPreLoadOptimze", 0);
    public static k akx = new k("formAdExitInterceptSwitch", 0);
    public static k aky = new k("adLeaveConfirmSwitch", 0);
    public static k akz = new k("viewLandingPageTaskDuration", 15);
    public static k akA = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d akB = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static m akC = new m("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d akD = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d akE = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static k akF = new k("commercialLoggerSwitch", 1);
    public static p akG = new p("tkSoUrlV7a", "");
    public static p akH = new p("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d akI = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l akJ = new l("playerConfig", null);
    public static q akK = new q("pkgNameList", new ArrayList(0));
    public static q akL = new q("hostList", new ArrayList(0));
    public static q akM = new q("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem akN = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c akO = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem akP = new InstallActivateReminderConfigItem();
    public static e akQ = new e();
    public static n akR = new n("realtimeReportActions", "");
    public static o akS = new o();
    public static k akT = new k("appInstallNoticeSecond", 0);
    public static k akU = new k("installFloatingLayerPostion", 0);
    public static k akV = new k("remindInstallStyle", 0);
    public static k akW = new k("remindInstallTime", 60);
    public static k akX = new k("watermarkKwaiIdSwitch", 0);
    public static k akY = new k("insertScreenV2Switch", 0);
    public static k akZ = new k("insertScreenAutoPlaySwitch", 0);
    public static j ala = new j("insertScreenV2ShowConfig");
    public static k alb = new k("environmentDetectEnable", 0);
    public static k alc = new k("simCardInfoEnable", 0);
    public static k ald = new k("baseStationEnable", 0);
    public static k ale = new k("sensorEventEnable2", 0);
    public static k alf = new k("lpAutoDownloadApkSwitch", 1);
    public static k alg = new k("autoDownloadUrlSwitch", 0);
    public static k alh = new k("insertScreenAdType", 0);
    public static k ali = new k("interstitialAutoCallAppCountDaily", 1);
    public static k alj = new k("mediaControlPlaySwitch", 1);
    public static p alk = new p("appStatusSoUrlV7a", "");
    public static p all = new p("appStatusSoUrlV8a", "");
    public static p alm = new p("appStatusSoVersion", "");
    public static k aln = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d alo = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h alp = new h();
    public static com.kwad.sdk.core.config.item.d alq = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d alr = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d als = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d alt = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d alu = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k alv = new k("forceActivate", 0);
    public static k alw = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d alx = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static k aly = new k("enableAnrReportReal", 0);
    public static k alz = new k("enableNativeCrashReport", 0);
    public static p alA = new p("exceptionSoUrlV7a", "");
    public static p alB = new p("exceptionSoUrlV8a", "");
    public static k alC = new k("kwaiAppVersionSwitch", 1);
    public static p alD = new p(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.q.getDefaultUserAgent());
    public static k alE = new k("biddingLogSwitch", 0);
    public static k alF = new k("forceActiveThreshold", 5);
    public static k alG = new k("forceActiveInterval", 3);
    public static k alH = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d alI = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g alJ = new g("adExposureAreaPercent", 0.3f);
    public static g alK = new g("adExposureTime", -1.0f);
    public static g alL = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d alM = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d alN = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k alO = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d alP = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k alQ = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d alR = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d alS = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static m alT = new m("obiwanLogFilesDiskQuota", 52428800L);
    public static l alU = new l("logCommandResult", "", false);
    public static m alV = new m("validClickConvertTime", 1000L);
    public static k alW = new k("playableAutoPlayEnable", 1);
    public static k alX = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d alY = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d alZ = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k ama = new k("weaponSwitch", 1);
    public static k amb = new k("kvModeV2", 0);
    public static i amc = new i();
    public static m amd = new m("currentServerTimeMs");
    public static k ame = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g amf = new g("adTraceReportRate", 1.0f);
    public static k amg = new k("adTraceRepeatEnable", 0);
    public static k amh = new k("appHeartBeatInterval", 0);
    public static k ami = new k("adCacheCode", 0);
    public static p amj = new p("installTipsContentDesc", "");
    public static p amk = new p("installTipsPositiveActionDesc", "");
    public static p aml = new p("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d amm = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static p amn = new p("perfMonitorV2", "");
    public static k amo = new k("neoVideoAdaptStrategy", 1);
    public static com.kwad.sdk.core.config.item.d amp = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static com.kwad.sdk.core.config.item.d amq = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static p amr = new p("ranger", "");
    public static p ams = new p("threadPoolPerfMonitor", "");
    public static p amt = new p("threadPoolParams", "");
    public static f amu = new f("crashUploadRate", Double.valueOf(1.0d));
    public static com.kwad.sdk.core.config.item.d amv = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d amw = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d amx = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", true);
    public static com.kwad.sdk.core.config.item.d amy = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);

    public static void init() {
    }
}
