local HttpDefine = { }

local BASE_HTTP_DEFINE_START = 100000

HttpDefine.askid = 1

-- 商城相关
HttpDefine.URL_STORE_PRODUCT_LIST = BASE_HTTP_DEFINE_START + 1
HttpDefine.URL_STORE_EXCHANGE_PRODUCT_LIST = BASE_HTTP_DEFINE_START + 2
HttpDefine.URL_STORE_EXCHANGE_PRODUCT = BASE_HTTP_DEFINE_START + 3
HttpDefine.URL_STORE_MODIFY_USER_INFO = BASE_HTTP_DEFINE_START + 4
HttpDefine.URL_STORE_SPECIAL_SCENE_GOODS = BASE_HTTP_DEFINE_START + 5

-- 公告
HttpDefine.URL_NOTIFY_ID = BASE_HTTP_DEFINE_START + 4
--礼券商城兑换记录
HttpDefine.URL_TICKETSTORE_EXCHANGE_HISTORY = BASE_HTTP_DEFINE_START + 9
HttpDefine.URL_TICKETSTORE_EXCHANGE_KAMI = BASE_HTTP_DEFINE_START + 10

--请求国外网络
HttpDefine.URL_IS_FOREIGN_IP = BASE_HTTP_DEFINE_START + 17

--H5支付
HttpDefine.H5PAY_INFO = BASE_HTTP_DEFINE_START + 18

--请求优惠卡券接口
HttpDefine.COUPON_INFO = BASE_HTTP_DEFINE_START + 19

--请求优惠卡券兑换
HttpDefine.COUPON_CHANGE = BASE_HTTP_DEFINE_START + 20

-- 提审行为采集
HttpDefine.HTTP_TI_SHEN_ACTIVITY_COLLECT = BASE_HTTP_DEFINE_START + 100

--首冲活动
HttpDefine.REQ_FIRST_CHARGE_INFO = BASE_HTTP_DEFINE_START + 1001
HttpDefine.REQ_FIRST_CHARGE_GET_AWARD = BASE_HTTP_DEFINE_START + 1002

--2020春节活动
HttpDefine.REQ_PLAYER_INFO = BASE_HTTP_DEFINE_START + 1003
HttpDefine.REQ_DROP_CARD = BASE_HTTP_DEFINE_START + 1004

HttpDefine.REQ_CACHE_WINDOW = BASE_HTTP_DEFINE_START + 1005
HttpDefine.REQ_PHONE_VERIFY_CODE = BASE_HTTP_DEFINE_START + 1006

HttpDefine.REQ_SYSTEMTIME = BASE_HTTP_DEFINE_START + 1007

--砍价活动
HttpDefine.REQ_GET_AWARD_RECORD = BASE_HTTP_DEFINE_START + 1009
HttpDefine.REQ_USER_INFO = BASE_HTTP_DEFINE_START + 1010
HttpDefine.REQ_SET_USER_INFO = BASE_HTTP_DEFINE_START + 1011

--B端迁移活动请求
HttpDefine.REQ_ZJ_AGENT_TRANSINFO = BASE_HTTP_DEFINE_START + 1009
HttpDefine.REQ_ZJ_AGENT_TRANSUSER = BASE_HTTP_DEFINE_START + 1010
HttpDefine.REQ_ZJ_TRANSFER_CHECKBIND = BASE_HTTP_DEFINE_START + 1011

--礼券商城兑换话费相关
HttpDefine.REQ_SHOP_FEE_PHONE_CODE_CHECK = BASE_HTTP_DEFINE_START + 1012
HttpDefine.REQ_SHOP_FEE_EXCHANGE = BASE_HTTP_DEFINE_START + 1013

--请求H5 游戏 微信注册的UserID
HttpDefine.REQ_H5_WECAHT_USERID = BASE_HTTP_DEFINE_START + 1014

--走风信配置后台链接
HttpDefine.HTTP_ID_DYNAMIC_URL = BASE_HTTP_DEFINE_START + 1015

--绑定功能
HttpDefine.HTTP_ID_DO_BIND_AGENT = BASE_HTTP_DEFINE_START + 1016
HttpDefine.HTTP_ID_RELEASEBIND_AGENT = BASE_HTTP_DEFINE_START + 1017
HttpDefine.HTTP_ID_GETBIND_INFO = BASE_HTTP_DEFINE_START + 1018
HttpDefine.HTTP_ID_GETAGENT_INFO = BASE_HTTP_DEFINE_START + 1019

--杭麻圈分享活动
HttpDefine.HTTP_ID_GETSHARE_INFO = BASE_HTTP_DEFINE_START + 1020
HttpDefine.HTTP_ID_HANGMA_SHARE_AWARD = BASE_HTTP_DEFINE_START + 1021

--领奖中心相关
HttpDefine.HTTP_ID_AWARD_CENTER_RECORD = BASE_HTTP_DEFINE_START + 1022
HttpDefine.HTTP_ID_USER_ADDRESS_GET = BASE_HTTP_DEFINE_START + 1023
HttpDefine.HTTP_ID_USER_ADDRESS_CHANGE = BASE_HTTP_DEFINE_START + 1024
HttpDefine.URL_STORE_PRODUCT_TYPE_LIST = BASE_HTTP_DEFINE_START + 1025

--数据抛送相关
HttpDefine.HTTP_ID_THROW_DATA = BASE_HTTP_DEFINE_START + 1026

--实名认证
HttpDefine.URL_DEFEND_IDENTITY = BASE_HTTP_DEFINE_START + 1027

--裂变活动
HttpDefine.HTTP_ID_INVITE_NEW_HISTORY = BASE_HTTP_DEFINE_START + 1028
HttpDefine.HTTP_ID_INVITE_NEW_GET_ALL_AWARD = BASE_HTTP_DEFINE_START + 1029
HttpDefine.HTTP_ID_INVITE_NEW_GET_AWARD = BASE_HTTP_DEFINE_START + 1030
HttpDefine.HTTP_ID_INVITE_NEW_INFO = BASE_HTTP_DEFINE_START + 1031
HttpDefine.HTTP_ID_INVITE_NEW_TIPS = BASE_HTTP_DEFINE_START + 1032

-- H5入口配置
HttpDefine.HTTP_ID_H5_GAME_SHOE_LIST = BASE_HTTP_DEFINE_START + 1033

-- 大厅Icons
HttpDefine.HTTP_ID_WEB_ICONS = BASE_HTTP_DEFINE_START + 1034

-- 休闲场快捷入口
HttpDefine.HTTP_ID_LEISURE_ENTRANCE = BASE_HTTP_DEFINE_START + 1035

-- 请求Token
HttpDefine.HTTP_ID_REQ_TOKEN = BASE_HTTP_DEFINE_START + 1037

-- 获取所有web维护的联运游戏id
HttpDefine.REQ_H5_WECAHT_ALL_USERID = BASE_HTTP_DEFINE_START + 1038

HttpDefine.HTTP_CALLBACK_TYPE = {
    CALL_BACK_STRING = 0,
    CALL_BACK_ARRAY = 1,
    CALL_BACK_BLOB = 2,
    CALL_BACK_DOCUMENT = 3,
    CALL_BACK_JSON = 4,
}

-- 合规白名单
HttpDefine.URL_LEGITIMACY_CHECK = BASE_HTTP_DEFINE_START + 1039

HttpDefine.URL_LOGOFF_DOCANCLE = BASE_HTTP_DEFINE_START + 1040

HttpDefine.HTTP_ID_LUCK_TASK_GETPAGE = BASE_HTTP_DEFINE_START + 1041
HttpDefine.HTTP_ID_LUCK_TASK_GETCONTENT = BASE_HTTP_DEFINE_START + 1042
HttpDefine.HTTP_ID_LUCK_TASK_GETDRAWLOGS = BASE_HTTP_DEFINE_START + 1043
HttpDefine.HTTP_ID_LUCK_TASK_GETREWARDS = BASE_HTTP_DEFINE_START + 1044
HttpDefine.HTTP_ID_LUCK_TASK_Participate = BASE_HTTP_DEFINE_START + 1045
HttpDefine.HTTP_ID_LUCK_TASK_ACTLIST = BASE_HTTP_DEFINE_START + 1046

HttpDefine.HTTP_ID_PRE_SHUFFLE = BASE_HTTP_DEFINE_START + 1047

-- 配置中心
HttpDefine.HTTP_ID_CONFIGURATION_MD5 = BASE_HTTP_DEFINE_START + 1048
HttpDefine.HTTP_ID_CONFIGURATION_FILE = BASE_HTTP_DEFINE_START + 1049

-- 洗牌5.0
HttpDefine.HTTP_ID_SHUFFLE_5 = BASE_HTTP_DEFINE_START + 1050
HttpDefine.URL_PROP_DISCOUNT = BASE_HTTP_DEFINE_START + 1051
HttpDefine.URL_ACCEPT_PRESENTER = BASE_HTTP_DEFINE_START + 1052

HttpDefine.URL_ARTICLE_LIST = BASE_HTTP_DEFINE_START + 1053
HttpDefine.URL_ARTICLE_THROW = BASE_HTTP_DEFINE_START + 1054

-- sxvip 新版会员
HttpDefine.URL_SXVIP_REMAINER = BASE_HTTP_DEFINE_START + 1055
HttpDefine.URL_SXVIP_CONFIG = BASE_HTTP_DEFINE_START + 1056
HttpDefine.URL_SXVIP_PRIVILEGE = BASE_HTTP_DEFINE_START + 1057
HttpDefine.URL_VIP_PROP_USE_FREE = BASE_HTTP_DEFINE_START + 1058
HttpDefine.URL_SXVIP_FRIEND_INFO = BASE_HTTP_DEFINE_START + 1059
HttpDefine.URL_SXVIP_GAMEPLAY_STATISTICS = BASE_HTTP_DEFINE_START + 1060
HttpDefine.URL_SXVIP_DAILY_REWARD = BASE_HTTP_DEFINE_START + 1061
HttpDefine.URL_SXVIP_FELLOW_SEND = BASE_HTTP_DEFINE_START + 1062

HttpDefine.HTTP_ID_LUCK_TASK_ACTDETAIL = BASE_HTTP_DEFINE_START + 1062
HttpDefine.HTTP_ID_ACT_50_BANKRUPT = BASE_HTTP_DEFINE_START + 1063
HttpDefine.HTTP_ID_ACT_50_DEDUCTIBLE = BASE_HTTP_DEFINE_START + 1064
HttpDefine.HTTP_ID_ACT_50_JOINROOM = BASE_HTTP_DEFINE_START + 1065
HttpDefine.URL_SIGN_DETAIL = BASE_HTTP_DEFINE_START + 1066
HttpDefine.URL_SIGN = BASE_HTTP_DEFINE_START + 1067
HttpDefine.URL_PROPS_COUONT_50 = BASE_HTTP_DEFINE_START + 1068

HttpDefine.URL_SXVIP_PAY_AFTER_SIGN = BASE_HTTP_DEFINE_START + 1069
HttpDefine.HTTP_ID_AOYUN_INFO = BASE_HTTP_DEFINE_START + 1070

HttpDefine.HTTP_ID_USE_EQUIP_CARD = BASE_HTTP_DEFINE_START + 1071
HttpDefine.HTTP_ID_USER_LOCATION = BASE_HTTP_DEFINE_START + 1072

return HttpDefine