-- ViewsConfig的key为view的名称，会通过setName设置给view对象，并在viewManager中保存
-- Path为类的路径
-- ZOrder为view的默认层级
-- BindScene表示view只在该场景才能打开，若不配置则在当前场景打开
-- IsTiShenHide为true表示提审时无法打开
local ViewsConfig = {
    ["LoginMethodView"] = {Path = "login.Modules.LoginMethod.View", ZOrder = XH.ZORDER.WINDOW},
    ["GuideNewView"] = {Path = "lobby.Modules.GuideNew.View", ZOrder = XH.ZORDER.TOPLAYER},
    ["ChooseAreaView"] = {Path = "login.Modules.ChooseArea.View", ZOrder = XH.ZORDER.WINDOW, BindScene = XH.SCENE_TAG.LOGIN},
    ["ChooseAreaTipLayer"] = {Path = "login.Modules.ChooseArea.TipLayer", ZOrder = XH.ZORDER.TIPLAYER, BindScene = XH.SCENE_TAG.LOGIN},
    ["PhoneLoginView"] = {Path = "login.Modules.PhoneLogin.View", ZOrder = XH.ZORDER.WINDOW},
    ["PhoneBindGuideView"] = {Path = "login.Modules.PhoneLogin.BindGuideView", ZOrder = XH.ZORDER.WINDOW},
    ["AniGambleView"] = {Path = "lobby.Modules.AniGamble.View", ZOrder = XH.ZORDER.WINDOW},
    ["BackActivityAwardView"] = {Path = "lobby.Modules.BackActivity.AwardView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["BackActivityChooseView"] = {Path = "lobby.Modules.BackActivity.ChooseView", ZOrder = XH.ZORDER.WINDOW},
    ["BackActivityRuleView"] = {Path = "lobby.Modules.BackActivity.RuleView", ZOrder = XH.ZORDER.WINDOW},
    ["BackActivityView"] = {Path = "lobby.Modules.BackActivity.View", ZOrder = XH.ZORDER.WINDOW},
    ["CreateBoxRoomView"] = {Path = "lobby.Modules.CreateBoxRoom.View", ZOrder = XH.ZORDER.WINDOW, IsFullScreen = true},
    ["PersonalCenterView"] = {Path = "lobby.Modules.PersonalCenter.PersonalCenterView", ZOrder = XH.ZORDER.WINDOW},
    ["TabsActivityMesBox"] = {Path = "lobby.Modules.TabsActivity.MesBox", ZOrder = XH.ZORDER.DIALOG},
    ["TabsActivityView"] = {Path = "lobby.Modules.TabsActivity.View", ZOrder = XH.ZORDER.WINDOW},
    ["TicketFeesExchangeView"] = {Path = "lobby.Modules.TicketShop.FeesExchangeView", ZOrder = XH.ZORDER.WINDOW},
    ["TicketShopExchangeView"] = {Path = "lobby.Modules.TicketShop.ExchangeView", ZOrder = XH.ZORDER.WINDOW},
    ["TicketShopView"] = {Path = "lobby.Modules.TicketShop.View", ZOrder = XH.ZORDER.WINDOW},
    ["ShopView"] = {Path = "lobby.Modules.Shop.View", ZOrder = XH.ZORDER.WINDOW, IsFullScreen = true},
    ["SetView"] = {Path = "lobby.Modules.Set.View", ZOrder = XH.ZORDER.WINDOW},
    ["RuleView"] = {Path = "lobby.Modules.Rule.View", ZOrder = XH.ZORDER.ACT_POPLAYER, IsFullScreen = true},
    ["PlayerBillInputView"] = {Path = "lobby.Modules.PlayerBill.InputView", ZOrder = XH.ZORDER.WINDOW},
    ["PlayerBillMergeView"] = {Path = "lobby.Modules.PlayerBill.MergeView", ZOrder = XH.ZORDER.WINDOW},
    ["PlayerBillView"] = {Path = "lobby.Modules.PlayerBill.View", ZOrder = XH.ZORDER.WINDOW, IsFullScreen = true},
    ["PhoneBindView"] = {Path = "lobby.Modules.PhoneBind.View", ZOrder = XH.ZORDER.DIALOG},
    ["NotifyView"] = {Path = "lobby.Modules.Notify.View", ZOrder = XH.ZORDER.DIALOG},
    ["JoinBoxRoomView"] = {Path = "lobby.Modules.JoinBoxRoom.View", ZOrder = XH.ZORDER.WINDOW},
    ["InvateChangeRecordPhoneView"] = {Path = "lobby.Modules.Invate.ChangeRecordPhoneView", ZOrder = XH.ZORDER.DIALOG},
    ["InvateChangeView"] = {Path = "lobby.Modules.Invate.ChangeView", ZOrder = XH.ZORDER.WINDOW},
    ["InvateView"] = {Path = "lobby.Modules.Invate.InvateView", ZOrder = XH.ZORDER.WINDOW},
    ["HealthView"] = {Path = "lobby.Modules.Health.View", ZOrder = XH.ZORDER.WINDOW},
    ["GoldBaseLiveView"] = {Path = "lobby.Modules.Gold.BaseLiveView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["GoldBankruptcyView"] = {Path = "lobby.Modules.Gold.BankruptcyView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["GoldEnterCardView"] = {Path = "lobby.Modules.GoldEnterCard.View", ZOrder = XH.ZORDER.TIPLAYER + 2},
    ["GoldRewardView"] = {Path = "lobby.Modules.Gold.RewardView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["GoldView"] = {Path = "lobby.Modules.Gold.View", ZOrder = XH.ZORDER.WINDOW},
    ["GiftBagView"] = {Path = "lobby.Modules.GiftBag.View", ZOrder = XH.ZORDER.WINDOW},
    ["FillInfoView"] = {Path = "lobby.Modules.FillInfoConfirm.FillInfoView", ZOrder = XH.ZORDER.WINDOW},
    ["FillInfoConfirmView"] = {Path = "lobby.Modules.FillInfoConfirm.View", ZOrder = XH.ZORDER.WINDOW},
    ["CusServiceView"] = {Path = "lobby.Modules.CusService.View", ZOrder = XH.ZORDER.ACT_POPLAYER + 1},
    ["CommonRewardView"] = {Path = "lobby.Modules.CommonReward.RewardView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["MailView"] = {Path = "lobby.Modules.Mail.View", ZOrder = XH.ZORDER.WINDOW},
    ["DailyLuckDrawMainView"] = {Path = "lobby.Modules.DailyLuckyDraw.View", ZOrder = XH.ZORDER.WINDOW},
    ["DailyLuckDrawRewardView"] = {Path = "lobby.Modules.DailyLuckyDraw.RewardView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["UniunGameView"] = {Path = "lobby.Modules.UniunGame.View", ZOrder = XH.ZORDER.WINDOW},
    ["BagMainViewNew"] = {Path = "lobby.Modules.BagSysNew.View", ZOrder = XH.ZORDER.WINDOW},
    ["ImMainView"] = {Path = "lobby.Modules.Im.View", ZOrder = XH.ZORDER.WINDOW},
    ["ImViewNew"] = {Path = "lobby.Modules.Im.NewIMView", ZOrder = XH.ZORDER.WINDOW},
    ["ImMessageView"] = {Path = "lobby.Modules.Im.MessageView", ZOrder = XH.ZORDER.WINDOW},
    ["ImMessageUIView"] = {Path = "lobby.Modules.Im.MessageUIView", ZOrder = XH.ZORDER.TOAST},
    ["ImInviteView"] = {Path = "lobby.Modules.Im.InviteView", ZOrder = XH.ZORDER.SCENE_POPNODE},
    ["IMTipsLayerView"] = {Path = "lobby.Modules.Im.TipsLayerView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["IMHostDismissView"] = {Path = "lobby.Modules.Im.HostDismissView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["IMSearchLoadingView"] = {Path = "lobby.Modules.Im.SearchLoadingView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["IMHistoryFriendsView"] = {Path = "lobby.Modules.Im.HistoryFriendsView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["NotEnoughPropsView"] = {Path = "lobby.Modules.Shop.NotEnoughPropsView", ZOrder = XH.ZORDER.WINDOW },
    ["ShopChooseView"] = {Path = "lobby.Modules.Shop.ChooseView", ZOrder = XH.ZORDER.WINDOW},
    ["ShopHingMsgView"] = {Path = "lobby.Modules.Shop.HintMsgView", ZOrder = XH.ZORDER.WINDOW},
    ["PayTypeView"] = {Path = "lobby.Modules.Shop.PayTypeView", ZOrder = XH.ZORDER.TIPLAYER},
    ["H5QRCodeView"] = {Path = "lobby.Modules.Shop.H5QRCodeView", ZOrder = XH.ZORDER.TIPLAYER},
    ["ShopPayCancel"] = {Path = "lobby.Modules.Shop.ShopPayCancelView", ZOrder = XH.ZORDER.TIPLAYER},
    ["ZheJiangNewsView"] = {Path = "lobby.Modules.ZheJiangNews.View", ZOrder = XH.ZORDER.DIALOG},
    ["CeLueCenterView"] = {Path = "lobby.Modules.PersonalCenter.CeLueCenterView", ZOrder = XH.ZORDER.DIALOG},
    ["CeLueAgreeView"] = {Path = "login.Modules.Login.CeLueAgreeView", ZOrder = XH.ZORDER.LOADING},
    ["CeLueQuanXianView"] = {Path = "login.Modules.Login.CeLueQuanXianView", ZOrder = XH.ZORDER.LOADING},
    ["CeLueAgeView"] = {Path = "login.Modules.Login.CeLueAgeView", ZOrder = XH.ZORDER.LOADING},
    ["PermissionTipView"] = {Path = "login.Modules.Login.PermissionTipView", ZOrder = XH.ZORDER.LOADING},
    ["PermissionSmallTipView"] = {Path = "login.Modules.Login.PermissionSmallTipView", ZOrder = XH.ZORDER.TIPLAYER},
    ["SaleGiftbagView"] = {Path = "lobby.Modules.SaleGiftbag.View", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["AwardCenterView"] = {Path = "lobby.Modules.AwardCenter.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTurnTableActView"] = {Path = "lobby.Modules.LuckyTurnTableAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTurnTableActHelpView"] = {Path = "lobby.Modules.LuckyTurnTableAct.ActHelpView", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTurnTableActAwardView"] = {Path = "lobby.Modules.LuckyTurnTableAct.ActAwardView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["VipWelfareView"] = {Path = "lobby.Modules.NewVip.View", ZOrder = XH.ZORDER.WINDOW + 1},
    ["VipNoticeLayer"] = {Path = "lobby.Modules.NewVip.VipNoticeView", ZOrder = XH.ZORDER.WINDOW },
    ["VipChargeLayer"] = {Path = "lobby.Modules.NewVip.VipChargeView", ZOrder = XH.ZORDER.WINDOW },
    ["VipEmojiPropChargeLayer"] = {Path = "lobby.Modules.NewVip.VipEmojiPropChargeView", ZOrder = XH.ZORDER.WINDOW },
    ["VipRenewTipsLayer"] = {Path = "lobby.Modules.NewVip.VipRenewTipsView", ZOrder = XH.ZORDER.WINDOW },
    ["GoldPlayActView"] = {Path = "lobby.Modules.GoldPlayAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["GoldRechargeView"] = {Path = "lobby.Modules.Gold.RechargeView", ZOrder = XH.ZORDER.WINDOW},
    ["PropChargeLayer"] = {Path = "lobby.Modules.GiftBag.PropChargeView", ZOrder = XH.ZORDER.WINDOW + 1 },
    ["ShopGiftChooseView"] = {Path = "lobby.Modules.GiftBag.ShopGiftChooseView", ZOrder = XH.ZORDER.WINDOW},
    ["ShopGiftChanceView"] = {Path = "lobby.Modules.GiftBag.ShopGiftChanceView", ZOrder = XH.ZORDER.WINDOW},
    ["GiftRewardView"] = {Path = "lobby.Modules.GiftBag.GiftRewardView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["AutoLogoutView"] = {Path = "lobby.Modules.PersonalCenter.AutoLogoutView", ZOrder = XH.ZORDER.WINDOW},
    ["ToponLobbyWaitView"] = {Path = "lobby.Modules.ToponAct.ToponLobbyWaitView", ZOrder = XH.ZORDER.ACT_POPLAYER+5},
    ["ToponPhoneFeeView"] = {Path = "lobby.Modules.ToponAct.ToponPhoneFeeView", ZOrder = XH.ZORDER.WINDOW},
    ["ToponDailySignView"] = {Path = "lobby.Modules.ToponAct.ToponDailySignView", ZOrder = XH.ZORDER.WINDOW},
    ["ToponGoldAreaDrawView"] = {Path = "lobby.Modules.ToponAct.ToponGoldAreaDrawView", ZOrder = XH.ZORDER.WINDOW},
    ["H5GameWidgetView"] = {Path = "lobby.Modules.H5GameWidget.View", ZOrder = XH.ZORDER.TIPLAYER - 1},
    ["PrayActView"] = {Path = "lobby.Modules.PrayAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["QuickRechargeView"] = {Path = "lobby.Modules.QuickRecharge.View", ZOrder = XH.ZORDER.WINDOW },
    ["QuickRechargeVipView"] = {Path = "lobby.Modules.QuickRecharge.VipView", ZOrder = XH.ZORDER.WINDOW },
    ["QuickRechargeBuyView"] = {Path = "lobby.Modules.QuickRecharge.AskBuyView", ZOrder = XH.ZORDER.WINDOW },
    ["PersonalGiftPackView"] = {Path = "lobby.Modules.PersonalGiftPack.View", ZOrder = XH.ZORDER.DIALOG},
    ["PopSystemView"] = {Path = "lobby.Modules.PopSystem.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTaskPromotePopView"] = {Path = "lobby.Modules.LuckyTaskPromote.LuckyTaskPromotePopView", ZOrder = XH.ZORDER.WINDOW},
    ["CommonRuleView"] = {Path = "lobby.Modules.CommonRule.CommonRuleView", ZOrder = XH.ZORDER.WINDOW},
    ["PopCommonLayerView"] = {Path = "lobby.Modules.PopCommonLayer.View", ZOrder = XH.ZORDER.WINDOW},
    ["QualificationView"] = {Path = "lobby.Modules.Set.QualificationView", ZOrder = XH.ZORDER.WINDOW},
    ["TeaHouseInviteView"] = {Path = "lobby.Modules.TeaHouseBatchInvite.TeaHouseInviteView", ZOrder = XH.ZORDER.WINDOW},
    ["TeaHouseInviteQuestionView"] = {Path = "lobby.Modules.TeaHouseBatchInvite.TeaHouseInviteQuestionView", ZOrder = XH.ZORDER.WINDOW },
    ["CouponSystemView"] = {Path = "lobby.Modules.CouponSystem.View", ZOrder = XH.ZORDER.WINDOW},
    ["InputPassWord"] = {Path = "lobby.Modules.PersonalCenter.PersonalInputPassWord", ZOrder = XH.ZORDER.WINDOW},
    ["PersonalCenterTipLayer"] = {Path = "lobby.Modules.PersonalCenter.PersonalCenterTipLayer", ZOrder = XH.ZORDER.WINDOW},
    ["PlayersSuggestionView"] = {Path = "lobby.Modules.PlayersSuggestion.View", ZOrder = XH.ZORDER.WINDOW},
    ["IMAddGroupView"] = {Path = "lobby.Modules.IMTeaHouse.IMAddGroupView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseTipsView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseTipsView", ZOrder = XH.ZORDER.WINDOW},
    ["IMAddPaiYouView"] = {Path = "lobby.Modules.IMTeaHouse.IMAddPaiYouView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseRankView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseRankView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseApplyFriendView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseApplyFriendView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseMemberView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseMemberView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeahouseRecordView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeahouseRecordView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseGroupTipsView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseGroupTipsView", ZOrder = XH.ZORDER.WINDOW},
    ["TeaHouseRankListItem2"] = {Path = "lobby.Modules.IMTeaHouse.TeaHouseRankListItem2", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseRankListItem"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseRankListItem", ZOrder = XH.ZORDER.WINDOW},
    ["IMCreateRoomView"] = {Path = "lobby.Modules.IMTeaHouse.IMCreateRoomView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseRoomInfoView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseRoomInfoView", ZOrder = XH.ZORDER.WINDOW},
    ["IMTeaHouseConfirmView"] = {Path = "lobby.Modules.IMTeaHouse.IMTeaHouseConfirmView", ZOrder = XH.ZORDER.WINDOW},
    ["LockTips"] = {Path = "app.Tip.LockTips",ZOrder = XH.ZORDER.LOADING},
    ["FishingKingTransferView"] = {Path = "lobby.Modules.FishingKingTransfer.View", ZOrder = XH.ZORDER.WINDOW},
    ["QuestionGuideView"] = {Path = "lobby.Modules.QuestionGuide.View", ZOrder = XH.ZORDER.TIPLAYER},
    ["PromoteHallView"] = {Path = "lobby.Modules.Promote.PromoteHallView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteView"] = {Path = "lobby.Modules.Promote.View", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteLogView"] = {Path = "lobby.Modules.Promote.PromoteLogView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteInviteView"] = {Path = "lobby.Modules.Promote.PromoteInviteView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteTipView"] = {Path = "lobby.Modules.Promote.PromoteTipView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteUserInviteView"] = {Path = "lobby.Modules.Promote.PromoteUserInviteView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteTeaNewView"] = {Path = "lobby.Modules.Promote2.PromoteTeaNewView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteIntroduceNewView"] = {Path = "lobby.Modules.Promote2.PromoteIntroduceNewView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteRewardLogNewView"] = {Path = "lobby.Modules.Promote2.PromoteRewardLogNewView", ZOrder = XH.ZORDER.WINDOW},
    ["PromoteDialogNewView"] = {Path = "lobby.Modules.Promote2.PromoteDialogNewView", ZOrder = XH.ZORDER.WINDOW},
    ["IdentityCheckView"] = {Path = "lobby.Modules.IdentityCheck.NView", ZOrder = XH.ZORDER.TOPLAYER-1},
    ["WXPublicView"] = {Path = "lobby.Modules.WXPublic.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTaskView"] = {Path = "lobby.Modules.LuckyTask.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyTaskLogView"] = {Path = "lobby.Modules.LuckyTask.LuckyTaskLogView", ZOrder = XH.ZORDER.WINDOW},
    ["UnlimitedGiftView"] = {Path = "lobby.Modules.UnlimitedGift.View", ZOrder = XH.ZORDER.WINDOW},
    ["UnlimitedGiftRuleView"] = {Path = "lobby.Modules.UnlimitedGift.RuleView", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyShareView"] = {Path = "lobby.Modules.Share.LobbyShareView", ZOrder = XH.ZORDER.WINDOW},
    ["JinLongPopNode"] = {Path = "lobby.Modules.JinlongPop.View", ZOrder = XH.ZORDER.WINDOW},
    ["GoldLaunchView"] = {Path = "lobby.Modules.GoldLaunch.View", ZOrder = XH.ZORDER.WINDOW + 99},
    ["SxvipTopView"] = {Path = "lobby.Modules.Sxvip.SxvipTopView", ZOrder = XH.ZORDER.TOPLAYER},
    ["SxvipActView"] = {Path = "lobby.Modules.SxvipAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["SxvipActTipView"] = {Path = "lobby.Modules.SxvipAct.TipView", ZOrder = XH.ZORDER.WINDOW},
    ["SxvipView"] = {Path = "lobby.Modules.Sxvip.View", ZOrder = XH.ZORDER.SCENE_POPNODE},
    ["SxvipPrivilegeView"] = {Path = "lobby.Modules.Sxvip.SxvipPrivilegeView", ZOrder = XH.ZORDER.SCENE_POPNODE },
    ["SxvipShopView"] = {Path = "lobby.Modules.Sxvip.SxvipShopView", ZOrder = XH.ZORDER.SCENE_POPNODE },
    ["SxvipDailyGiftView"] = {Path = "lobby.Modules.Sxvip.SxvipDailyGiftView", ZOrder = XH.ZORDER.SCENE_POPNODE },
    ["SxvipGiveView"] = {Path = "lobby.Modules.Sxvip.SxvipGiveView", ZOrder = XH.ZORDER.SCENE_POPNODE},
    ["SxvipRecordView"] = {Path = "lobby.Modules.Sxvip.SxvipRecordView", ZOrder = XH.ZORDER.SCENE_POPNODE},
    ["SxvipInfoView"] = {Path = "lobby.Modules.Sxvip.SxvipInfoView", ZOrder = XH.ZORDER.SCENE_POPNODE},
    ["YGiftDefeatView"] = {Path = "lobby.Modules.YGiftDefeat.View", ZOrder = XH.ZORDER.WINDOW},
    ["YGiftEnterView"] = {Path = "lobby.Modules.YGiftEnter.View", ZOrder = XH.ZORDER.WINDOW},
    ["ScoringAssistantView"] = {Path = "lobby.Modules.ScoringAssistant.View", ZOrder = XH.ZORDER.WINDOW},
    ["ApplyView"] = {Path = "lobby.Modules.PeakRace.ApplyView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["MatchContributeRuleView"] = {Path = "lobby.Modules.PeakRace.RuleView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["MatchContributeView"] = {Path = "lobby.Modules.PeakRace.View", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["MatchTipView"] = {Path = "lobby.Modules.Match.MatchTipView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["MatchRankTipView"] = {Path = "lobby.Modules.PeakRace.TipView", ZOrder = XH.ZORDER.ACT_POPLAYER},
    ["AniTopView"] = {Path = "lobby.Modules.AniTop.View", ZOrder = XH.ZORDER.LOADING},
    ["TimeLoginActView"] = {Path = "lobby.Modules.TimeLoginAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["TimeLoginActWheelView"] = {Path = "lobby.Modules.TimeLoginAct.WheelView", ZOrder = XH.ZORDER.WINDOW},
    ["BindPhoneView"] = {Path = "lobby.Modules.BindPhone.View", ZOrder = XH.ZORDER.DIALOG},
    ["GoldHallEditGameView"] = {Path = "lobby.Modules.GoldNew.Views.EditGame", ZOrder = XH.ZORDER.DIALOG},
    ["GoldHallGameRuleView"] = {Path = "lobby.Modules.GoldNew.SubModules.Rule.RuleView", ZOrder = XH.ZORDER.DIALOG},
    ["GoldHallSettingView"] = {Path = "lobby.Modules.GoldNew.SubModules.Setting.SettingView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallBagView"] = {Path = "lobby.Modules.GoldNew.SubModules.Bag.BagView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallShopView"] = {Path = "lobby.Modules.GoldNew.SubModules.Shop.ShopView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallQuickRechareView"] = {Path = "lobby.Modules.GoldNew.SubModules.Shop.QuickRechareView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallFRFirstView"] = {Path = "lobby.Modules.GoldNew.SubModules.ActFirstRecharge.ActFRFirstView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallFRSecondView"] = {Path = "lobby.Modules.GoldNew.SubModules.ActFirstRecharge.ActFRSecondView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallBJRankView"] = {Path = "lobby.Modules.GoldNew.SubModules.ActBaoJiRank.ActBaoJiRankView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallBJRankRuleView"] = {Path = "lobby.Modules.GoldNew.SubModules.ActBaoJiRank.ActBaoJiRankRuleView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallPeGPView"] = {Path = "lobby.Modules.GoldNew.SubModules.ActPeriodicGiftPackage.ActPeGPView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallPCView"] = {Path = "lobby.Modules.GoldNew.SubModules.PersonalCenter.PersonalCenterView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallPCEditAvatarView"] = {Path = "lobby.Modules.GoldNew.SubModules.PersonalCenter.EditAvatarView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallGPCView"] = {Path = "lobby.Modules.GoldNew.SubModules.GiftPackCollection.GiftPackCollectionView", ZOrder = XH.ZORDER.WINDOW},
    ["CoinRewardsView"] = {Path = "lobby.Modules.GoldNew.SubModules.CoinRewards.View", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallMailView"] = {Path = "lobby.Modules.GoldNew.SubModules.Mail.View", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallMailDetailView"] = {Path = "lobby.Modules.GoldNew.SubModules.Mail.DetailView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallActivityView"] = {Path = "lobby.Modules.GoldNew.SubModules.Activity.ActivityView", ZOrder = XH.ZORDER.WINDOW},
    ["GoldHallChooseRoomGuideView"] = {Path = "lobby.Modules.GoldNew.Views.ChooseRoomGuide", ZOrder = XH.ZORDER.WINDOW},
    ["FeedBackView"] = {Path = "lobby.Modules.FeedBack.View", ZOrder = XH.ZORDER.ACT_POPLAYER + 1},
    ["GamePlayReachView"] = {Path = "lobby.Modules.GamePlayReach.View", ZOrder = XH.ZORDER.ACT_POPLAYER}, -- 玩法触达标准弹窗
    ["ReviveGiftView"] = {Path = "lobby.Modules.ReviveGift.View", ZOrder = XH.ZORDER.WINDOW},
    ["TeachingGiftView"] = {Path = "lobby.Modules.TeachingGift.View", ZOrder = XH.ZORDER.WINDOW},
    ["ImageTextTutorialView"] = {Path = "lobby.Modules.ImageTextTutorial.View", ZOrder = XH.ZORDER.WINDOW},
    ["DarkShuangKouChallengeView"] = {Path = "lobby.Modules.DarkShuangKouChallenge.View", ZOrder = XH.ZORDER.WINDOW},
    ["DarkShuangKouChallengeRuleView"] = {Path = "lobby.Modules.DarkShuangKouChallenge.RuleView", ZOrder = XH.ZORDER.WINDOW},
    ["WindowsTestUI"] = {Path = "local.Debug.Config.WindowsTest.WindowsTestUI", ZOrder = XH.ZORDER.LOADING + 111},
    ["UnLimitGoldActView"] = {Path = "lobby.Modules.UnlimitGoldAct.View", ZOrder = XH.ZORDER.WINDOW},
    ["UnLimitBoxActView"] = {Path = "lobby.Modules.UnlimitBoxAct.View", ZOrder = XH.ZORDER.WINDOW + 1},
    ["BattlePassDarkShuangKouView"] = {Path = "lobby.Modules.BattlePass.DarkShuangKou.View", ZOrder = XH.ZORDER.WINDOW},
    ["BattlePassDarkShuangKouAwardPreview"] = {Path = "lobby.Modules.BattlePass.DarkShuangKou.AwardPreview", ZOrder = XH.ZORDER.WINDOW},
    ["BattlePassAwardDescView"] = {Path = "lobby.Modules.BattlePass.AwardDesc", ZOrder = XH.ZORDER.WINDOW},
    ["BattlePassRuleView"] = {Path = "lobby.Modules.BattlePass.RuleView", ZOrder = XH.ZORDER.WINDOW},
    ["BattlePassGetAwardView"] = {Path = "lobby.Modules.BattlePass.GetAwardView", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyBattlePassView"] = {Path = "lobby.Modules.BattlePass.Lobby.View", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyBattlePassBuyLevelView"] = {Path = "lobby.Modules.BattlePass.Lobby.BuyLevelView", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyBattlePassRewardPreView"] = {Path = "lobby.Modules.BattlePass.Lobby.RewardPreView", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyBattlePassUnlockView"] = {Path = "lobby.Modules.BattlePass.Lobby.UnlockView", ZOrder = XH.ZORDER.WINDOW},
    ["BoxGuideView"] = {Path = "lobby.Modules.BoxGuide.View", ZOrder = XH.ZORDER.WINDOW},
    ["XiaGuangView"] = {Path = "lobby.Modules.XiaGuang.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyBagView"] = {Path = "lobby.Modules.Share.LuckyBagView", ZOrder = XH.ZORDER.WINDOW},
    ["LobbyShareNewView"] = {Path = "lobby.Modules.Share.LobbyShareNewView", ZOrder = XH.ZORDER.WINDOW},
    ["RecallNewView"] = {Path = "lobby.Modules.RecallNew.View", ZOrder = XH.ZORDER.WINDOW},
    ["RecallNewHelpView"] = {Path = "lobby.Modules.RecallNew.HelpView", ZOrder = XH.ZORDER.WINDOW},
    ["RecallNewEmailView"] = {Path = "lobby.Modules.RecallNew.EmailView", ZOrder = XH.ZORDER.TOPLAYER + 2},
    ["RecallTeamView"] = {Path = "lobby.Modules.RecallTeam.View", ZOrder = XH.ZORDER.WINDOW},
    ["InviteAct"] = {Path = "lobby.Modules.InviteActivity.View", ZOrder = XH.ZORDER.WINDOW},
    ["InviteActAwardRecord"] = {Path = "lobby.Modules.InviteActivity.AwardRecordView", ZOrder = XH.ZORDER.WINDOW},
    ["InviteActInviteRecord"] = {Path = "lobby.Modules.InviteActivity.InviteRecordView", ZOrder = XH.ZORDER.WINDOW},
    ["InvitePhoneNumView"] = {Path = "lobby.Modules.InviteActivity.PhoneNumView", ZOrder = XH.ZORDER.WINDOW},
    ["InviteGetPhoneCardTip"] = {Path = "lobby.Modules.InviteActivity.GetPhoneCardTip", ZOrder = XH.ZORDER.WINDOW},
    ["MonthlyCardView"] = {Path = "lobby.Modules.MonthlyCard.View", ZOrder = XH.ZORDER.WINDOW},
    ["LuckyMissionView"] = {Path = "lobby.Modules.LuckyMission.View", ZOrder = XH.ZORDER.WINDOW},
    ["FeeGetView"] = {Path = "lobby.Modules.RecallNew.FeeGetView", ZOrder = XH.ZORDER.WINDOW},
    ["FriendTeaView"] = {Path = "lobby.Modules.FriendTea.View", ZOrder = XH.ZORDER.WINDOW},
    ["Double12View"] = {Path = "lobby.Modules.Double12.View", ZOrder = XH.ZORDER.WINDOW},
    ["Double12AwardView"] = {Path = "lobby.Modules.Double12.AwardView", ZOrder = XH.ZORDER.WINDOW},
    ["Double12ActHelpView"] = {Path = "lobby.Modules.Double12.HelpView", ZOrder = XH.ZORDER.WINDOW},
    ["ShareFailView"] = {Path = "lobby.Modules.Share.ShareFailView", ZOrder = XH.ZORDER.WINDOW + 1},
    ["NewYear2026"] = {Path = "lobby.Modules.NewYear2026.View", ZOrder = XH.ZORDER.WINDOW},
    ["QingShenIntegrateView"] = {Path = "lobby.Modules.QingShen.QingShenIntegrateView", ZOrder = XH.ZORDER.WINDOW},
    ["GameCenterView"] = {Path = "lobby.Modules.GameCenter.View", ZOrder = XH.ZORDER.WINDOW},
    ["GameCenterWebVideoView"] = {Path = "lobby.Modules.GameCenter.WebVideoView", ZOrder = XH.ZORDER.WINDOW},
    ["GameCenterTaskView"] = {Path = "lobby.Modules.GameCenter.TaskView", ZOrder = XH.ZORDER.WINDOW},
}
return ViewsConfig k`  