-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	GameMenuList = {
		{ ConfID = 1001, DefaultValue = { 100, 1, 100, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2 ,1} },
        { ConfID = 7133, DefaultValue = { 100, 0, 100, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1 ,1} },
        { ConfID = 7109, DefaultValue = { 100, 1, 100, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2 ,1} },
        { ConfID = 7128, DefaultValue = { 100, 1, 100, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2 ,1} },
        { ConfID = 7107, DefaultValue = { 100, 0, 100, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1 ,1} },
        { ConfID = 7102, DefaultValue = { 100, 1, 100, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2 ,1} },
        { ConfID = 7136, DefaultValue = { 100, 1, 100, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2 ,2} },
	}

}


-- ConfID
tab.GameMenuListByConfID = {}
for _, rec in pairs(tab.GameMenuList) do
	tab.GameMenuListByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab