-- Generated by github.com/davyxu/tabtoy
-- Version: 2.8.7

local tab = {
	AgentAreaSelectConfig = {
		{ ConfID = 900038, ShiName = "丽水", QuNameTable = { "莲都", "龙泉", "松阳", "庆元", "缙云", "遂昌", "青田", "其他" } 	},
		{ ConfID = 900037, ShiName = "温州(茶)", QuNameTable = { "龙港", "平阳", "苍南", "泰顺", "文成", "其他" } 	},
		{ ConfID = 900017, ShiName = "温州(熟)", QuNameTable = { "永嘉", "龙湾", "鹿城", "瓯海", "其他" } 	},
		{ ConfID = 900025, ShiName = "杭州(宝宝)", QuNameTable = { "其他" } 	},
		{ ConfID = 900021, ShiName = "杭州", QuNameTable = { "其他" } 	},
		{ ConfID = 900020, ShiName = "金华", QuNameTable = { "其他" } 	},
		{ ConfID = 900036, ShiName = "瑞安", QuNameTable = { "其他" } 	},
		{ ConfID = 900031, ShiName = "乐清", QuNameTable = { "其他" } 	},
		{ ConfID = 900003, ShiName = "衢州", QuNameTable = { "其他" } 	},
		{ ConfID = 900008, ShiName = "湖州", QuNameTable = { "其他" } 	},
		{ ConfID = 900023, ShiName = "台州", QuNameTable = { "其他" } 	},
		{ ConfID = 900043, ShiName = "舟山", QuNameTable = { "其他" } 	},
		{ ConfID = 900039, ShiName = "青田", QuNameTable = { "其他" } 	},
		{ ConfID = 900007, ShiName = "嵊州(越)", QuNameTable = { "其他" } 	},
		{ ConfID = 900006, ShiName = "宁波", QuNameTable = { "其他" } 	},
		{ ConfID = 40165, ShiName = "嘉兴", QuNameTable = { "其他" } 	},
		{ ConfID = 900029, ShiName = "余姚", QuNameTable = { "其他" } 	},
        { ConfID = 900046, ShiName = "绍兴麻将", QuNameTable = { "其他" } 	}
	}

}


-- ConfID
tab.AgentAreaSelectConfigByConfID = {}
for _, rec in pairs(tab.AgentAreaSelectConfig) do
	tab.AgentAreaSelectConfigByConfID[rec.ConfID] = rec
end

tab.Enum = {
}

return tab