local CreateBoxRoomConfig = { }

CreateBoxRoomConfig.DefaultRuleToServer = {
    [30042] = {Rule = "basescore='1';", Text = "底分1倍"},
    [30043] = {Rule = "basescore='1';CanContinue='1';", Text = "底分1倍"},
    [30126] = {Rule = "basescore='1';", Text = "底分1倍"},
    [30073] = {Rule = "DiFen='1';", Text = "1分"},
    [30017] = {Rule = "Base='1';", Text = "1"},
    [30018] = {Rule = "Base='1';", Text = "1"},
    [30023] = {Rule = "base='1';", Text = "1"},
    [30025] = {Rule = "base='1';", Text = "1"},
    [30026] = {Rule = "basescore='1';", Text = "1"},
    [30028] = {Rule = "base='1';", Text = "1"},
    [30102] = {Rule = "basescore='1';", Text = "1分"},
    [30107] = {Rule = "basescore='1';", Text = "1分"},
    [30109] = {Rule = "basescore='1';", Text = "1"},
    [30110] = {Rule = "basescore='1';", Text = "1"},
    [30111] = {Rule = "basescore='1';", Text = "1"},
    [30112] = {Rule = "basescore='1';", Text = "1"},
    [30113] = {Rule = "baseScore='1';", Text = "1"},
    [30114] = {Rule = "baseScore='1';", Text = "1"},
    [30250] = {Rule = "basescore='1';", Text = "1"},
    [30284] = {Rule = "basescore='1';", Text = "1"},
    [302841] = {Rule = "basescore='1';", Text = "1"},
    [30399] = {Rule = "basescore='1';", Text = "1"},
    [30133] = {Rule = "basescore='1';", Text = "1"},
    [30136] = {Rule = "basescore='1';", Text = "1"},
    [30137] = {Rule = "basescore='1';", Text = "1"},
    [30138] = {Rule = "basescore='1';", Text = "1"},
    [30139] = {Rule = "basescore='1';", Text = "1"},
    [30140] = {Rule = "basescore='1';", Text = "1"},
    [30145] = {Rule = "basescore='1';", Text = "1"},
    [30151] = {Rule = "basescore='1';", Text = "1"},
    [30153] = {Rule = "basescore='1';", Text = "1", NotCategoriesIndex = 2},
    [30323] = {Rule = "BaseScore='0'", Text = "1分底"},
    [30446] = {Rule = "Multiple='0';", Text = "0.5倍"},
    [30356] = {Rule = "DiScore='1';", Text = "5分"},
    [30160] = {Rule = "basescore='1';", Text = "1"},
    [30020] = {Rule = "base='1';", Text = "1"},
    [30022] = {Rule = "base='1';", Text = "1"},
    [30021] = {Rule = "base='1';", Text = "1"},
    [30172] = {Rule = "basescore='1';", Text = "1"},
    [30465] = {Rule = "BaseScore='1';", Text = "1"},
    [30135] = {Rule = "BaseJinType='3';", Text = "5分"},
    [30142] = {Rule = "basescore='1';", Text = "1"},
    [30388] = {Rule = "basescore='1';", Text = "1"},
    [30155] = {Rule = "baseScore='1';", Text = "1"},
    [30227] = {Rule = "baseScore='1';", Text = "1"},
    [30063] = {Rule = "basescore='1';", Text = "1"},
    [30065] = {Rule = "BaseScore='1';", Text = "1"},
}

CreateBoxRoomConfig.BaseScoreRuleToText = {
    [30020] = {
        ["base='1';"] = "1",
        ["base='2';"] = "2",
        ["base='3';"] = "3",
        ["base='5';"] = "5",
        ["base='10';"] = "10",
        ["base='20';"] = "20",
    },
    [30022] = {
        ["base='1';"] = "1",
        ["base='2';"] = "2",
        ["base='3';"] = "3",
        ["base='5';"] = "5",
    },
    [30021] = {
        ["base='1';"] = "1",
        ["base='2';"] = "2",
        ["base='3';"] = "3",
        ["base='5';"] = "5",
    },
    [30023] = {
        ["base='1';"] = "1",
        ["base='2';"] = "2",
        ["base='3';"] = "3",
        ["base='5';"] = "5",
    },
    [30025] = {
        ["base='1';"] = "1",
        ["base='2';"] = "2",
        ["base='3';"] = "3",
        ["base='5';"] = "5",
    },
    [30026] = {
        ["basescore='1';"] = "1",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
    },
    [30028] = {
        ["base='1';"] = "1",
        ["base='5';"] = "5",
        ["base='10';"] = "10",
        ["base='20';"] = "20",
    },
    [30017] = {
        ["Base='1';"] = "1",
        ["Base='2';"] = "2",
        ["Base='5';"] = "5",
        ["Base='10';"] = "10",
    },
    [30018] = {
        ["Base='1';"] = "1",
        ["Base='2';"] = "2",
        ["Base='5';"] = "5",
        ["Base='10';"] = "10",
    },
    [30063] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
    },
    [30065] = {
        ["BaseScore='1';"] = "1",
        ["BaseScore='2';"] = "2",
        ["BaseScore='5';"] = "5",
        ["BaseScore='10';"] = "10",
    },
    [30073] = {
        ["DiFen='1';"] = "1分",
        ["DiFen='3';"] = "3分",
        ["DiFen='5';"] = "5分",
        ["DiFen='10';"] = "10分",
    },
    [30102] = {
        ["basescore='1';"] = "1分",
        ["basescore='2';"] = "2分",
        ["basescore='4';"] = "4分",
    },
    [30107] = {
        ["basescore='1';"] = "1分",
        ["basescore='2';"] = "2分",
        ["basescore='5';"] = "5分",
    },
    [30172] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
    },
    [30465] = {
        ["BaseScore='1';"] = "1",
        ["BaseScore='2';"] = "2",
        ["BaseScore='5';"] = "5",
        ["BaseScore='10';"] = "10",
    },
    [30135] = {
        ["BaseJinType='3';"] = "5分",
        ["BaseJinType='0';"] = "1斤",
        ["BaseJinType='1';"] = "2.5斤",
        ["BaseJinType='2';"] = "5斤",
    },
    [30136] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
    },
    [30137] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
    },
    [30138] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
    },
    [30139] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
    },
    [30140] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
    },
    [30142] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
        ["basescore='10';"] = "10",
        ["basescore='20';"] = "20",
    },
    [30145] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
    },
    [30151] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
        ["basescore='10';"] = "10",
    },
    [30388] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
        ["basescore='10';"] = "10",
        ["basescore='20';"] = "20",
    },
    [30109] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30110] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30111] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30112] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30113] = {
        ["baseScore='1';"] = "1",
        ["baseScore='2';"] = "2",
        ["baseScore='3';"] = "3",
        ["baseScore='4';"] = "4",
        ["baseScore='5';"] = "5",
    },
    [30114] = {
        ["baseScore='1';"] = "1",
        ["baseScore='2';"] = "2",
        ["baseScore='3';"] = "3",
        ["baseScore='4';"] = "4",
        ["baseScore='5';"] = "5",
    },
    [30155] = {
        ["baseScore='1';"] = "1",
        ["baseScore='2';"] = "2",
        ["baseScore='3';"] = "3",
        ["baseScore='4';"] = "4",
        ["baseScore='5';"] = "5",
    },
    [30227] = {
        ["baseScore='1';"] = "1",
        ["baseScore='2';"] = "2",
        ["baseScore='3';"] = "3",
        ["baseScore='4';"] = "4",
        ["baseScore='5';"] = "5",
    },
    [30250] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30284] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [302841] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30399] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='4';"] = "4",
        ["basescore='5';"] = "5",
    },
    [30153] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='3';"] = "3",
        ["basescore='5';"] = "5",
    },
    [30160] = {
        ["basescore='1';"] = "1",
        ["basescore='2';"] = "2",
        ["basescore='5';"] = "5",
        ["basescore='10';"] = "10",
        ["basescore='20';"] = "20",
    },
}

return CreateBoxRoomConfig|%  